### ISSUE TITLE
Plotting the Efficient Frontier

### ISSUE THREAD

**Issue by jackmoody11** [robertmartin8/PyPortfolioOpt#1]
[Here is a good article](https://towardsdatascience.com/efficient-frontier-portfolio-optimisation-in-python-e7844051e7f) that might be valuable for plotting the result of the efficient frontier. I can help with this if wanted.

**Comment by jackmoody11** [comment]
I also found [this notebook](https://github.com/yhilpisch/py4fi/blob/master/jupyter36/11_Statistics_a.ipynb) that seems to do what you are describing

**Comment by robertmartin8** [comment]
@jackmoody11 

I've got the code for plotting all ready, but I'm just trying to figure out where it should fit into this library. For example, the plots in those links require a monte carlo process first (to generate all the dots).

**Comment by jefferson2z** [comment]
Maybe we could discuss about it and I could help implementing it?

**Comment by robertmartin8** [comment]
@jefferson2z after giving it a lot of thought, I'm still not certain whether it belongs in this package. I will continue to evaluate and let you know if I plan to. 

Thanks!

**Comment by jefferson2z** [comment]
Thank you,
I'll be forking it and adding the functionality for now. If more people are interested in it you could redirect them to me.
