### ISSUE TITLE
Issue with HRP Optimizer

### ISSUE THREAD

**Issue by mlaricheva** [robertmartin8/PyPortfolioOpt#103]
Hi!
I was trying to test HRP optimizer but i've recently encountered a problem.
So my dataset consists of regular stocks (from Russian Moscow Exchange) - nothing unusual about them, but the results of optimization are just inadequate as HRP optimizer proposes portfolio that consists of one stock for 98% and others are taken with the smallest percentage.
I made sure that data provided has no anomalies and i have even tested it with Efficient Frontier and it gave me the result that seems right (less than 20% of one stock were taken).

Also, I wanted to mention that I tried it on the stocks that you were using in provided example (but imported them myself from yfinance) and the optimizer worked fine, so I'm really confused about the problem here.

P.S. I cloned the repo from GitHub because the optimize() method was not working from pip.

**Comment by robertmartin8** [comment]
Hi @mlaricheva,

Thanks for reaching out!

> HRP optimizer proposes portfolio that consists of one stock for 98% 

That's very strange, I've never seen HRP do something like that. One reason it could happen is if one of your assets has much higher covariance than all of the others, and is also in an independent cluster. I would expect this to affect `EfficientFrontier` also, but perhaps it could be balanced out by very high return estimates.

Could you try creating a covariance matrix from your stocks and see if there's anything funny about it? In particular, check the diagonal to see if there are any outliers in terms of variance.

> P.S. I cloned the repo from GitHub because the optimize() method was not working from pip.

Thanks for letting me know about this, I'll look into it

Best,
Robert

**Comment by mlaricheva** [comment]
Hi @robertmartin8,

Thanks for coming back to me! I've done some tests again and here's what I found. I couldn't find anything unusual in cov matrix where i received such an imbalanced portfolio, so im kinda out of guesses on what could be wrong.
![cov_matrix](https://user-images.githubusercontent.com/47871121/80351429-f8379000-887a-11ea-87c2-a0e7e960e81b.png)

The stock that got 98% is VTBR.ME. I tried to exclude it but the problem happened again -- this time HRP chose 80% of HYDR.ME. What is strange is that Efficient Frontier have evenly spread among 20 stocks and had a higher performance with expected return of 43% (both times, btw, on the same data of 36 and 35 stocks).

Here is also the dendogram of stocks, I cant find anything here but may be I'm missing something 
![dend](https://user-images.githubusercontent.com/47871121/80351734-7dbb4000-887b-11ea-82ba-2a9cd2a4ea5c.png)

I'm really confused about it and would appreciate any help

**Comment by robertmartin8** [comment]
> The stock that got 98% is VTBR.ME. I tried to exclude it but the problem happened again -- this time HRP chose 80% of HYDR.ME. What is strange is that Efficient Frontier have evenly spread among 20 stocks and had a higher performance with expected return of 43% (both times, btw, on the same data of 36 and 35 stocks). 

@mlaricheva I'll have a think about, it's a very strange issue.

@tschm I wonder if this is related to anything we discussed. The dendrogram looks fine..

**Comment by tschm** [comment]
@mlaricheva You have provided a heat map of the correlation matrix (all diagonal entries are 1). Could you please try to do the same for the covariance matrix? It looks to me that VTBR ends up on position 9 in a cluster of 18 (using recursive bisection). So, in particular, I would like to see RTKE vs VTBR as these two will be a cluster if we follow recursive bisection all the way down. So has VTBR a variance 100times smaller than RTKE?

**Comment by mlaricheva** [comment]
@tschm Yeah, sorry, I used plot_covariance, but now i see that it plots the correlation matrix. Here you can see covariance matrix of the two assets mentioned. 
![cov](https://user-images.githubusercontent.com/47871121/80382680-3a78c580-88ab-11ea-9b14-099c81136399.png)

I think you are right and variance plays a role here, but im not sure how to work with it. As I mentioned, if I leave the VTBR, the optimizer just gets stuck on some other stock. I also tried to change the period before (now it 1yr, but before was almost 10yr), but the result was the same.
Is it possible add some constraints inside the HRROpt calculations without trying to make a custom optimizer?

**Comment by robertmartin8** [comment]
@mlaricheva 

Regarding constraints, unfortunately not. HRP is relatively new in academia, and to my knowledge, there currently aren't any widely-accepted methods for constraining weights. That's one of the areas of research. 

I'll try to think of what else could be causing it, but it's a little bit difficult without having your data. Maybe you could export your covariance matrix to a csv file and share it here, then we can have a deeper look? 

PyPortfolioOpt's implementation of HRP is very similar to the original de Prado implementation, so if it's failing, then I reckon de Prado's code would fail too. In which case it's an interesting edge case

**Comment by mlaricheva** [comment]
Hi again guys, 

Spend some time looking and found out that i pass to HRPOpt the historical dataframe and not the returns! Somehow it has eluded from me. So I added one line and it's working fine now. And that is the explanation why the Efficient Frontier was showing better results: it calculated the cov matrix and mu from the same dataframe as it should be. 

Big thanks for all your support! @robertmartin8 btw, i really enjoy your library, getting some thoughtful insights
