### ISSUE TITLE
Add_constraints issue

### ISSUE THREAD

**Issue by krisutopian** [robertmartin8/PyPortfolioOpt#106]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Operating system and python version:**
e.g MacOS 10.146, python 3.7.3

**Additional context**

**Comment by krisutopian** [comment]
Hi,
Recently i installed PyportfolioOpt.

However i try to test for simply add_constraints from the documentations however i keep getting error.

The code:
from pypfopt.efficient_frontier import EfficientFrontier
from pypfopt import risk_models
from pypfopt import expected_returns

mu = expected_returns.mean_historical_return(table)
s = risk_models.sample_cov(table)
ef = EfficientFrontier(mu, s, weight_bounds=(0, 1))
ef.add_constraint(lambda weights : weights[0] <= 0.02)
weights = ef.min_volatility()
cleaned_weights = ef.clean_weights()

Error: AttributeError: 'EfficientFrontier' object has no attribute 'add_constraint'

**Comment by robertmartin8** [comment]
@krisutopian 

Thanks for reaching out! Could I ask what version of PyPortfolioOpt are you using? You can install the latest using `pip install -U pyportfolioopt`. You can check the version by `import pypfopt; pypfopt.__version__`. 

Let me know if that doesn't work and we'll figure it out :)

Best,
Robert

**Comment by krisutopian** [comment]
Dear @robertmartin8,

Thank you for your help. I manage to solve it by deleting the environment, delete conda cache then recreate new python 3.7 conda env. I realized I was using older version of PyPortfolioOpt. 

Could you please send me any example code on how to create objective & constraint using pyportfolioopt? I am still new in python and I could not really understand it by referring to the existing documents. Thank you!

**Comment by robertmartin8** [comment]
@krisutopian 

The code sample in the image you sent is correct – there's also an [examples.py](https://github.com/robertmartin8/PyPortfolioOpt/blob/master/examples.py) file that highlights the various things you can do.

I recognise that the examples file is a bit crude, so some time this week I'll be pushing a couple of jupyter notebooks with complete examples, from downloading data to constructing an actual portfolio.

Until then, if you tell me what specific problem you're trying to solve (i.e what objectives and constraints), I can help you write a code snippet that gets it done.

Best,
Robert

**Comment by krisutopian** [comment]
@robertmartin8 

Yes, I kinda understand from the examples.py. I am currently trying to test simple optimization and adding constraints based on sector. For example stocks a, b & c (IT Sectors) will be always less than or equal to 30 % of the portfolio after optimize.

Thank you again for your effort.

**Comment by robertmartin8** [comment]
@krisutopian 

To do that, you need to know the index of the tickers:

```python
ef = EfficientFrontier(mu, S)
print(ef.tickers)  # ["a", "f", "c", "b"]
```

So you see that your stocks a, b, c have indices 0, 2, 3 (remember, python counts from zero). It is possible to automatically do this using `a_index = ef.tickers.index("a")` etc.

Once you have these indices, you can add a constraint:

```python
ef.add_constraint(lambda w: w[0] + w[2] + w[3] <= 0.3)
weights = ef.min_volatility()
```

As of `v1.2.1`, I've added an new API for sector constraints. An example is shown below:

```python
sector_mapper = {
    "MSFT": "Tech",
    "AMZN": "Consumer Discretionary",
    "KO": "Consumer Staples",
    "MA": "Financial Services",
    "COST": "Consumer Staples",
    "LUV": "Aerospace",
    "XOM": "Energy",
    "PFE": "Healthcare",
    "JPM": "Financial Services",
    "UNH": "Healthcare",
    "ACN": "Misc",
    "DIS": "Media",
    "GILD": "Healthcare",
    "F": "Auto",
    "TSLA": "Auto"
}

sector_lower = {
    "Consumer Staples": 0.1, # at least 10% to staples
    "Tech": 0.05 # at least 5% to tech
    # For all other sectors, it will be assumed there is no lower bound
}

sector_upper = {
    "Tech": 0.2,
    "Aerospace":0.1,
    "Energy": 0.1,
    "Auto":0.15
}

ef = EfficientFrontier(mu, S)
ef.add_sector_constraints(sector_mapper, sector_lower, sector_upper)
ef.max_sharpe()
```

I'll let you know once the full examples is up!

Best,
Robert

**Comment by robertmartin8** [comment]
@krisutopian 

I've pushed an initial version of the notebook, check it out [here](https://github.com/robertmartin8/PyPortfolioOpt/blob/master/cookbook/2-Mean-Variance-Optimisation.ipynb).

Please reopen this thread if you still have any issues!

Best,
Robert

**Comment by krisutopian** [comment]
@robertmartin8 

Thank you for your effort!

**Comment by krisutopian** [comment]
@robertmartin8 

The notebook version is clear and easy to understand. Thank you!
I will continue developing our optimization/simulation strategy using pyportfolioopt.
