### ISSUE TITLE
Could not install on Windows Anaconda 

### ISSUE THREAD

**Issue by JChung123** [robertmartin8/PyPortfolioOpt#109]
**Operating system, environment, python version**
Windows 10, anaconda, python 3.7

**What you tried**
pip install PyPortfolioOpt (from Spyder)

**Error message**
```
Copy paste the terminal message here
when trying to import : from pypfopt import EfficientFrontier

Traceback (most recent call last):
  File "<ipython-input-7-9a826826cd11>", line 1, in <module>from pypfopt import EfficientFrontier
ImportError: cannot import name 'EfficientFrontier' from 'pypfopt' (C:\ProgramData\Anaconda\lib\site-packages\pypfopt\__init__.py)
```

Do you think is the initial installation that is not correctly done or is there something else? 

Many thanks

Jonathan

**Comment by robertmartin8** [comment]
HI @JChung123 

What happens if you `import pypfopt`?

If that works, then this is a versioning issue – try `pip install -U pyportfolioopt`.

Robert

**Comment by JChung123** [comment]
Thanks Robert for your quick reply and seems to work. I can import most module now except plotting:
seems like a similar issues but not sure why I can import say efficient_frontier and discrete_allocation, but not plotting?

Error below:
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-60-587fb7c16c73> in <module>
      1 from pypfopt import risk_models
----> 2 from pypfopt.plotting import Plotting
      3 
      4 sample_cov = risk_models.sample_cov(df,frequency = 12)
      5 sample_cov

ModuleNotFoundError: No module named 'pypfopt.plotting'

Thanks

Jonathan

**Comment by robertmartin8** [comment]
Can you run `import pypfopt; print(pypfopt.__version__)` just to be sure?

That's very strange. You also should be able to import Plotting directly, e.g `from pypfopt import Plotting`.

**Comment by JChung123** [comment]
very odd indeed. I can't even run your code and getting below error:

Traceback (most recent call last):

  File "<ipython-input-16-e8d9d52f8463>", line 1, in <module>
    print(pypfopt.__version__)

AttributeError: module 'pypfopt' has no attribute '__version__'

though I ran "pip list" to show below.. if that helps:

![image](https://user-images.githubusercontent.com/64885279/81153797-9be51680-8fc6-11ea-8f25-27b8fad64022.png)

Thanks

Jonathan

**Comment by robertmartin8** [comment]
That's quite helpful! PyPortfolioOpt is currently on v1.2.1.

Could you try pip install PyPortfolioOpt==1.2.1

**Comment by JChung123** [comment]
Thanks Robert, will try again once I manage to install the latest version, seems like some kind of firewall is blocking me to install cvxpy during the installation, will contact IT to see if this can be lifted. 

Thanks for all your help so far, have a good one!

**Comment by AnushangaWimalasena** [comment]
`pip install PyPortfolioOpt `command will install those packages according to your default python version in the OS. That version might not match your virtual env. Therefore follow these steps.

1. activate your conda env
2.  Then in cmd  type `python -m pip install PyPortfolioOpt`

This method works for me.
