### ISSUE TITLE
Only for shorts

### ISSUE THREAD

**Issue by fepshampshire** [robertmartin8/PyPortfolioOpt#11]
Hi there!!

can we optimize only for shorts? I tried setting the weight_bounds to (-1,0) but the result are nan's.

tks!

**Comment by robertmartin8** [comment]
Hi,

That's quite an interesting question and something that I've never even thought of. I'm not sure whether the short-only portfolio optimisation problem can be solved by a convex optimiser (I've never seen any explicit comments on this), but I can't think why it wouldn't be able to.

Unfortunately I have quite a lot on my plate right now so may not be able to suitably dig into this problem. Here's a cheap trick that might work: flip the sign of all the returns, then maximise a long-only portfolio :) 

I will let you know if I have any new insight onto this. Until then, I'd love to hear anyone else's thoughts on this matter.

Robert

**Comment by fepshampshire** [comment]
Hi @robertmartin8. 

Very nice idea inverting the returns. I think will work for me perfectly.
Other quick question regarding the weights... you know if I'm able to limit the minimum and maximum weight for both long and short?

tks!!!!!!

**Comment by robertmartin8** [comment]
That is done by modifying the weight bound parameter. If you want the maximum weight for longs to be 50%, and shorts to be -30%, you'd do:

```python
ef = EfficientFrontier(mu, S, weight_bounds=(-0.3, 0.5))
```

Let me know if you have any trouble with that.

Robert

**Comment by robertmartin8** [comment]
I have added a comment about this in the docs.
