### ISSUE TITLE
Minimum variance w/ target return

### ISSUE THREAD

**Issue by asjem** [robertmartin8/PyPortfolioOpt#110]
**What are you trying to do?*
Hi - appreciate the library, just wondering what the best way to solve a minimum variance portfolio w/ a target risk constraint? Or is that just the same as ef = EfficientFrontier(None, cov); ef.efficient_risk(x)? I don't want to use estimated returns, only volatility.

**Comment by robertmartin8** [comment]
Hi @asjem,

Thanks for reaching out! I'm afraid I don't fully understand your question: the minimum variance portfolio (`ef.min_volatility()`) will give you the portfolio weights that result in the lowest possible variance. For example, in the test dataset, the minimum volatility is 16%. 

Conversely, target-risk constraints constrain the portfolio to a particular level of volatility. So `ef.efficient_risk(0.20)` would aim to maximise return for a set risk level of 20%. 

So in that sense, you wouldn't ever need to put a risk constraint on the minimum volatility portfolio. On the other hand, you may want to explicitly limit the maximum weight of any single asset. This can be done in the constructor:

```python
ef = EfficientFrontier(None, cov, weight_bounds=(0, 0.3)) # no stock can have more than 30%
ef.min_volatility()
weights = ef.clean_weights()
ef.portfolio_performance(verbose=True)
```

Please let me know if I've misinterpreted, and don't hesitate to follow up :) 

Best,
Robert

**Comment by asjem** [comment]
Thanks for the reply. I want to optimize to a certain portfolio volatility
level, so sort of like efficient_risk but w/o the dependency on returns. I
just found the custom objective/constraint API which I can probably make
work.

**Comment by robertmartin8** [comment]
Interesting, I've never done that before. I think the easiest way forward is for you to produce a dummy vector of expected returns (e.g filled with ones), then just use `efficient_risk`. Let me know how it goes!

**Comment by robertmartin8** [comment]
Discussion is continuing in #116
