### ISSUE TITLE
setting minimum sector constraint

### ISSUE THREAD

**Issue by JChung123** [robertmartin8/PyPortfolioOpt#112]
**Describe the bug**
I am trying to set each sectors to have minimum weights, so there is at least some weights to each sectors and avoid 0% weighting to any sectors. I do so by using sector_constraints by setting up lower sector limit, but some sectors still producing 0 weights?

**Expected behavior**
Expect there are no 0% weight sectors, or is there just no solutions based on the constriants? shouldn't it give an error warning instead in that case?

**Screenshots**

![image](https://user-images.githubusercontent.com/64885279/81528888-fef8f380-93a0-11ea-80bd-647762925350.png)

![image](https://user-images.githubusercontent.com/64885279/81528990-3cf61780-93a1-11ea-8005-034a2c9e2227.png)

**Operating system and python version:**
python 3.7

**Additional context**

**Comment by robertmartin8** [comment]
Thanks for raising this bug – can I check what version of PyPortfolioOpt you're using? There were some issues that I rectified in v1.2.1

**Comment by JChung123** [comment]
ah.. OK. understand how it works now. .thanks for clarifying!

**Comment by JChung123** [comment]
Hi Robert

I am trying to make this works by sending weights bounds like you suggested, and using ef._map_bounds_to_constraints. But I am getting below error message. But my arrays are all real numbers, why do you think am getting NaN issue? Sorry this may be a simple question, but I can't get my head around it..

![image](https://user-images.githubusercontent.com/64885279/82152509-122a2880-98a5-11ea-9e77-0880a871ff49.png)

Thanks

Jonathan

**Comment by robertmartin8** [comment]
Hi Jonathan,

You haven't done anything wrong – I think you're on a slightly older version of `numpy`. As of v1.17 and above, `nan_to_num` accepts a keyword argument to specify how to fill nan. If you `pip install --upgrade numpy` I think this problem should go away. Let me know if that works for you!

Best,
Robert

**Comment by JChung123** [comment]
Thanks Robert. Works like a charm.. thanks for your help and great project, thanks a bunch!
