### ISSUE TITLE
File b'tests/resources/stock_prices.csv' does not exist

### ISSUE THREAD

**Issue by charlynielsen** [robertmartin8/PyPortfolioOpt#120]
Hello, I recently installed PyPortfolioOpt and run the first example:

```
import pandas as pd
from pypfopt import EfficientFrontier
from pypfopt import risk_models
from pypfopt import expected_returns

df = pd.read_csv("tests/resources/stock_prices.csv", parse_dates=True, index_col="date")

mu = expected_returns.mean_historical_return(df)
S = risk_models.sample_cov(df)

ef = EfficientFrontier(mu, S)
raw_weights = ef.max_sharpe()
cleaned_weights = ef.clean_weights()
ef.save_weights_to_file("weights.csv")  # saves to file
print(cleaned_weights)
ef.portfolio_performance(verbose=True)
```

and an error came out: 

```
FileNotFoundError: [Errno 2] File b'tests/resources/stock_prices.csv' does not exist: b'tests/resources/stock_prices.csv'
```

Any ideas?

**Comment by robertmartin8** [comment]
Hi,

To get the example to work, you should download the `stock_prices.csv` file and put it in whatever directory that you are testing the project in. Then change the `test/resources/stock_prices.csv` to just `stock_prices.csv`.

So let's say your project folder is called `portfolio/`, you should download `stock_prices.csv` into that folder. Then you can create a python file `my_file.py`, copy-paste the example code, and change the data reading to:

```python
df = pd.read_csv("stock_prices.csv", parse_dates=True, index_col="date")
```

That ought to work!

Best,
Robert

**Comment by charlynielsen** [comment]
Great! Thank you very much!!
