### ISSUE TITLE
Great project

### ISSUE THREAD

**Issue by lefig** [robertmartin8/PyPortfolioOpt#121]
Just a brief mention of thanks.

Your work really fills a void in the asset management/portfolio domain.

**Comment by robertmartin8** [comment]
Thanks for the kind words! I'm glad you're deriving value from it :)

**Comment by lefig** [comment]
Absolutely. There are many many algo or trade signal like frameworks. 

But here are very very few that address portfolio selection and optimisation domain scenarios. 

And even fewer that at readily accessible and practical for users such as myself without any math background. :)
