### ISSUE TITLE
Can I add a custom objective?

### ISSUE THREAD

**Issue by JChung123** [robertmartin8/PyPortfolioOpt#122]
Hi Robert
Thanks for the library, still exploring it but find it very useful.

Just wanted to assigned some scores to my assets and minimise the overall Market Value weighted average score. Initially I thought I can add an objective via your custom objective, but think the custom objective functions are not use for "adding" a new objective to the optimisation problem? Is my understanding correct?

I am not sure if I can use add constraint to achieve this?

Welcome any of your thoughts.

Regards

Jonathan

**Comment by robertmartin8** [comment]
Hi @JChung123,

The "proper" way to do this in PyPortfolioOpt is with the `ef.convex_objective()` function, which is called after you instantiate via `ef = EfficientFrontier()`. The only challenging part here is to write your objective function using `cvxpy` atoms, though if you are just doing a dot product this isn't necessary.

In your case, it will probably be something like this:

```python
market_scores = np.array(...).reshape(-1, 1)

def market_score_objective(w, score):
    return w @ score   # minimise dot product of weight and scores

ef = EfficientFrontier()
ef.add_constraint()  # add your custom constraints 
ef.convex_objective(market_score_objective, score=market_scores)
weights = ef.clean_weights()
```

There are a couple of further examples in this [cookbook recipe](https://github.com/robertmartin8/PyPortfolioOpt/blob/master/cookbook/3-Advanced-Mean-Variance-Optimisation.ipynb).

Let me know if that works for you!

Robert

**Comment by robertmartin8** [comment]
Closing for now, let me know if you have any other problems!
