### ISSUE TITLE
Installing on Python 3.5.x does not result in a proper __init__.py

### ISSUE THREAD

**Issue by 1D0BE** [robertmartin8/PyPortfolioOpt#123]
**Describe the bug**
The installation is missing the necessary linkages in `__init__.py` on Python 3.5.x to be able to import the classes from pypfopt properly.

**Expected behavior**
Being able to import all classes properly.

**Screenshots**
None

**Operating system and python version:**
Windows 10 with Python 3.5.4 - amd64

**Additional context**

**Solution**

Add following content to `__init__.py` of the package during installation:

```
from .black_litterman import (
    market_implied_prior_returns,
    market_implied_risk_aversion,
    BlackLittermanModel,
)
from .cla import CLA
from .discrete_allocation import get_latest_prices, DiscreteAllocation
from .efficient_frontier import EfficientFrontier
from .hierarchical_risk_parity import HRPOpt # different name for whatever reason
from .risk_models import CovarianceShrinkage
# from .plotting import Plotting # Not in 3.5 version for some reason


__version__ = "1.2.1"

__all__ = [
    "market_implied_prior_returns",
    "market_implied_risk_aversion",
    "BlackLittermanModel",
    "CLA",
    "get_latest_prices",
    "DiscreteAllocation",
    "EfficientFrontier",
    "HRPOpt",
    "CovarianceShrinkage",
    #"Plotting",
]

```

I'm adding it here, so you may check if the issue is always persisting or only Windows-python35 specific.
Thanks for developing the package btw. I love it.

**Comment by robertmartin8** [comment]
@1D0BE 

Thanks for raising this, it's quite a strange issue. Sometime this week I'm going to have a proper look into the current packaging/dependencies as there have been many issues lately. 

One thing I would add is that python 3.5 is not explicitly supported – the reason for this is that some methods in PyPortfolioOpt implicitly make use of dictionaries preserving order (especially in Black-Litterman). So there might be unpredictable failures for python <3.6. 

Robert

**Comment by 1D0BE** [comment]
@robertmartin8 

Thanks for clarifying. I have since upgraded to  3.7.2, so this is not relevant to me, but to others, support of Python 3.5 could be crucial, as this version is necessary for use of zipline, a common backtesting library.

Link:[here](https://www.zipline.io/)

**Comment by robertmartin8** [comment]
Thanks for letting me know about that! I might have a go at changing all
current dictionary usage to OrderedDict so that this works properly in
v3.5.

**Comment by robertmartin8** [comment]
Most of PyPortfolioOpt now supports python 3.5. The major exception is Black-Litterman – the features involving the convenient creation of inputs (by passing `absolute_views` or `view_confidences`) may not work as intended because they rely on dictionaries being ordered. But I've made sure that the EfficientFrontier functionality works and that the `setup.py` specifies `>=3.5`.
