### ISSUE TITLE
Exporting Efficient Frontier?

### ISSUE THREAD

**Issue by mariotq** [robertmartin8/PyPortfolioOpt#124]
Hi, first of all I would like to apologize because this is my the first time using Python and it may be that some of my doubts are basic.

I'm trying to create the efficient border and then export it (in csv) in the following format:
 risk, return, asset weights.

But I'm not getting it. Is there a way to do it?

I managed to export one portfolio at a time (ef.save_weights_to_file) but without the risk and return parameters.

Thank you

**Comment by robertmartin8** [comment]
For this, you probably want the Critical Line Algorithm ([docs](https://pyportfolioopt.readthedocs.io/en/latest/OtherOptimisers.html#pypfopt.cla.CLA))

```python
from pypfopt import CLA, Plotting

cla = CLA(expected_returns, cov_matrix)
mu, sigma, weights = cla.efficient_frontier(points=100)
```
`mu` and `sigma` are now lists corresponding to the return and std of 100 points on the efficient frontier. `weights` is now a list of lists – for each point on the efficient frontier, it's a list of weights. 

You can then combine these into a dataframe however you want and export to excel

Robert

**Comment by mariotq** [comment]
Tks, i will try.

**Comment by mariotq** [comment]
is it possible to use estimated risk and return assumptions?

For example, I believe that the risk of a particular stock will not be 20% but 22% or the return will not be 10% but 4%.

The list with the returns, I managed to import. However, the new varcovar matrix I was unable to make the CLA use.

it's possible?

**Comment by robertmartin8** [comment]
Hi @mariotq,

I'm afraid I don't fully understand what you're asking. If you want to override the expected returns or sample covariance matrix, you can do so before passing them to `CLA`. e.g

```python
mu["AAPL"] = 0.04
S["AAPL"]["AAPL"] = 0.22 ** 2   # diagonal of cov matrix is variance, not std

cla = CLA(mu, S)
eff_mu, eff_sigma, eff_weights = cla.efficient_frontier(points=100)
```

Is this what you meant?

Robert

**Comment by mariotq** [comment]
I`m sorry. 

I want using my own assumptions of assets, importing my covariance matrix and expected returns. 

Perhaps with my code and data you can understand.

[Code.txt](https://github.com/robertmartin8/PyPortfolioOpt/files/4668620/Code.txt)
[limites_premissas.xlsx](https://github.com/robertmartin8/PyPortfolioOpt/files/4668621/limites_premissas.xlsx)
[varcovar_comnomes.xlsx](https://github.com/robertmartin8/PyPortfolioOpt/files/4668622/varcovar_comnomes.xlsx)

**Comment by robertmartin8** [comment]
Hi @mariotq,

```python
S  = pd.read_excel("varcovar_comnomes.xlsx", sheet_name="Planilha1", header=0, index_col=0)
S = S * 252  # your data looks like it is daily so multiply by 252 to get annual
mu = pd.read_excel("limites_premissas.xlsx")["ret"]  
```

For future reference, the [pandas documentation on input/output](https://pandas.pydata.org/pandas-docs/stable/reference/io.html) might be helpful.

Best,
Robert
