### ISSUE TITLE
How to plot nicely formatted efficient frontier

### ISSUE THREAD

**Issue by x829901** [robertmartin8/PyPortfolioOpt#126]
The efficient frontier on your main page is very colorful and nicely formatted. But I couldn't find anything in your repository that creates it. All I could find was:

`Plotting.plot_efficient_frontier(cla)  # to plot` 

And that just make a simple very basic efficient frontier plot. How did you make the colorful efficient frontier?

**Comment by robertmartin8** [comment]
The colourful efficient frontier plot, though pretty, isn't actually very informative. All of the dots on it represent random portfolios, coloured by the Sharpe ratio. I generated this by a simple Monte Carlo script, which looked something like:

```python
returns = []
sigmas = []
sharpes = []
n_assets = 20
for _ in range(10000):
    w = np.random(n_assets, 1)
    w /= w.sum()
    ret = mu.T @ w
    std = np.sqrt(w.T @ S @ w)
    returns.append(ret)
    sigmas.append(std)
    sharpes.append(ret/std)
```
