### ISSUE TITLE
How to [define the target return and target volatility]?

### ISSUE THREAD

**Issue by tomekstarfunds** [robertmartin8/PyPortfolioOpt#129]
**What are you trying to do?*
I'm trying to create portfolio with target return and target volatility.

**What data are you using?**
The data from Datastream for SPX500, dailly closing prices.

I'm not sure what should be target return and target volatility timeframe. Should it be annualized or adopted to the frequency of input data (dailly in my case).

**Comment by robertmartin8** [comment]
Hi @tomekstarfunds,

PyPortfolioOpt currently doesn't offer an explicit way to optimise for both target return and volatility simultaneously, but if you are using `ef.efficient_risk()` or `ef.efficient_return()`, you should pass an **annual target.** 

Hope that helps!

Robert

**Comment by tomekstarfunds** [comment]
Hi,

Thank you. That is what I was looking for.

Tomasz
