### ISSUE TITLE
hierarchical_portfolio.HRPOpt

### ISSUE THREAD

**Issue by RazHadas** [robertmartin8/PyPortfolioOpt#130]
I tried to replace (EfficientFrontier(mu, S))  to (hierarchical_portfolio.HRPOpt(mu,S)) and I got error: TypeError: returns are not a dataframe. 
In user guide it's written that return should be pd.series. Also when I change mu to pd.dataframe i got:
ValueError: The number of observations cannot be determined on an empty distance matrix.
How should I use correctly hierarchical_portfolio.HRPOpt.

![image](https://user-images.githubusercontent.com/65238333/83018888-b3944580-a02e-11ea-9b7d-423b18ed19d0.png)

**Comment by robertmartin8** [comment]
Hi @RazHadas,

`HRPOPt` requires the raw asset returns, rather than the expected returns:

```python
df = pd.read_csv("tests/resources/stock_prices.csv", parse_dates=True, index_col="date")
returns = df.pct_change().dropna()

# Hierarchical risk parity
hrp = HRPOpt(returns)
weights = hrp.optimize()
hrp.portfolio_performance(verbose=True)
print(weights)
Plotting.plot_dendrogram(hrp)  # to plot dendrogram
```

Hope this helps!
