### ISSUE TITLE
plotting.py:144: RuntimeWarning: More than 20 figures have been opened.

### ISSUE THREAD

**Issue by nojaba** [robertmartin8/PyPortfolioOpt#131]
Hi,
When I use plot to draw efficient frontier and covariance charts and set a file name to save the results, after saving some images it raises this warning.
I try to correct this by adding the line 
plt.cla()
after the 
plt.savefig(fname=filename, dpi=dpi)
but it does'nt work.
Also I try to close the plt but could not.

**Screenshots**
/lib/python3.7/site-packages/pyportfolioopt-1.2.2-py3.7.egg/pypfopt/plotting.py:144: RuntimeWarning: More than 20 figures have been opened. Figures created through the pyplot interface (`matplotlib.pyplot.figure`) are retained until explicitly closed and may consume too much memory. (To control this warning, see the rcParam `figure.max_open_warning`).

Thanx for your help
Best Regards 
Barmak

**Comment by robertmartin8** [comment]
Hi Barmak,

Thanks is a common problem with matplotlib. Could you try `plt.close("all")`? Failing that, perhaps some of the suggestions in this [SO post](https://stackoverflow.com/questions/21884271/warning-about-too-many-open-figures) might help.

Best,
Robert

**Comment by nojaba** [comment]
Thank you.
I try that before and it works. But in case of using with simultaneous user it may cause problem.
I want to close only the plot handle of the current session user. But It could be ignore.
Many thanks
& Regards
Barmak

**Comment by robertmartin8** [comment]
I think `plt.close()` just closes the latest figure, so you could run that after each generating each plot.
