### ISSUE TITLE
Could not install on Windows [replace with your environment]

### ISSUE THREAD

**Issue by pitabasm** [robertmartin8/PyPortfolioOpt#132]
**Operating system, environment, python version**
e.g Windows, anaconda, python3.7

**What you tried**
poetry add PyPortfolioOpt

**Error message**
```
Poetry could not find a pyproject.toml file in C:\Users\HP or its parents
```

**Comment by robertmartin8** [comment]
Does pip install work?

**Comment by pitabasm** [comment]
I tried that also. I am getting this error message there:

Could not build wheels for cvxpy which use PEP 517 and cannot be installed directly

**Comment by pitabasm** [comment]
I could install it. I did not install Visual Studio earlier. Now it is working.

**Comment by robertmartin8** [comment]
@pitabasm Cool, I'm glad you managed to get it working!
