### ISSUE TITLE
How can I remove constraint of weights adding to 1 or 0?

### ISSUE THREAD

**Issue by hnicks13** [robertmartin8/PyPortfolioOpt#134]
I am trying to optimise a fixed income portfolio where my active exposures vector (ie. relative to benchmark) is a mix of FX weights and weighted durations. Clearly there is no reason why the exposures will add to zero (the FX weights will but not if you include the durations), in contrast to the simple case of an equity portfolio. I understand that the EfficientFrontier class has a built in constraint that forces the sum of weights to be 1 or 0. The guides explain how to add extra constraints but not how to visualise the built in default constraints and how to edit them? How can I remove the constraint on sum of weights?

**Comment by robertmartin8** [comment]
@hnicks13 

For the EfficientFrontier methods there are only two default constraints, the weight bounds which can be modified in the constructor, and the sum of weights. There is no easy way to change the sum of weights constraint (apart from using `market_neutral=True` for the methods that support it). 

The reason for this is that in my view, any nonzero positive sum-of-weight constraint can be produced from the sum-to-one constraint by rescaling the weights afterwards. If you want the weights to sum to 0.5, you can optimise with sum-to-one then divide everything by 2. Hence the only cases that need to be covered are sum-to-one and sum-to-zero.

If that doesn't work for you, you can use the custom objective functionality in `ef.convex_objective()`, documented [here](https://pyportfolioopt.readthedocs.io/en/latest/EfficientFrontier.html#pypfopt.base_optimizer.pypfopt.base_optimizer.BaseConvexOptimizer.BaseConvexOptimizer.convex_objective). If you set `sum_to_one=False`, then it does not add such a constraint. So you can do something like:

```python
import cvxpy as cp
from pypfopt import objective_functions, EfficientFrontier

ef = EfficientFrontier(mu, S, (None, None)) # no weight bounds
ef.add_constraint(lambda w: cp.sum(w) == 0.3)
ef.convex_objective(objective_functions.portfolio_variance, cov_matrix=S)
```

Hope that helps!

Robert

**Comment by hnicks13** [comment]
@robertmartin8  many thanks for such a quick response! I will try what you suggested.

**Comment by hnicks13** [comment]
@robertmartin8 I had a go at this by doing the below. Essentially, what I simply want to achieve is: maximise a  function of weights (portfolio carry in my case, same logic as maximising return) for a given target risk, with no constraint on sum of weights but with customised constraints for individual exposures. I defined my customised exposure constraints in a np.array called 'weight_constraints'.

ef =EfficientFrontier(Carry,Sigma, (None, None))
ef.add_constraint(lambda w: w[:55] <= weight_constraints[:55])
ef.add_constraint(lambda w: w[:55] >= -1*weight_constraints[:55])
ef.add_constraint(lambda w: w[56:] == weight_constraints[56:])
ef.convex_objective(objective_functions.portfolio_variance, cov_matrix=Sigma, weights_sum_to_one=False)

I understand that the output of that is the minimum variance portfolio and I checked the sum of weights do not add to 1 which is good! However, now I want to return the optimal portfolios for a series of target risk levels. When I try ef.efficient_risk(0.01) I get an error:
OptimizationError: Please check your objectives/constraints or use a different solver

Does this mean I need to use the nonconvex_objective? But even in that case, would I be able to achieve my goal (both solvers, seem to minimise an objective but I want to enter a target risk and maximise a function). Many thanks in advance.

**Comment by hnicks13** [comment]
Please ignore my earlier message. It was easy enough to replace the objective with the negative of what I need to maximise using a cp function. All works fine so far. The last sticking point is that I now have to add my portfolio volatility as a constraint. I tried to express it with np functions (1) and cp functions (2) but they both fail: (1) gives a syntax error and (2) an optimisation error:

(1) ef.add_constraint (lambda w: np.dot(w.T, np.dot(Sigma,w)**0.5 == 0.01)
(2) ef.add_constraint (lambda w: cp.quad_form(w, Sigma)==0.01)

How can I do this?

**Comment by robertmartin8** [comment]
@hnicks13

Currently you can only specify risk constraints as inequalities, i.e:

```python
 ef.add_constraint (lambda w: cp.quad_form(w, Sigma)<=0.01)
```

This is discussed in great detail in #116 

Best,
Robert

**Comment by hnicks13** [comment]
Thanks for the link, I read the thread carefully and indeed the issue raised by those users is the same as mine. I agree that it would be ideal to be able to specify the target risk as an equality. However, the good news is that <= seems to give the same answers as == and I tested that for my portfolio by solving for various levels of risk! This is something already mentioned by someone in the thread. In theory it makes sense since the optimiser would go for the highest allowed level of risk in order to maximise returns (and not for anything less than that). So all works great!

**Comment by robertmartin8** [comment]
Fantastic! Let me know if you have any other issues
