### ISSUE TITLE
sample_cov() method returning very odd results

### ISSUE THREAD

**Issue by hnicks13** [robertmartin8/PyPortfolioOpt#136]
I first used this on my dataframe: Sigma = risk_models.sample_cov(df_ret)
Then I re-calculated the covariance matrix using: Cov = df_ret.cov()

Comparing the two, the first one is giving very weird numbers that are huge! 
The second one is closer to the expected values.
For instance, for one pair, sample_cov() gave 181,075.774 and cov() gave 0.0000009617663  !!

Is there some kind of scaling going on in sample_cov and, more generally, what is the difference to the cov() calculation?

Many thanks in advance.

**Comment by robertmartin8** [comment]
@hnicks13 

`sample_cov` is meant to be passed the **prices** unless you explicitly set the flag `returns_data=True`. Do let me know if that fixes the problem!

Robert

**Comment by hnicks13** [comment]
@robertmartin8 many thanks for your response. I apologise for missing the note about the returns in the guide, working fine now.

**Comment by robertmartin8** [comment]
@hnicks13 Awesome, I'm glad it's working!
