### ISSUE TITLE
Could not install on Windows

### ISSUE THREAD

**Issue by Conorcasey1** [robertmartin8/PyPortfolioOpt#138]
I ran "pip install pyportfoioopt" on my command lone and get an error when building a wheel, 

"Error: Could not build wheels for cvxpy which use PEP 517 and cannot be installed directly" 

I have attached a txt file with the full terminal output displayed for more info, this was not an issue with my previous computer and I've looked online with no success so any help would be appreciated. 

[Error Message.txt](https://github.com/robertmartin8/PyPortfolioOpt/files/4742067/Error.Message.txt)

**Comment by robertmartin8** [comment]
Hi @Conorcasey1,

Have you downloaded Visual Studio? PyPortfolioOpt has special installation instructions for windows, described [here](https://pyportfolioopt.readthedocs.io/en/latest/#installation)

Best,
Robert

**Comment by Conorcasey1** [comment]
Hi Robert, that worked thanks very much for that, really appreciate it

**Comment by robertmartin8** [comment]
Great! Glad it's working
