### ISSUE TITLE
failed to import pypfopt: DLL load failed

### ISSUE THREAD

**Issue by nikitazhhy** [robertmartin8/PyPortfolioOpt#142]
Hi, 

  I installed PyPortfolioOpt sucessfully on my Anaconda environment, but failed to import this lib.

  C ++ 2015-2019 already installed, visual studio 2019 already installed.

  Could u pls help check why it still can't work? Thank you so much !

**Comment by robertmartin8** [comment]
Hi @nikitazhhy,

Are you on windows? What version of python are you running? 

Can you open a python shell in your terminal and try `import pandas, numpy` followed by `import pypfopt; print(pypfopt.__version__)`.

Robert

**Comment by nikitazhhy** [comment]
> Hi @nikitazhhy,
> 
> Are you on windows? What version of python are you running?
> 
> Can you open a python shell in your terminal and try `import pandas, numpy` followed by `import pypfopt; print(pypfopt.__version__)`.
> 
> Robert

Hi, Robert,

I'm using python 3.7,

**Comment by nikitazhhy** [comment]
> Hi @nikitazhhy,
> 
> Are you on windows? What version of python are you running?
> 
> Can you open a python shell in your terminal and try `import pandas, numpy` followed by `import pypfopt; print(pypfopt.__version__)`.
> 
> Robert

Hi, Robert,

I'm using python 3.7 on windows 10. I just reinstalled Ananconda and pypfopt finally works  !
So weird, but thanks god it works now.

Thanks !
