### ISSUE TITLE
The weight to be assigned to the risk free asset

### ISSUE THREAD

**Issue by haimsitt** [robertmartin8/PyPortfolioOpt#143]
When i use the max_sharpe function it returns the optimal weight for every asset in my dataframe.

Is there a way to find out the optimal weights when investing in the risk free asset and investing in the market?

**Comment by robertmartin8** [comment]
There isn't a builtin way to do that, but you should be able to create a risk free asset and re-run the optimisation

**Comment by haimsitt** [comment]
Thanks for the quick response. 
How would you define a risk free asset in pandas?

**Comment by robertmartin8** [comment]
You could create a column with constant returns

**Comment by haimsitt** [comment]
If the time series has a constant daily return than the sharpe ratio is infinite.

**Comment by robertmartin8** [comment]
Do you mean conceptually, or this is the result of a numerical attempt?

An asset with constant returns is the definition of a risk-free asset.
Also, the Sharpe ratio is not technically infinite because the numerator
will also be zero.

**Comment by haimsitt** [comment]
You are correct. If an asset with a risk free asset has returns that are equal to the risk free returns than the Sharpe ratio is 0.
Say you have the weights for the portfolio maximizing the Sharpe ratio. If you use leverage you can achieve a higher Sharpe ratio if you also invest in the risk free asset (depending on your loan rate). 
Maybe you can add leverage to the max_sharpe function ?

**Comment by haimsitt** [comment]
My feature request is partially theoretical, so I will close it for now. Thanks :D
