### ISSUE TITLE
RuntimeError: Running cythonize failed!

### ISSUE THREAD

**Issue by chris-brown-nz** [robertmartin8/PyPortfolioOpt#144]
Just a minor thing, I had a bit of a problem with my install and thought it might be useful to others if it was mentioned in the [docs](https://pyportfolioopt.readthedocs.io/en/latest/index.html#installation) (which are excellent by the way).

Here is what I did. I'm using (Windows 10, Python 3.8.2). I had installed `cvxpy` first as per the link to the docs that I posted above.

---

Create and activate a new virtual environment:

```
>python -m venv ppo

>ppo\Scripts\activate.bat
```

Check installed Python packages:

```
>pip list
Package    Version
---------- -------
pip        19.2.3
setuptools 41.2.0
WARNING: You are using pip version 19.2.3, however version 20.1.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

Upgrade pip (see warning) then install PyPortfolioOpt:

```
>python -m pip install --upgrade pip

>pip install PyPortfolioOpt
```

At this point I got an error:

```
    RuntimeError: Running cythonize failed!
    Namespace(blas64=False, extraverbose=False, float32=False, gpu=False, int32=False, scs=False)
    Cythonizing sources
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
```

I just needed to install the Cython package first:

```
>pip install Cython

>pip install PyPortfolioOpt
```

**Comment by robertmartin8** [comment]
Thank you for this!

**Comment by hightechatri** [comment]
For me it did not work....so sad.....😥
