### ISSUE TITLE
Incorrect calculation in Ledoit-Wolf shrinkage intensity

### ISSUE THREAD

**Issue by szev77** [robertmartin8/PyPortfolioOpt#150]
https://github.com/robertmartin8/PyPortfolioOpt/blob/d220fddb418420f622d1af1999724110d6371eca/pypfopt/risk_models.py#L542

You write:
```
term1 = np.dot((X ** 3).T, X) / t
help_ = np.dot(X.T, X) / t
```

But it should be `Xm` instead of `X` (i.e. the demeaned variable).

**Comment by robertmartin8** [comment]
Good spot, will push a fix shortly!
