### ISSUE TITLE
Feature request: Upgrate cvxpy to 1.1.1

### ISSUE THREAD

**Issue by diegolovison** [robertmartin8/PyPortfolioOpt#153]
Upgrade cvxpy to 1.1.1

When upgrading, the method https://github.com/robertmartin8/PyPortfolioOpt/blob/master/pypfopt/discrete_allocation.py#L244 will fail

**Comment by robertmartin8** [comment]
I'm still trying to figure out what to do about that. They've removed the `ECOS_BB` default solver, so users would have to explicitly install a mixed-integer solver. Will think about it some more

**Comment by diegolovison** [comment]
No problem. I installed http://cvxopt.org/ and run the code. It is not breaking but the method is returning wrong values.
Once you have an idea, if you wish, I can run the tests that I have in my project and provide some feedback.

Thanks!

**Comment by robertmartin8** [comment]
When you say incorrect, do you mean that the resulting discrete allocations
aren't optimal? Or do they just not make sense

**Comment by diegolovison** [comment]
They don't make sense.

**Comment by robertmartin8** [comment]
Fixed!
