### ISSUE TITLE
Adding Deep Neural Networks and/or Probabilistic Modelling

### ISSUE THREAD

**Issue by AHappyDeskPlant** [robertmartin8/PyPortfolioOpt#154]
Hi, 

I am unsure whether this is possible for your framework (as I have not fully read through all your documentation yet) but I was wondering, is it possible to add a Deep Neural Network or a probabilistic model, i.e. GMM, to the portfolio optimisation procedure. For instance, I would like to be able to apply a DNN to the calculation of the covariance matrix to improve the estimation and hence, potentially improve for example, the GMVP. Sorry if I have completely misunderstood PyPortfolioOpt but the above is what I looking into for my masters thesis. 

Thanks for creating an awesome package for python

**Comment by robertmartin8** [comment]
PyPortfolioOpt is completely modular, meaning that you can input whatever estimate of the covariance matrix you like, be that from a deep learning model, or literally a hard-coded covariance matrix.
