### ISSUE TITLE
Plz add your CVaR feature back in

### ISSUE THREAD

**Issue by franceslius** [robertmartin8/PyPortfolioOpt#155]
conditional Value-at-Risk calculaiton had existed in negative_cvar imported from pypfopt.objective_functions until version 0.5.3, why u del it while u add other functions in?

**Comment by PyDataBlog** [comment]
+1 for the request as well. I badly need it in my current project.

**Comment by robertmartin8** [comment]
Hi guys, thanks for the feedback. CVaR is something I want to add, but it's
actually quite hard to do it properly.

The previous implementation was deeply flawed.

**Comment by farbodbahari** [comment]
Here is a function I have written to compute VaR and CVaR. I don't know how much it could help you to add CVaR back to the package, but I thought it would worth sharing.
Thanks!

def VaR_CVaR(data_series,
         significance_level):
    """Return VaR and CVaR and Tail Loss respectivley at the specifeid significance_level 
    1. VaR and CVaR Based on Normal_Dist and sample mean and std 
    2. VaR and CVaR Based on T Distribution
    3. VaR and CVaR Based on data driven approach - observed percentiles in the data at the significance level 
    4. VaR and CVaR Based on Generalized Extreme Value (GEV) distribution
    
    CVaR = (1/significance_level) * tail_loss
    """
    import scipy.stats
    import numpy as np
    mean=np.mean(data_series)
    std= np.std(data_series)
    #### Normal Dist VaR CVaR
    VaR_Normal_Dist=scipy.stats.norm.ppf(
        significance_level,
        loc = mean,
        scale = std)
    return_in_tail_based_on_VaR_Normal_Dist=data_series[data_series<VaR_Normal_Dist]
    
    tail_loss_Normal_dist = scipy.stats.norm.expect(lambda x: x,
                            loc = mean,
                            scale = std,
                            ub = VaR_Normal_Dist)
    CVaR_Normal = (1/significance_level) * tail_loss_Normal_dist
    
    
    #### T Dist Var CVaR
    t_dist_params = scipy.stats.t.fit(data_series)
    
    VaR_t_dist = scipy.stats.t.ppf(significance_level,*t_dist_params)
    tail_loss_t= scipy.stats.t.expect( lambda y: y, args = (t_dist_params[0],),
                                      loc = t_dist_params[1],
                                      scale = t_dist_params[2],
                                      ub = VaR_t_dist)
    
    CVaR_T = (1/significance_level) * tail_loss_t
    
    
    ### Data Driven VaR CVaR
    VaR_Quantile = np.quantile(data_series,significance_level)
    return_in_tail_based_on_VaR_Quantile=data_series[data_series<VaR_Quantile]
    CVaR_Quantile=np.mean(return_in_tail_based_on_VaR_Quantile)    
    
    
    #### VaR and CVaR GEV 
    genextreme_params= scipy.stats.genextreme.fit(-1*data_series)
    VaR_GEV = (scipy.stats.genextreme.ppf((1-significance_level), *genextreme_params))
    
    tail_loss_GEV = scipy.stats. genextreme.expect(lambda x: x, 
           args=(genextreme_params[0],),
                                                   loc = genextreme_params[1], 
                                              scale = genextreme_params[2],
                                              lb = VaR_GEV)
    CVaR_GEV = ((1/(significance_level)) * tail_loss_GEV)
    
    
    return ({"VaR_Normal_Dist":VaR_Normal_Dist,
             "VaR_GEV":VaR_GEV*-1,
             "VaR_t_dist":VaR_t_dist,
             "VaR_Quantile":VaR_Quantile,
             
            "CVaR_Normal":CVaR_Normal,
            "CVaR_GEV":CVaR_GEV*-1,
             "CVaR_T":CVaR_T,
             "CVaR_Quantile":CVaR_Quantile
            })

**Comment by Kaywa-ops** [comment]
Hi guys please try to add negative_cvar I need it to create portfolio. I can't do anything without it .

**Comment by robertmartin8** [comment]
Fixed in v1.4.0 😄

**Comment by rgno1** [comment]
Great Feature! hope you add back soon! Thanks in advance!
