### ISSUE TITLE
OptimizationError raised in new version ef.max_sharpe

### ISSUE THREAD

**Issue by franceslius** [robertmartin8/PyPortfolioOpt#157]
It was okay and solved well while I apply ef.max_sharpe() by old version 0.5.3, but it raised OptimizationError by cvxpy_opt by the newest version. Though it beased on same data and implemented in same process.

**Comment by robertmartin8** [comment]
Hi @franceslius, 

Sorry to hear that it's not working for you. Could you share a bit more about the kind of constraints/objectives you are using? It is probably the case that there is a nonconvex objective.

Best,
Robert

**Comment by franceslius** [comment]
thanks for replying, indeed, this issue was raised because of a nonconvex objective.

However, there is another issue that ef.max_sharpe() solve a different weight based on the same data runing twice, which caused a huge different performance. How this happened?
