### ISSUE TITLE
Eigenvalues did not converge

### ISSUE THREAD

**Issue by mcbrain78** [robertmartin8/PyPortfolioOpt#160]
Hi,

I am trying to follow the Quick Example from the documentation on Read the docs. I have a data frame of daily returns indexed by date. However when I execute `S = risk_models.sample_cov(df)`

I get the following error:

```
numpy.linalg.linalg.LinAlgError: Eigenvalues did not converge
```

I am running numpy version 1.14.6

Thanks,
Markus

**Comment by robertmartin8** [comment]
Hi @mcbrain78,

Thanks for raising this issue. I've never seen the error before - could you maybe share a sample of the data or the code you are using? I'll have a go at troubleshooting.

Cheers,
Robert

**Comment by mcbrain78** [comment]
Hi Robert,

I think I've managed to track the first error down to incompatible packages, but now I get another error. I'm also using zipline and that puts quite some constraints on the environment. To run a proper test, I've created now a completely clean new virtual env with Python 3.8.3 and the packages list at the bottom of the reply.

I've imported a returns dataframe from a csv which looks like this:
         ADBE      ADSK       CRM  ...      QLYS        RP      WDAY
0   -0.015389 -0.015430 -0.014372  ... -0.007047 -0.014246 -0.011529
1    0.010066 -0.000275  0.005311  ...  0.035484  0.013986 -0.002103
2   -0.004983 -0.007426 -0.003703  ...  0.011776 -0.008736 -0.000383
3    0.005271  0.005819  0.005847  ... -0.027649 -0.006030 -0.005750
4    0.013634  0.010193  0.010967  ...  0.011400  0.007933  0.016965
..        ...       ...       ...  ...       ...       ...       ...
247  0.000840 -0.006237  0.000912  ... -0.049331 -0.003968  0.001700
248 -0.001175  0.003037 -0.007293  ...  0.028584  0.002213 -0.005454
249  0.000672  0.000807  0.013223  ... -0.008123  0.000442  0.004387
250  0.005525  0.014885  0.000363  ... -0.003879  0.032230  0.008978
251 -0.009837 -0.021225 -0.005979  ...  0.002596 -0.041916 -0.016715

I then ran the following code

mu = pypfopt.expected_returns.mean_historical_return(df2)
sample_cov = pypfopt.risk_models.sample_cov(df2, returns_data=True)
ef = pypfopt.efficient_frontier.EfficientFrontier(mu, sample_cov)
weights = ef.max_sharpe()

And got this result:
ERROR in LDL_factor: Error in KKT matrix LDL factorization when computing the nonzero elements. The problem seems to be non-convex
ERROR in osqp_setup: KKT matrix factorization.
The problem seems to be non-convex.
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\Markus\anaconda3\envs\pypfopt_test\lib\site-packages\pypfopt\efficient_frontier.py", line 212, in max_sharpe
    self._solve_cvxpy_opt_problem()
  File "C:\Users\Markus\anaconda3\envs\pypfopt_test\lib\site-packages\pypfopt\base_optimizer.py", line 217, in _solve_cvxpy_opt_problem
    opt.solve()
  File "C:\Users\Markus\anaconda3\envs\pypfopt_test\lib\site-packages\cvxpy\problems\problem.py", line 290, in solve
    return solve_func(self, *args, **kwargs)
  File "C:\Users\Markus\anaconda3\envs\pypfopt_test\lib\site-packages\cvxpy\problems\problem.py", line 571, in _solve
    solution = self._solving_chain.solve_via_data(
  File "C:\Users\Markus\anaconda3\envs\pypfopt_test\lib\site-packages\cvxpy\reductions\solvers\solving_chain.py", line 195, in solve_via_data
    return self.solver.solve_via_data(data, warm_start, verbose,
  File "C:\Users\Markus\anaconda3\envs\pypfopt_test\lib\site-packages\cvxpy\reductions\solvers\qp_solvers\osqp_qpif.py", line 113, in solve_via_data
    solver.setup(P, q, A, lA, uA, verbose=verbose, **solver_opts)
  File "C:\Users\Markus\anaconda3\envs\pypfopt_test\lib\site-packages\osqp\interface.py", line 32, in setup
    self._model.setup(*unpacked_data, **settings)
ValueError: Workspace allocation error!

Package         Version
--------------- -------------------
certifi         2020.6.20
cvxpy           1.0.31
cycler          0.10.0
dill            0.3.2
ecos            2.0.7.post1
future          0.18.2
kiwisolver      1.2.0
matplotlib      3.3.0
multiprocess    0.70.10
numpy           1.19.1
osqp            0.6.1
pandas          1.1.0
Pillow          7.2.0
pip             20.1.1
pyparsing       2.4.7
pyportfolioopt  1.2.4
python-dateutil 2.8.1
pytz            2020.1
scipy           1.5.2
scs             2.1.2
setuptools      49.2.0.post20200714
six             1.15.0
wheel           0.34.2
wincertstore    0.2

**Comment by yves-pires** [comment]
I was having a very similar error, and I eventually found out that 2 rows of my huge DataFrame had the assets prices values equal to 0, which was a mistake. Erasing those rows did the trick for me.

**Comment by mcbrain78** [comment]
Thanks, that helped! So I could narrow down the bug:

When I work with a "returns" data frame like this:
df2 = df.pct_change()
mu = pypfopt.expected_returns.mean_historical_return(df2)
sample_cov = pypfopt.risk_models.sample_cov(df2, returns_data=True)
ef = pypfopt.efficient_frontier.EfficientFrontier(mu, sample_cov)
weights = ef.max_sharpe()

I get the above error. Dropping all 0 values removes the problem but leaves only ~1/5 of rows and the weights are obviously off.

When I use a data frame with prices data instead, then I don't have the 0 values and therefor no error.

**Comment by robertmartin8** [comment]
Glad to hear everything is resolved! Don't hesitate to reopen this issue if you are still having problems.

Cheers,
Robert

**Comment by SoundsSerious** [comment]
Also having this error, quite odd that 0 return data should cause such an issue as that is completely feasible.

**Comment by robertmartin8** [comment]
@SoundsSerious I believe the problem here 0s in the `prices` dataframe (and thus infinities in the `returns` dataframe).

In any case, I think the cause of #297 is more likely to be dataframe formatting

**Comment by SoundsSerious** [comment]
@robertmartin8 Yea i think it has alot to do with how the dataframe is formatted. I found some of my models had nans for the most recent values (late to update the data) and that was also throwing it off. The performance data I'm using is formatted as percent return so its a little to closer to zero in general. Padding the cumulative performance with 1 has helped, its on me to find the trailing NaN's
