### ISSUE TITLE
`gamma` argument in `EfficientFrontier` has no effect

### ISSUE THREAD

**Issue by openerror** [robertmartin8/PyPortfolioOpt#161]
**Describe the bug**
When I ran `EfficientFrontier` on the stock prices this package uses for its unit tests, different `gamma` values led to the same weights. I have tried both `min_volatility` and `max_quadratic_utility` objectives/methods. `gamma` enters into the convex optimisation objective itself; it's inconceivable that 100 and 0 would lead to the same weights. 

**Expected behavior**
Should obtain different portfolio weights for drastically different `gamma` values. I am aware that there's a `L2_reg` objective function in the package; but if `gamma` is exposed in the constructor of `EfficientFrontier`, then I don't think users should need to manually add the L2 regularisation objective for `gamma` != 0.0

**Screenshots**
![image](https://user-images.githubusercontent.com/11012723/88746160-6fccd200-d17e-11ea-9581-d9cd9d6919c2.png)

**Operating system and python version:**
e.g MacOS 10.14.6, python 3.8.3, pyportfolioopt 1.2.3, cvxpy 1.0.31

I appreciate this package very much; looking forward to improving it, one way or another!

**Comment by robertmartin8** [comment]
Hi @openerror,

Really appreciate the detailed report! This is indeed a bug, I forgot to remove `gamma` from the constructor when I changed the API – it does not connect to anything and I will remove it in the next release.

Cheers!
Robert

**Comment by openerror** [comment]
Thanks for the prompt response, Robert. In that case, how would one add L2 regularisation as an objective? You included the following lines in the documentation, but how does one actually define & adjust `gamma`'s value? (Tried running the lines below, same results as `gamma` = 0)

```
ef = EfficientFrontier(expected_returns, cov_matrix)  # setup
ef.add_objective(objective_functions.L2_reg)  # add a secondary objective
ef.min_volatility()  # find the portfolio that minimises volatility and L2_reg
```
Would gladly contribute the relevant edits to the docs, once it's clear how to do it

**Comment by robertmartin8** [comment]
@openerror 

Really sorry for the slow reply – I was quite busy with internship work this summer. I'm glad you figured it out. I'll have a go at making the docs a bit more clear on this.

Cheers,
Robert

**Comment by openerror** [comment]
No worries Robert, I was busy with my internship, too. Looking forward to a better and more complete package!
