### ISSUE TITLE
Ledoit-Wolf Shrinkage applied to prices rather than sample_cov

### ISSUE THREAD

**Issue by cstampar** [robertmartin8/PyPortfolioOpt#163]
Hi there! So this isn't strictly a bug, because the program is still working, but I believe a variable is being misused and wanted some further insight, and wasn't sure it fell in the other categories, sorry if it is mis-flagged. 

In your cookbook[ here](https://github.com/robertmartin8/PyPortfolioOpt/blob/master/cookbook/2-Mean-Variance-Optimisation.ipynb) for mean-variance optimization you:

#create the sample_cov
sample_cov = risk_models.sample_cov(prices, frequency=252)

#apply shrinkage function 
S = risk_models.CovarianceShrinkage(prices).ledoit_wolf()

But here you provides 'prices' instead of 'sample_cov'.....the rest of the code works, it will apply this function to the prices and give me the discrete allocations. But from all my reading it seems it should be applied to the 'sample_cov' directly. I tried this and it does work. It results in slightly different Discrete Allocations, however when you print the portfolio performance, on a max sharpe for example, it results in an annual volatility of 768% rather than 24.6% when calculating on 'prices'.

Just wondering if I am missing something here, or if there is a specific reason why it would be better to shrink the prices rather than the sample_cov. 

Thank you so much for all your work!! :)

**Comment by cstampar** [comment]
Could me an amateur mistake here on my part, but is 'risk_models.CovarianceShrinkage()' recalculating the entire cov_mat AND shrinking it, or doing just the shrinkage? I think that might explain it.

**Comment by robertmartin8** [comment]
Hi @cstampar,

Thanks for reaching out with the question! This is probably a result of me poorly explaining the API. 

The goal of this method is to compute the shrunk covariance matrix based on a price (or return) series that you input, then shrink it. It is not meant to accept a covariance matrix, then shrink it. The reason why it has been designed this way is that the shrinkage target requires information beyond just the covariance matrix. 

Hope this helps!
Robert

**Comment by cstampar** [comment]
Thank you so much!
