### ISSUE TITLE
Incorrect computation for compounded returns

### ISSUE THREAD

**Issue by bhutraaditya** [robertmartin8/PyPortfolioOpt#166]
https://github.com/robertmartin8/PyPortfolioOpt/blob/386d72da52d1ddaeb9eabb49f04e7386078ff7ea/pypfopt/expected_returns.py#L130-L133

**Example:**
`returns` contains just two rows for an asset with values `0.1` and `-0.1`. 
Let us assume `frequency` to be 1 for simplicity.

Using the existing logic, the expected compounded returns would be `(1 + returns.mean()) ** frequency - 1`   = `0`

In reality, the compounded return would be `(1+0.1)*(1-0.1) ** 0.5 - 1`  ! = `0`

**Comment by robertmartin8** [comment]
Hi @bhutraaditya,

Thanks for pointing this out! I agree with you that this is technically incorrect, as conceptually we should be using the geometric mean (aka CAGR). However, many portfolio optimisation implementations that I've seen do not do this. If you can suggest an implementation that would be robust to different frequencies, I'd consider it!

Cheers,
Robert

**Comment by bhutraaditya** [comment]
@robertmartin8  How about something like this:

`(1 + returns).prod() ** (frequency/returns.count()) - 1`

Although, there could be inefficiencies if there are long periods of missing return data in the series.
