### ISSUE TITLE
Correlation calculation appears broken

### ISSUE THREAD

**Issue by Wilm0r** [robertmartin8/PyPortfolioOpt#168]
**Describe the bug**
Using the exact example code from `cookbook/1-RiskReturnModels.ipynb` does not result in the expected plots. For example, there's no diagonal line showing stocks 100% correlating with themselves. (Which makes it difficult to trust the other calculations as well..)

**Expected behavior**
I'd expect the example code + data to result in the exact same plots shown in the examples, and the scale on the right to cover the full spectrum (or at least up to 100%).

**Operating system and python version:**
Debian testing, 3.8.5. All libs freshly installed in a virtualenv.

![nopes](https://user-images.githubusercontent.com/6828117/89719961-8caaa600-d9c5-11ea-9c18-c2855d71d71c.png)

**Comment by robertmartin8** [comment]
Hi,

This function has been updated to plot covariance matrices by default (but
you can plot correlation matrices instead by passing `correlation=True`)

Cheers,
Robert

**Comment by Wilm0r** [comment]
Thank you for the promt response and apologies for missing that detail. I'm still trying to wrap my head around a lot of this matter. It looks like the exact name of the flag is `plot_correlation`, now I'm getting the same results indeed. :)

That does seem like a documentation bug then, with code and screenshots no longer matching? I'll send a PR.
