### ISSUE TITLE
How do I calculate an HRP portfolio performance?

### ISSUE THREAD

**Issue by ManuelLopezMe** [robertmartin8/PyPortfolioOpt#170]
After using the HRP .optimize() method, I tried to calculate its performance but I don't know how to use the .portfolio_performance() function. I tried the following method
<img width="780" alt="hrppo" src="https://user-images.githubusercontent.com/53957443/89823686-ea530580-db1f-11ea-87ca-ce10896ee405.PNG">

**Comment by robertmartin8** [comment]
Hi @ManuelLopezMe 

Hope this helps!

```python
hrp_model = HRPOpt(returns, cov_matrix)
hrp_model.optimize()
hrp_model.portfolio_performance(verbose=True)
```
