### ISSUE TITLE
online portfolio selection algorithms

### ISSUE THREAD

**Issue by andrewcztrack** [robertmartin8/PyPortfolioOpt#171]
The modern online portfolio selection algorithms

**Comment by robertmartin8** [comment]
Hi @andrewcztrack,

Thanks for the feature request! OLPS is something that I wanted to include in the early days, but I have since become a lot more suspicious of their practicality.

**Comment by andrewcztrack** [comment]
wow thats interesting :)

**Comment by robertmartin8** [comment]
I am closing this, as OLPS is not something I envision adding in future. I harbour strong doubts regarding their utility, and there are many other large featuresets that would take priority (for example: CVaR, higher moments, monte carlo, factor modelling). However, in future I may be interested in implementing multi-period optimisation (not the same as OLPS) – see [this paper](https://stanford.edu/~boyd/papers/pdf/cvx_portfolio.pdf) by Boyd et al.

If anyone desperately needs OLPS, I would suggest [mlfinlab](https://github.com/hudson-and-thames/mlfinlab).

**Comment by sdafsdfw123wq** [comment]
@robertmartin8 
Any update on the multi-period optimisation?
