### ISSUE TITLE
How to Debug Constraints in the cvxpy version?

### ISSUE THREAD

**Issue by pmn4** [robertmartin8/PyPortfolioOpt#173]
I have a portfolio that is failing to find a solution

My security constraints are (0.0, 1.0), and my Sector constraints are, for the sake of argument, (0.0, 0.1). Most sectors only have one security, but one has two. I would expect the solver to allocate 10% to each security, however, I get the error `Please check your objectives/constraints or use a different solver.`

My question is not "why is this happening?", but rather, "how can I debug this?"

I tried to put a bunch of print statements in my constraint methods, but cvxpy is doing some magic that I cannot quite follow! In the numpy days, I would see hundreds/thousands of console statement showing each attempt the solver tried. Any idea how I can see each iteration of the solver now?

thanks!

**Comment by robertmartin8** [comment]
Hi @pmn4,

That's a good question – it's possible that the `verbose` parameter in the solver might be what you're after? The output would look something like [this](https://www.cvxpy.org/tutorial/advanced/index.html#viewing-solver-output). 

Cheers,
Robert

**Comment by pmn4** [comment]
right, the verbose output looks like this, which is a little over my head!

```
It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  +1.287e-17  -1.427e+01  +5e+01  5e-01  5e-01  1e+00  1e+00    ---    ---    1  1  - |  -  - 
 1  -1.957e-02  -5.004e-01  +5e+00  4e-02  4e-02  6e-01  2e-01  0.9855  1e-01   1  1  1 |  0  0
 2  +1.660e-02  -8.009e-02  +1e+00  5e-03  6e-03  7e-02  4e-02  0.8261  1e-02   2  1  1 |  0  0
 3  +2.230e-02  +8.144e-03  +2e-01  8e-04  8e-04  1e-02  6e-03  0.8756  3e-02   1  1  1 |  0  0
 4  +2.301e-02  +2.051e-02  +5e-02  9e-04  3e-04  1e-02  2e-03  0.7942  1e-01   1  1  1 |  0  0
 5  +2.643e-02  +1.205e-01  +8e-03  2e-03  3e-04  1e-01  3e-04  0.8720  2e-02   1  1  1 |  0  0
 6  +2.834e-01  +1.041e+01  +9e-05  3e-03  2e-04  1e+01  3e-06  0.9888  1e-04   1  1  1 |  0  0
 7  +1.941e+01  +7.611e+02  +1e-06  3e-03  2e-04  7e+02  4e-08  0.9865  1e-04   2  1  1 |  0  0
 8  +8.158e+02  +2.797e+04  +3e-08  3e-03  2e-04  3e+04  1e-09  0.9735  7e-04   2  1  1 |  0  0
 9  +4.786e+04  +1.148e+06  +7e-10  2e-03  2e-04  1e+06  2e-11  0.9890  1e-02   1  1  1 |  0  0
```
also, am I to understand that cvxpy can solve the problem accurately in only ten steps?!

_(I understand this is more of a question for the cvxpy crew, but had hoped you'd struggled through it yourself. I will certainly ask the question there too and let you know if I hear anything back)_

**Comment by robertmartin8** [comment]
Could you try this?

```python
ef = EfficientFrontier(mu, S)
ef.min_volatility() # fails

opt = cp.Problem(cp.Minimize(ef._objective), ef._constraints)
if self.solver is not None:
    opt.solve(solver=ef.solver, verbose=True)
else:
    opt.solve()
```

This explicitly solves the problem using cvxpy, which means that you should get the full trace explaining why the problem cannot be solved with the convex optimiser. If this trace is useful, I can make it so that it gets returned to the user when there are optimisation errors
