### ISSUE TITLE
Feature request: CAPM return with non-scalar risk-free rate

### ISSUE THREAD

**Issue by bhutraaditya** [robertmartin8/PyPortfolioOpt#175]
**Is your feature request related to a problem? Please describe.**
https://github.com/robertmartin8/PyPortfolioOpt/blob/386d72da52d1ddaeb9eabb49f04e7386078ff7ea/pypfopt/expected_returns.py#L278

Currently, the CAPM return computation assumes a constant risk-free rate (default=0.02). However, if one intends to carry out a long-term analysis (5+ years), this may not be a good assumption. Merely replacing the `risk_free_rate` with the mean of its timeseries over the period is mathematically incorrect too.

Original formula for beta:
` cov( [Mkt - Rf], [Stock-Rf] ) / variance( [Mkt-Rf] )`

Current implementation:
` cov( [Mkt], [Stock] ) / variance( [Mkt] )`

The above are equivalent only if `Rf` is constant.

**Describe the solution you'd like**
Allow `risk_free_rate` parameter to be specified as a time-series and use the "original formula" above

@robertmartin8 Let me know what you think and I can take care of the implementation.

**Comment by robertmartin8** [comment]
Hi @bhutraaditya 

Appreciate the suggestion! There are a couple of reasons why I want to keep it the way it is:

1. Almost all implementations of the CAPM (particularly in WACC calculations) use a constant risk-free rate.
2. You are right that technically we want to input the future risk-free rate, but similarly, we need to input the future betas and future market return. 
3. I don't think the vast majority of users will have a view on the term structure of interest rates.

So I think that while it would be "more correct" to allow for a time series of risk-free rates, it is not conventional and it is a case of "false precision". 

However, PyPortfolioOpt has been designed with modularity in mind, so advanced users who do have a view on the term structure of interest rates are free to incorporate that into their own model of the expected returns, then use that as input to the optimiser.

Hope that makes sense!
Robert
