### ISSUE TITLE
Using different (cvxpy) solvers

### ISSUE THREAD

**Issue by oldrichsmejkal** [robertmartin8/PyPortfolioOpt#178]
I would like to try different (cvxpy) optimizers, because default one does not converge for some of my problems.
I see there is 'solver' parameter in EfficientFrontier documentation as an input, but I don't see it in a source code at all.
Am I missing something? If so would you have please some example how to use different solvers?

Thanks

**Comment by robertmartin8** [comment]
Hi @oldrichsmejkal,

It is currently a "hidden API". You can access it like:

```python
ef = EfficientFrontier(mu, S)
ef.solver = "SCS"
ef.max_sharpe()
```

There is currently a [pull request](https://github.com/robertmartin8/PyPortfolioOpt/pull/162) making this a proper API, which I will merge next week.

Cheers,
Robert
