### ISSUE TITLE
Could not install on MacOs Anaconda 

### ISSUE THREAD

**Issue by floleor** [robertmartin8/PyPortfolioOpt#181]
**Operating system, environment, python version**
MacOs, anaconda, python3.8

**What you tried**
pip install pyportfolioopt

**Error message**
ERROR: Could not build wheels for cvxpy which use PEP 517 and cannot be installed directly

Hi There,

when I try to install pyportfolioopt using my terminal I always get the error message above. I tried to install cvxpy independently, however I get exactly the same message. Can you advise me on how to fix this? Would really love to use your tool!

Best, Florian

**Comment by abdelilahDR** [comment]
I got exactly the same error. were you able to fix it?

**Comment by floleor** [comment]
Unfortunately no, not yet.

**Comment by robertmartin8** [comment]
@floleor 

Hi Florian,

Appreciate the detailed stack trace and apologies for the delayed response. Could you try to `pip install ecos` and `pip install scs` before `pip install cvxpy`? I'd like to narrow down whether this is a problem in PyPortfolioOpt, or cvxpy.

If any of these fail and you see some errors relating to `gcc`, it might mean that C++ is not properly installed, so you may need to `conda install gcc libgcc`. Let me know if that works – I am a bit unfamiliar with anaconda (I use homebrew), so I seek your patience as there may be a bit of back-and-forth.

Cheers,
Robert

**Comment by floleor** [comment]
Hi Robert,

First off, I really appreciate your help!
Apparently it was really an issue with C++ and this is how I fixed it:

First I installed gcc using brew:
```brew install gcc```

Then I was able to install all dependencies:
```
pip install ecos
pip intall scs
pip install cvxpy
```

Finally, I could install PyPortfolioOpt!
```pip install pyportfolioopt```

Thanks again for your help Robert! Keep up the great work :)

Flo
