### ISSUE TITLE
Optimization for Min Volatility is returning an error

### ISSUE THREAD

**Issue by sarvotham** [robertmartin8/PyPortfolioOpt#182]
When i request minimum volatility optimization with the below code:

```
ef = EfficientFrontier(mu, S)
pypfopt_weights = ef.min_volatility()
```

I get the following errors:
```
NoneType: None
Traceback (most recent call last):

  File "<ipython-input-26-06f7f6515a7b>", line 1, in <module>
    ef.min_volatility()

  File "C:\ProgramData\Anaconda3\lib\site-packages\pyportfolioopt-1.2.3-py3.8.egg\pypfopt\efficient_frontier.py", line 152, in min_volatility
    return self._solve_cvxpy_opt_problem()

  File "C:\ProgramData\Anaconda3\lib\site-packages\pyportfolioopt-1.2.3-py3.8.egg\pypfopt\base_optimizer.py", line 221, in _solve_cvxpy_opt_problem
    raise exceptions.OptimizationError

OptimizationError: Please check your objectives/constraints or use a different solver.
```

I'm able to perform the same for max_sharpe and max_sharpe by exponentially weighted returns without any issues. What is the cause of the issue here?

**Comment by robertmartin8** [comment]
HI @sarvotham,

Could you provide more information about the specific optimisation problem you are trying to solve? What kind of data are you using?

Incidentally, I remember you had a couple of installation issues – how did you resolve those?

Best,
Robert

**Comment by sarvotham** [comment]
I wasn't able to solve the installation issues. Likely due to the cvxpy conditions and in Python 3.8 it is not able to build a wheel for the cvxpy v1.0. So, I cloned the git repository, added it to my path and then imported it. I'm able to run the optimization functions by importing pypfopt.

I have a set of tickers with daily ohlc data. I was trying to compare the portfolio performance when optimizing with max_sharpe, max_sharpe with exp. weighted returns, and min_volatility. Using the code below:

```
mu = expected_returns.mean_historical_return(AdjClose_price)
S = risk_models.sample_cov(AdjClose_price)
ef = EfficientFrontier(mu, S)
min_vol_p = pd.DataFrame(ef.min_volatility(), index=[0])
```

While i can get the first 2 to run without any issues, with min_volatility i get the error message shown above. Let me know if I'm doing anything wrong here.

**Comment by robertmartin8** [comment]
@sarvotham 

Gotcha, sorry to hear about the persistent issues. Another user had a similar issue and managed to [solve it](https://github.com/robertmartin8/PyPortfolioOpt/issues/184). I wonder if that would work for you? In any case, over the next few days I will be pushing a version that supports cvxpy 1.1 and python 3.8.

As for your `min_volatility` issue, I'm afraid I can't really help without seeing your covariance matrix. I've never seen an issue where `max_sharpe` works but `min_volatility` doesn't. Here are a few things to try:

- Visually check your covariance matrix to make sure there are no issues (e.g asymmetry, NaNs)
- Run EfficientFrontier with no `mu`, e.g `EfficientFrontier(None, S)`. 
- Try it again with fewer stocks.
- Recreate the optimisation problem in cvxpy to isolate whether it is a `pypfopt` problem. Code below:

```python
w = cp.Variable(n)
risk = cp.quad_form(w, S.values)
constraints = [cp.sum(w) == 1, w >= 0]
opt = cp.Problem(cp.Minimize(risk), constraints)
opt.solve()
w.value
```

In the next PR, I will be including a change that makes these kind of errors a lot more transparent, i.e providing the full cvxpy stack trace. I really appreciate your patience working through these issues, PyPortfolioOpt normally "just works" for people :( 

Let me know how that goes!

**Comment by sarvotham** [comment]
@robertmartin8 

Thank you for sharing the above guide. My covariance matrix looks clean and there are no issues there with the data. I tried running with replacing the `mu` with `None` and I don't see the error being flagged for `min_volatility` any longer.

I also recreated the optimization with cvxpy with the code you shared above and am not seeing any errors there. Hopefully this helps. Let me know if you want me to run any more tests.

**Comment by robertmartin8** [comment]
@sarvotham 

Thanks for getting back to me! So am I correct in saying that this doesn't work:

```python
ef = EfficientFrontier(mu, S)
ef.min_volatility()
```

but this does:

```python
ef = EfficientFrontier(None, S)
ef.min_volatility()
```

If so, that's a pretty strange error

**Comment by sarvotham** [comment]
@robertmartin8 

Yes, that's correct. I get the optimization error with the first one and no error with the second one.

**Comment by robertmartin8** [comment]
What if you try:

```python
ef = EfficientFrontier(mu, S)
ef.expected_returns = None
ef.min_volatility()
```

and

```python
ef = EfficientFrontier(None, S)
ef.expected_returns = mu.values  # assuming mu is a pd.series
ef.min_volatility()
```

This error doesn't make much sense to me, because `min_volatility` makes no attempt to use the field `self.expected_returns`.

**Comment by robertmartin8** [comment]
Please reopen this if required
