### ISSUE TITLE
how can i add the another point to the plot_efficient_frontier ? 

### ISSUE THREAD

**Issue by silent0506** [robertmartin8/PyPortfolioOpt#185]
Hello, I am very grateful for your package.

I have a question.

how can add the another(min volatility) point to the plot_efficient_frontier ? 

I want to add min volatility point to the ef line.

* my using code 
from pypfopt.plotting import plot_efficient_frontier
plot_efficient_frontier(CLA0_ms, points=100, show_assets=True)

**Comment by robertmartin8** [comment]
@silent0506 

Thanks for the question!

To plot an additional point:

```python
ax = plotting.plot_efficient_frontier(cla, showfig=False)
ax.scatter(0.15, 0.2)
```

Replace 0.15 and 0.20 with the volatility or returns respectively.

Hope this helps!
Robert

**Comment by silent0506** [comment]
Thank you^^
