### ISSUE TITLE
Returns based style analysis

### ISSUE THREAD

**Issue by sbauwow** [robertmartin8/PyPortfolioOpt#19]
Looking to implement a way to calculate Returns Based Styles with this library. Something similar to https://github.com/calebdoxsey/node-rbsa/blob/master/rbsa.js or https://github.com/badgerodon/rbsa.

**Comment by robertmartin8** [comment]
Hi, 

Have you got any other information on this method? Ideally an academic article or something - I haven't come across it before.

Best,
Robert

**Comment by sbauwow** [comment]
Hi Robert,

Here is a good primer on the topic:
[Part 1](http://www.styleadvisor.com/content/mathematics-returns-based-style-analysis-part-1)
[Part 2](http://www.styleadvisor.com/content/mathematics-returns-based-style-analysis-part-2)

Let me know what your thoughts, and I will search for more literature.

Best,

Steve

**Comment by robertmartin8** [comment]
@sbauwow alright I've had a quick look at the resources linked. The method does not seem mathematically complicated, and of course it wouldn't be too difficult (but not trivial either) to port the javascript implementation you've linked.

My issue is that it requires quite a significant re-architecture of the PyPortfolioOpt API, which currently focuses on portfolio optimisation provided with an asset universe and prices _only_. I intended for PyPortfolioOpt to be the last step in a fund-management workflow: having identified desirable assets, how should they be combined?

In the future I do want to expand this to include optimisation based on factor analysis (which seems to be essentially what RBSA is about), and more general constraints like that raised in #10, #13, #16, but this is not currently on the horizon. Thus, I am closing this but marking it as 'Revisit'. 

Please don't hesitate to reach out if you have any other comments or feedback.

Robert
