### ISSUE TITLE
error in exponential covariance

### ISSUE THREAD

**Issue by ali-amirahmadii** [robertmartin8/PyPortfolioOpt#192]
When i try to use exponential covariance with 
`S = risk_models.exp_cov(df)`

i get following error:
```

KeyError                                  Traceback (most recent call last)
<ipython-input-112-5a1dc4e7c598> in <module>
----> 1 S = risk_models.exp_cov(df)

~/vir_env/env/lib/python3.6/site-packages/pypfopt/risk_models.py in exp_cov(prices, returns_data, span, frequency, **kwargs)
    263         for j in range(i, N):
    264             S[i, j] = S[j, i] = _pair_exp_cov(
--> 265                 returns.iloc[:, i], returns.iloc[:, j], span
    266             )
    267     cov = pd.DataFrame(S * frequency, columns=assets, index=assets)

~/vir_env/env/lib/python3.6/site-packages/pypfopt/risk_models.py in _pair_exp_cov(X, Y, span)
    227     if span < 10:
    228         warnings.warn("it is recommended to use a higher span, e.g 30 days")
--> 229     return covariation.ewm(span=span).mean()[-1]
    230 
    231 

~/vir_env/env/lib/python3.6/site-packages/pandas/core/series.py in __getitem__(self, key)
    869         key = com.apply_if_callable(key, self)
    870         try:
--> 871             result = self.index.get_value(self, key)
    872 
    873             if not is_scalar(result):

~/vir_env/env/lib/python3.6/site-packages/pandas/core/indexes/base.py in get_value(self, series, key)
   4403         k = self._convert_scalar_indexer(k, kind="getitem")
   4404         try:
-> 4405             return self._engine.get_value(s, k, tz=getattr(series.dtype, "tz", None))
   4406         except KeyError as e1:
   4407             if len(self) > 0 and (self.holds_integer() or self.is_boolean()):

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_value()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_value()

pandas/_libs/index.pyx in pandas._libs.index.IndexEngine.get_loc()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.Int64HashTable.get_item()

pandas/_libs/hashtable_class_helper.pxi in pandas._libs.hashtable.Int64HashTable.get_item()

KeyError: -1
```

after checking error logs i found out in the last line of the _pair_exp_cov(X, Y, span=180) function:

`return covariation.ewm(span=span).mean()[-1]` 

was used, while return covariation.ewm(span=span).mean() is a pandas object and for access to last element of this pandas object you should use 
`return covariation.ewm(span=span).mean().iloc[-1]`
after change this line as i described exp_cove function worked correctly.

**Comment by robertmartin8** [comment]
Hi @ali-amirahmadii,

Thanks for reaching out! Can you let me know what version of python/pandas/pyportfolioopt you are using? `exp_cov` is currently [tested](https://github.com/robertmartin8/PyPortfolioOpt/blob/master/tests/test_risk_models.py#L113), and the latest test is [passing](https://travis-ci.org/robertmartin8/PyPortfolioOpt). 

Thanks!
Robert

**Comment by ali-amirahmadii** [comment]
Hi @robertmartin8 

python version:  3.6.9
pandas version: 1.0.1
pyportfolioopt version: 1.2.3

> Hi @ali-amirahmadii,
> 
> Thanks for reaching out! Can you let me know what version of python/pandas/pyportfolioopt you are using? `exp_cov` is currently [tested](https://github.com/robertmartin8/PyPortfolioOpt/blob/master/tests/test_risk_models.py#L113), and the latest test is [passing](https://travis-ci.org/robertmartin8/PyPortfolioOpt).
> 
> Thanks!
> Robert

**Comment by robertmartin8** [comment]
@ali-amirahmadii 

Interesting, thanks for letting me know – I will push a fix in the next update.
