### ISSUE TITLE
How do I backtest a portfolio's asset allocation?

### ISSUE THREAD

**Issue by aam1r** [robertmartin8/PyPortfolioOpt#193]
My apologies if this has been asked before.

I would like to use this to backtest a portfolio's asset allocation and compare it to an index.

Example:

```
Ticker,% of Allocation
AAPL,0.5
TSLA,0.25
MSFT,0.20
AMZN,0.05
```

Given this fixed asset allocation of the tickers above, how do I backtest this portfolio and compare it against an index?

The key thing to note here is that the allocation is fixed in terms of % of portfolio.

**Comment by robertmartin8** [comment]
Hi @aam1r,

Thanks for the question! Unfortunately, PyPortfolioOpt doesn't offer backtesting functionality – there are packages like Backtrader, Zipline, and Pyfolio that do a good job of this. However, for "quick backtests" I often just use pandas. e.g you make a new "portfolio" column that is the weighted sum of other columns:

```python
# Can use df.dot to avoid hard coding
df["portfolio"] = 0.5 * df["AAPL"] + ... + 0.05 * df["AMZN"]
```

Then you can compute whatever statistics are relevant, or plot them using `df[["portfolio", "index"]].plot()`.

Hope that helps!
Robert
