### ISSUE TITLE
Volatility disagrees with other online sources

### ISSUE THREAD

**Issue by talsisinay** [robertmartin8/PyPortfolioOpt#195]
Hey,

While I am not as close to the understand the theory behind this (great!) library - I found that the volatility and Shape ratio reported when using 'portfolio_performance' are somewhat different than what you would get when using any online volatility calculator (say on S&P500). 

Digging in, I think the underlying cause is that whenever you are using numpy.cov() - for example in sample_cov - you are using it a sample/biased (STDEV) instead of population based (STDEVP) - this can be fixed by passing ddof=0. I am aware that the name is "sample cov" so maybe this is done on purpose, but maybe not.

**Comment by robertmartin8** [comment]
Hi @talsisinay,

Thanks for reaching out! There are several reasons why the volatility might differ slightly:

- Lookback period
- Sample vs population (as you point out)
- Frequency
- Handling of missing data, weekends
- Adjusted close vs close
- Annualisation procedure

If the differences are large (e.g 10% vs 20%), please provide a sample and a link to the online calculator – I will investigate.

Cheers,
Robert

**Comment by talsisinay** [comment]
Thanks, the differences depend on the values, I think that even lower% is significant when it comes to volatility. You can use a simple 12 month returns from a stock:

0.84
1.52
-2.21
1.09
1.6
-1.2
0.84
0.81
1.66
0.34
2.75


STDEV=1.34169048
STDEVP=1.28457083

**Comment by robertmartin8** [comment]
@talsisinay 

I think it is conceptually better to use the sample standard deviation rather than the population standard deviation. After all, our estimate of volatility is based on a sample of the return distribution. But if it happens to be the case that most other resources are using the population std, I will happily consider making the change to PyPortfolioOpt.
