### ISSUE TITLE
Cookbook: Black-litterman posterior not always between the prior and the view

### ISSUE THREAD

**Issue by jameszhao00** [robertmartin8/PyPortfolioOpt#197]
The cookbook states that "Notice that the posterior is always between the prior and the views.". This seems to contradict the photo right above it
![image](https://user-images.githubusercontent.com/845753/94328971-12d67800-ff85-11ea-99e5-d431bb363615.png)

Cookbook - https://github.com/robertmartin8/PyPortfolioOpt/blob/master/cookbook/4-Black-Litterman-Allocation.ipynb

**Comment by robertmartin8** [comment]
@jameszhao00 

Good catch! I'm investigating it now – spotted a bug (#198) that _might_ explain it. I'm pretty sure the mathematics of Black-Litterman means that the posterior returns should be between the prior and the view, though it's possible that particular uncertainty matrices may cause it not to be always true.

**Comment by jameszhao00** [comment]
Is it possible for my views on other, correlated assets to influence the posterior so much so that it's no longer between the prior and the view? In your example I could say I'm confident AMZN's returns is -100 with a confidence of 1 and drag MSFT's posterior down.

**Comment by robertmartin8** [comment]
@jameszhao00, that's exactly what I believe to be happening. 

Jay Walter's classic paper [*The Black Litterman Model in Detail*](https://www.ssrn.com/abstract=1314585) – in my view, the definitive guide to all things Black-Litterman – discusses the limiting cases of 100% confidence (which gives the view) and 0% confidence (which gives the prior), which I misinterpreted when I wrote the docs.

I am changing the wording of the docs to make it more precise, will push it by tomorrow. Really appreciate the feedback! Don't hesitate to reach out if you spot any other issues, or have any questions :) 

Cheers,
Robert

**Comment by nathanramoscfa** [comment]
I have also been observing that I am finding instances of the posterior return not being between the prior or view estimate. I don't know why that's happening but I adjusted my posterior returns so that they _have_ to be between the prior and view.
