### ISSUE TITLE
 higher dimensional components when creating the Efficient Frontier 

### ISSUE THREAD

**Issue by farbodbahari** [robertmartin8/PyPortfolioOpt#205]
Would you please consider adding higher dimensional components for  creating the Efficient Frontier ?

Right now the package is mainly performing mean-variance optimization. In reality investors care about the skewness and kurtosis of the portfolio. There is an example on its implementation in Python on  towardsdatascience.com which I linked here below. It would be a great additional feature to add to this package.

Here is the link to the implementation in Python
https://towardsdatascience.com/building-a-higher-dimensional-efficient-frontier-in-python-ce66ca2eff7

Thank you!

**Comment by robertmartin8** [comment]
Thanks for the feature suggestion! This is currently discussed in #158. 

The article you share doesn't actually optimise for higher moments, it only plots them – still a useful resource though!
