### ISSUE TITLE
How to constraint sum of top weights to a value?

### ISSUE THREAD

**Issue by sven-borden** [robertmartin8/PyPortfolioOpt#210]
Dear all,
**What are you trying to do?**
I am trying to add a constraint where the sum of top N weights should be smaller or equal to a certain value. 
For example we want to have the top 2 weights in the solution to be lower or equal to 20% of the portfolio. 

Is this kind of contraints possible to do?

**Comment by phschiele** [comment]
Hi @sven-borden,

it is certainly possible to implement such a constraint.

CVXPY has implemented the [sum_largest()](https://www.cvxpy.org/_modules/cvxpy/atoms/sum_largest.html#sum_largest) function, which does exactly what you describe. You can see that this function is convex and increasing [here](https://www.cvxpy.org/tutorial/functions/index.html#scalar-functionsl).



Considering your example, a straightforward way to see that it is generally possible is to do this is to construct constraints such that the sum of the weights of _any_ two assets is less than 20%.
Let's further assume you have 3 assets in total. Your constraints would look like this:
```
1 1 0 * x <= 0.2
1 0 1 * x <= 0.2
0 1 1 * x <= 0.2
```
You can see that the number of constraints this will require is reflected in the binomial coefficient.
This is only for illustrative purposes, though, and I would recommend to go with the readily available function linked above.

**Comment by phschiele** [comment]
@sven-borden here is an MWE of this constraint:

```
import cvxpy as cp
from tests.utilities_for_tests import setup_efficient_frontier

ef = setup_efficient_frontier()
ef.efficient_return(0.1)  # without the constraint, the sum of the two largest weights is above 20%

ef.add_constraint(lambda x: cp.sum_largest(x, 2) <= 0.2)
ef.efficient_return(0.1)  # with the constraint, the sum of the two largest weights is <= 20%
```

**Comment by sven-borden** [comment]
Thank you @phschiele , your solution works great and also thank for the previous explanations!

**Comment by robo-houdie92** [comment]
Hi, a quick follow up question: If I do not know the number of assets beforehand (e.g., 2), but all assets with an individual weight >= 5%, can I formulate such a constraint?
Basically: lambda x: sum([i if i>=0.05 else 0 for i in x]) <= 0.4
That is, the sum of all assets with an individual weight >= 5% should not exceed 40%.
Thanks in advance for your help!

**Comment by phschiele** [comment]
@robo-houdie92 Yes, this can be done.
Consider the below code:
```py
import cvxpy as cp
import numpy as np
from tests.utilities_for_tests import setup_efficient_frontier

threshold = 0.05
limit = 0.4

ef = setup_efficient_frontier()
z = cp.Variable(ef.n_assets, boolean=True)
ef.add_constraint(lambda w: w - threshold <= z)  # x > limit => z = 1, assuming each weight has an upper bound of 1.0
ef.add_constraint(lambda w: cp.sum(cp.pos(w-threshold)) <= limit - threshold * cp.sum(z))
ef.efficient_return(0.1)
large_weights = ef.weights[ef.weights > 0.05]
print(large_weights)
print(np.sum(large_weights))

>>> [0.19260117 0.20739883]
>>> 0.4
```

Notes:
- This requires the use of mixed-integer programming, which can make solving the problem much slower. 
- You need to install a mixed-integer solver (e.g. you can get started with the community version of CPLEX by installing `pip install cplex`)
- The first constraint added is referred to as "implication of positivity". You can read more about it [here](https://docs.mosek.com/modeling-cookbook/mio.html#implication-of-positivity)
- Technically the implementation considers only the weights `> 5%`, not `>= 5%`, but this should not make any difference, as you can get arbitrarily close to the equality. 

cc: @robertmartin8

**Comment by robo-houdie92** [comment]
@phschiele: Thank you very much for your help! Your solution worked :)
However, I've got one remaining question: when I also would like to include individual asset caps, I usually do that using the weight_bounds argument. When I input that into the problem (with individual caps of (0, 0.2)), then I get the following error:

**Comment by phschiele** [comment]
> @phschiele: Thank you very much for your help! Your solution worked :)
> 
> However, I've got one remaining question: when I also would like to include individual asset caps, I usually do that using the weight_bounds argument. When I input that into the problem (with individual caps of (0, 0.2)), then I get the following error:
> 
> 
> 
> cvxpy.error.SolverError: Either candidate conic solvers (['GLPK_MI']) do not support the cones output by the problem (SOC, NonNeg, Zero), or there are not enough constraints in the problem.
> 
> 
> 
> Does that mean that I cannot include individual weight caps when also trying to solve the above mixed-integer programming problem? Or is there a solution to also include individual upper bounds (assuming individual asset bounds are all the same, e.g. 20%)?

@robo-houdie92 have you installed a mixed integer solver such as `cplex` or `xpress` as suggested above?
