### ISSUE TITLE
Portfolio mix

### ISSUE THREAD

**Issue by talsisinay** [robertmartin8/PyPortfolioOpt#211]
Hey,

In the user guide, you have a great visualization showing thousands of different portfolios, overlaid by the efficient frontier:
![](https://pyportfolioopt.readthedocs.io/en/latest/_images/efficient_frontier.png)

I was trying to write some code that builds different mixes of weights to get a similar visualization using random weights, but it seems like a very hard problem to get an "exhaustive" list of permutations, they seem to concentrate "in the middle" when using this approach. Can you share how this can be done?

I know that the library provides a way to plot the EF line, but am interested in the random portfolios.

Thanks!

**Comment by phschiele** [comment]
@talsisinay the figure is quite similar to the one in [this blog post](https://towardsdatascience.com/efficient-frontier-portfolio-optimisation-in-python-e7844051e7f). The generating code can also be found in the post.

You describe a concentration "in the middle". This can be  visualized by looking simply at the weight generation part:
```
import numpy as np
weights = np.random.random((1000,3))
weights/=weights.sum(axis=1)[:,None]  
```
Plotting these portfolio weights in three dimensions, we see exactly this concentration:
```
import matplotlib.pyplot as plt
fig = plt.figure()
ax = fig.add_subplot(111, projection='3d')
ax.scatter(weights[:,0], weights[:,1], weights[:,2])
ax.view_init(30,30)
plt.show()
```

![image](https://user-images.githubusercontent.com/44360364/97605361-d2986880-1a0e-11eb-8afa-604abf03da5c.png)

I suggest you look into the [Dirichlet distribution](https://en.wikipedia.org/wiki/Dirichlet_distribution):

```
weights = np.random.dirichlet([1,1,1],1000)
```
which yields
![image](https://user-images.githubusercontent.com/44360364/97605964-8dc10180-1a0f-11eb-9114-f0d11ca22442.png)

Hope this helps!

**Comment by talsisinay** [comment]
Very helpful - Thank you very much!
