### ISSUE TITLE
efficient_risk error: Please check your objectives/constraints or use a different solver.

### ISSUE THREAD

**Issue by kruzel** [robertmartin8/PyPortfolioOpt#213]
Hi,
I'm trying to calculate efficient_risk with target_volatility.
![image](https://user-images.githubusercontent.com/975963/97683155-015f1f00-1aa1-11eb-842a-770bf0a74f95.png)
this is the efficient_risk code
![image](https://user-images.githubusercontent.com/975963/97683985-39666200-1aa1-11eb-95ab-e7a7d2abd4a1.png)

error message:
Please check your objectives/constraints or use a different solver.

but target_volatility 0.15 looks ok according to efficient frontier plot.

thanks

**Comment by phschiele** [comment]
Hi @kruzel ,
from your example, it is not completely clear to me, if the `mu` and `S` in the first snippet are the same as `cov` and `er` below.
Would you mind sharing a complete MWE?
Ideally, could you paste the code in text form using the "Insert Code" function in the text editor?
This makes reproducing the error much easier.

**Comment by kruzel** [comment]
hi phschiele,
coming to think of it I'm using backtest that break the prices series into smaller sets and on each I run this function, while the efficient frontier chart I use all history.
when I change target_volatility to 0.8 it doesn't fail.

btw, I send you the backtest code as a separate issue to add to the project if u want.
