### ISSUE TITLE
Could not install on MacOS

### ISSUE THREAD

**Issue by bvrilliance** [robertmartin8/PyPortfolioOpt#214]
**Operating system, environment, python version**
e.g MacOS 10.15.7, Terminal
**What you tried**
pip install pyportfolioopt
and through poetry

**Error message**
ERROR: Command errored out with exit status 1:
   command: /Users/valeriafilip/opt/anaconda3/bin/python /Users/valeriafilip/opt/anaconda3/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /var/folders/07/ttj1rb556c36spbvys0zdmt80000gn/T/tmpx0rnfy1d
       cwd: /private/var/folders/07/ttj1rb556c36spbvys0zdmt80000gn/T/pip-install-kz96pk6b/cvxpy
....

gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/valeriafilip/opt/anaconda3/include -arch x86_64 -I/Users/valeriafilip/opt/anaconda3/include -arch x86_64 -Icvxpy/cvxcore/src/ -Icvxpy/cvxcore/python/ -Icvxpy/cvxcore/include/ -I/Users/valeriafilip/opt/anaconda3/include/python3.8 -I/private/var/folders/07/ttj1rb556c36spbvys0zdmt80000gn/T/pip-build-env-wkywb5vm/overlay/lib/python3.8/site-packages/numpy/core/include -c cvxpy/cvxcore/src/cvxcore.cpp -o build/temp.macosx-10.9-x86_64-3.8/cvxpy/cvxcore/src/cvxcore.o -O3
  xcode-select: note: no developer tools were found at '/Applications/Xcode.app', requesting install. Choose an option in the dialog to download the command line developer tools.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for cvxpy
  Building wheel for scs (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/valeriafilip/opt/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/07/ttj1rb556c36spbvys0zdmt80000gn/T/pip-install-kz96pk6b/scs/setup.py'"'"'; __file__='"'"'/private/var/folders/07/ttj1rb556c36spbvys0zdmt80000gn/T/pip-install-kz96pk6b/scs/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/07/ttj1rb556c36spbvys0zdmt80000gn/T/pip-wheel-hrov0ui9
       cwd: /private/var/folders/07/ttj1rb556c36spbvys0zdmt80000gn/T/pip-install-kz96pk6b/scs/
  Complete output (59 lines):

 .....

Choose an option in the dialog to download the command line developer tools.
  error: Command "gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/valeriafilip/opt/anaconda3/include -arch x86_64 -I/Users/valeriafilip/opt/anaconda3/include -arch x86_64 -DPYTHON -DCTRLC=1 -DDLONG=1 -DCOPYAMATRIX -DUSE_LAPACK -DSCIPY_MKL_H -DHAVE_CBLAS -DSCIPY_MKL_H -DHAVE_CBLAS -Iscs/include -Iscs/linsys -Iscs/linsys/cpu/direct/ -Iscs/linsys/external/amd -Iscs/linsys/external/dqlql -I/Users/valeriafilip/opt/anaconda3/lib/python3.8/site-packages/numpy/core/include -I/Users/valeriafilip/opt/anaconda3/include -I/Users/valeriafilip/opt/anaconda3/include -I/Users/valeriafilip/opt/anaconda3/include/python3.8 -c src/scsmodule.c -o build/temp.macosx-10.9-x86_64-3.8/src/scsmodule.o -O3" failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for scs
  Running setup.py clean for scs
  Building wheel for ecos (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/valeriafilip/opt/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/07/ttj1rb556c36spbvys0zdmt80000gn/T/pip-install-kz96pk6b/ecos/setup.py'"'"'; __file__='"'"'/private/var/folders/07/ttj1rb556c36spbvys0zdmt80000gn/T/pip-install-kz96pk6b/ecos/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/07/ttj1rb556c36spbvys0zdmt80000gn/T/pip-wheel-71egh5s9
       cwd: /private/var/folders/07/ttj1rb556c36spbvys0zdmt80000gn/T/pip-install-kz96pk6b/ecos/
  Complete output (24 lines):

.....

  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/valeriafilip/opt/anaconda3/include -arch x86_64 -I/Users/valeriafilip/opt/anaconda3/include -arch x86_64 -DPYTHON -DDLONG -DLDL_LONG -DCTRLC=1 -Iecos/include -Iecos/external/amd/include -Iecos/external/ldl/include -Iecos/external/SuiteSparse_config -I/Users/valeriafilip/opt/anaconda3/include/python3.8 -I/Users/valeriafilip/opt/anaconda3/lib/python3.8/site-packages/numpy/core/include -c src/ecosmodule.c -o build/temp.macosx-10.9-x86_64-3.8/src/ecosmodule.o
  xcode-select: note: no developer tools were found at '/Applications/Xcode.app', requesting install. Choose an option in the dialog to download the command line developer tools.
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for ecos
  Running setup.py clean for ecos
Failed to build cvxpy scs ecos
ERROR: Could not build wheels for cvxpy which use PEP 517 and cannot be installed directly
<img width="1440" alt="Screen Shot 2020-10-30 at 17 58 17" src="https://user-images.githubusercontent.com/68708405/97729386-5ae43f80-1adb-11eb-9843-fe45962c5966.png">

**Comment by robertmartin8** [comment]
Hi @bvrilliance,

Could you please try the solution described [here](https://github.com/robertmartin8/PyPortfolioOpt/issues/181)?

Let me know if that works.

Robert

**Comment by bvrilliance** [comment]
Hi Robert, I installed Xcode and Command Lines Developer Tools from the Apple website and it worked
