### ISSUE TITLE
Negative returns on efficient_return()

### ISSUE THREAD

**Issue by georgk10** [robertmartin8/PyPortfolioOpt#215]
I'm trying to optimize the volatility of a portfolio with a given return. The portfolio is a long/short one and should be equally weighted, therefore I'm using the following code:

>df = pd.DataFrame({symbol: prices[symbol] for symbol in symbols})
>mu = pd.Series([returns[symbol] for symbol in symbols], index=symbols)    
>sigma = risk_models.CovarianceShrinkage(df).ledoit_wolf()
>ef = EfficientFrontier(mu, sigma, weight_bounds=(-1,1))
>pfolio = ef.efficient_return(mu.abs().mean(), True)

"mu" contains the expected returns for each ticker. Because it's a long/short portfolio it also contains negative predicted returns regularly (which should produce positive returns when short selling the asset). To make sure the return parameter given to the  "efficient_return" function actually is achievable, I'm using the mean of all predicted returns. Nevertheless, the function returns the followin error:

>ValueError: target_return must be lower than the largest expected return

I'm pretty sure this happens because of the negative returns in "mu", but I'm not sure whether this is a bug or the expected behavior. 

Can this library even handle negative returns? And if so, how else should the above function be used?

**Comment by robertmartin8** [comment]
Hi @georgk10 

Thanks for reaching out! I'm pretty sure this is a bug, in particular, [this line](https://github.com/robertmartin8/PyPortfolioOpt/blob/8a9f37d080a33df025cc0410c884a4a06230c5a5/pypfopt/efficient_frontier.py#L329). Basically, if you have two assets with respective mean returns -10% and +5%, although return targets of e.g +8% should be achievable by shorting the first asset, PyPortfolioOpt complains that 8% is above 5%.

I need to change `target_return > self.expected_returns.max()` to `target_return > self.expected_returns.abs().max()`.

Before I push a fix, could you please change your `target_return` to `mu[mu > 0).mean()` to make sure there are no other problems?

Best,
Robert

**Comment by georgk10** [comment]
Hi Robert, 

thanks for the quick response. Using `mu[mu > 0].mean()` as target return causes no further exceptions, so it's most likely just that one line you pointed out that needs to be changed.

Thanks again & best regards
Georg

**Comment by robertmartin8** [comment]
@georgk10 

Great, will try to push a fix today!

Best,
Robert

**Comment by ayberkakbalik** [comment]
Hi @robertmartin8,

I found the expected annual return, annual volatility and sharpe ratio using the template below with your help.

![Sharpe Ratio](https://user-images.githubusercontent.com/63553314/167813615-df8869db-ac2e-43d2-a7fc-49eb87733881.png)

Now I'm trying to find Sortino Ratio and Max Drawdown (CDAR). I checked, the library I'm using is the one where you fixed the bug "target_return > self.expected_returns.max()" with "target_return > np.abs(self.expected_returns).max()". When I use the template below to find the Sortino Ratio, I get still a "target_return must be lower than the largest expected return" error. Can you help me?

For Sortino Ratio:

mu = expected_returns.mean_historical_return(df)
historical_returns = expected_returns.returns_from_prices(df)
es = EfficientSemivariance(mu, historical_returns)
es.efficient_return(0.20)

weights = es.clean_weights()
print(weights)
es.portfolio_performance(verbose=True)
