### ISSUE TITLE
Why does the program output the same values every time?

### ISSUE THREAD

**Issue by sharief101** [robertmartin8/PyPortfolioOpt#218]
![image](https://user-images.githubusercontent.com/57871653/98474973-8f36ba80-21c3-11eb-9174-aabc0f48a95a.png)

After downloading the code and numpy... , whenever the program (screenshot provided) is run, the same output is provided.

![image](https://user-images.githubusercontent.com/57871653/98475359-c3aa7680-21c3-11eb-8784-6e2e28ef2a36.png)

Basically, how do I get the program to access the internet to give me real-time predictions?

Sorry, I'm new to this. Thanks!

**Comment by phschiele** [comment]
Hi @sharief101,

you are reading in a static `.csv` file at the top, i.e. using always the same input data. Given the same inputs, it is a good thing that you are also getting the same outputs.

You should dynamically load the prices from some stock data API to get the desired updates. Yahoo finance could be a good place to start.
