### ISSUE TITLE
Downside deviation calculation

### ISSUE THREAD

**Issue by talsisinay** [robertmartin8/PyPortfolioOpt#219]
Hey,

I'm trying to calculate the Sortino index and downside variation/downside risk. A natural candidate would be to use semicovariance, with benchmark = 0 - ie:
risk_models.semicovariance(data, benchmark=0, returns_data=True, frequency=12)

However, this seems a bit different than the classic method - the current implementation, in this case, will form a matrix with negative months only, and will then calculate the variance of this matrix (ie: sum of difference from average), where for "downside deviation" - this should be - sum of difference from 0 (and not from average) - for negative numbers. This will result with a different number.

For example. for:

-4.98%
-0.08%
6.73%
0.39%
1.70%
0.35%
3.65%
0.12%
0.01%
-1.73%
3.68%
2.03%

semicovariance will result with 0.002395221481, whereas classic online calculators will result in 0.00277995.

See here for example:
https://www.thebalance.com/what-is-downside-deviation-4590379

--

**Comment by phschiele** [comment]
I also stumbled upon this issue during the creation of PR #227 

Compare the definition in [Estrada (2007)](https://papers.ssrn.com/sol3/papers.cfm?abstract_id=1028206):
![image](https://user-images.githubusercontent.com/44360364/100211088-fd8db380-2f0b-11eb-9826-d8c35f755e03.png)

**Comment by phschiele** [comment]
Opened PR #228 to adapt the risk model.

**Comment by talsisinay** [comment]
Also take a look on http://www.redrockcapital.com/Sortino__A__Sharper__Ratio_Red_Rock_Capital.pdf which demostrates the calculation clearly.

**Comment by robertmartin8** [comment]
Fixed in v1.3.0
