### ISSUE TITLE
Wrong annualized return?

### ISSUE THREAD

**Issue by talsisinay** [robertmartin8/PyPortfolioOpt#220]
base_optimizer returns the "annualized return", and does so by multiplying each stock's annualized return, by the weights.
From my simulations, this is wrong - the "mixed" annualized return is different when calculated separately.
This happens only for >1 year data. I think it has something to do with intra-year compounding where you start the 2nd+ year with a different weight because the underlying growth.

Consider these 2 series over 24 months:

1. Grows by 10% each month, so for an investment of $50:
55
60.5
66.55
73.205
80.5255
88.57805
97.435855
107.179441
117.897385
129.687123
142.655835
156.921419
172.613561
189.874917
208.862408
229.748649
252.723514
277.995866
305.795452
336.374997
370.012497
407.013747
447.715122
492.486634

2. Grows by 1% each month, so for a $50 investment:

50.5
51.005
51.51505
52.0302005
52.5505025
53.0760075
53.6067676
54.1428353
54.6842636
55.2311063
55.7834173
56.3412515
56.904664
57.4737107
58.0484478
58.6289322
59.2152216
59.8073738
60.4054475
61.009502
61.619597
62.235793
62.8581509
63.4867324

First one's annualized return is 213.8%
Second one's annualized return is 12.68%

For a $100 investment which is split 50% each, the current implementation would yield 113.2%.

But looking at the portfolio's real return (sum for each stock over the same period):
105.5
111.505
118.06505
125.235201
133.076003
141.654058
151.042623
161.322276
172.581648
184.918229
198.439253
213.26267
229.518225
247.348627
266.910856
288.377582
311.938736
337.803239
366.2009
397.384499
431.632094
469.24954
510.573273
555.973366

This yields 135% annualized return which is the correct number.
So there's a 20% gap in this example.

**Comment by phschiele** [comment]
It is generally advisable to work with the frequency of your data as long as possible, only annualising when showing final results / plotting. Doing so in your example above, the monthly expected return is indeed given by `weights * expected returns = 0.5 * 0.1 + 0.5 * 0.01 = 0.055`.

**Comment by talsisinay** [comment]
Thanks for the response @phschiele !
Not sure I get the bottom line here, I am using this for efficient_return and then expected_return. I am passing 12 as a frequency when calculating the returns:
expected_returns.mean_historical_return(data, returns_data=True, frequency=12)

Is there anything I need to differently to fix this?

**Comment by phschiele** [comment]
If you work with annualised numbers (i.e. frequency=12), you will get the expected return for only one compounding step per year. In your case, it seems like you want monthly compounding. In that case, I would not annualise the returns (frequency=1, likewise for the covariance matrix). Next, I would target a monthly return in `efficient_return`. Using this return in monthly compounding as per your example above, you will not have this discrepancy.

**Comment by talsisinay** [comment]
Thanks, but this example was given just to demonstrate the problem. In real life, monthly returns will be much different. Tested now on a real dataset with 2 stocks and frequency=1 still gives a wrong result compared to the real mix (even if you then annualize it).

I think the right solution will be to compound "steps" between years...

**Comment by talsisinay** [comment]
Here is a real dataset:

stock 1:
5.635913
-3.636053
-2.741046
0.516825
2.430912
0.57509
3.704643
3.191993
0.594544
-6.910422
1.854927
-8.804842
8.006566
3.241552
1.810072
4.085241
-6.377112
6.958643
1.511948
-1.674355
1.945804
2.210455
3.619831
2.905546

stock 2:
3.234937
-2.07599
0.632001
-0.953975
-1.195921
-3.614945
-2.241891
-2.138112
-0.660735
2.119545
0.338688
4.942011
2.886598
-0.60922
-1.5969
-0.663884
1.75743
8.002915
0.007515
7.912313
-3.394786
2.563547
-3.208588
3.655878

with weights: 0.56722467, 0.43277533 (returned for efficient_return(0.1) and frequency=12, you will get - 
"annualized performance: 10.00%"

when tested for the real mix (starting with 100):
104.59683
--
101.490631
100.184436
100.054672
100.905377
99.6803953
100.903749
101.960752
102.06825
98.5786726
99.7961523
96.5683528
102.127374
103.756541
104.156101
106.383085
103.049592
110.671211
111.643135
114.243476
113.779444
116.466106
117.277979
121.047587

You will get 10.2% instead of 10%. The gap can be much bigger of course.

**Comment by phschiele** [comment]
Ok, I think I know what you mean. Having different expected returns will change the composition of the portfolio over time, which is not reflected in the current implementation. 
It basically assumes a rebalancing back to the given weights in each period.

**Comment by robertmartin8** [comment]
I'm closing this issue for now, because I think the current implementation is consistent with several other textbooks / portfolio optimisation software (even if it's not the best reflection of real life).

Please feel free to reopen if you have suggestions.
