### ISSUE TITLE
Are cov matrices for assets with unequal amount of data consistent and reliable?

### ISSUE THREAD

**Issue by artjoms-formulevics** [robertmartin8/PyPortfolioOpt#224]
**What are you trying to do?**
I am willing to create an efficient portfolio (max sharpe) of several assets using basically sample codes, as given in the [User Guide](https://pyportfolioopt.readthedocs.io/en/latest/UserGuide.html), except I am using my own dataset. The idea is simple, I wanted to use `mean_historical_return(df)` and then `CovarianceShrinkage(df).ledoit_wolf()`, yet I've realized that my initial data has some securities, that started to trade publicly later than the dataset starting date. Eventually, that produces no errors or warnings, as these values are getting omitted for calculation.

But what does it mean for the result? Let's say I have 3 assets (let's say AAPL, GOOG, MSFT) with 100 datapoints, and the 4th  (FB) one with only 50. Does it imply, that only last 50 points would be taken for cov matrix? Or does it take the maximum points available for each pair, i.e. maximum for pairs of first 3 and 50 points for pairs made for FB?

Wouldn't it make the final results inconsistent, given for example that mean returns for AAPL/GGOG/MSFT are calculated using all 100 datapoints, while their FB cov matrices with only 50?

Thanks in advance for any comments!

**Comment by robertmartin8** [comment]
@artjoms-formulevics 

Good question! It takes the _minimum_ available for each pair. So let's say we have:

- Asset A (50 days)
- Asset B (75 days)
- Asset C (100 days)

The covariance between A and B/C would only use 50 datapoints. The covariance between B and C would use 75 days. 

So you're right that overall, the covariance matrix will include covariances calculated with different numbers of data points. This is perhaps "inconsistent", but users who are unhappy with the inconsistency can easily `risk_models.sample_cov(df.dropna(how="any"))` – so I've erred on the side of flexibility.

Hope this helps!

**Comment by artjoms-formulevics** [comment]
Thanks for the prompt reply! That indeed is fair and helpful. Kudos!
