### ISSUE TITLE
Adding Stratified Models - Portfolio Optimization 

### ISSUE THREAD

**Issue by andrewcztrack** [robertmartin8/PyPortfolioOpt#229]
Hi @robertmartin8 !!! I hope your well.

i was wondering how difficult would it be to add the below to the package -

https://github.com/cvxgrp/strat_models/blob/master/examples/sectors.py

I was thinking of trying to do it for a university project, however it uses Mosek as the optimizer?
Do you think we could use an open source optimizer instead?

Kind regards and thanks,
Andrew

**Comment by robertmartin8** [comment]
Hi @andrewcztrack,

I've had a brief look through their code. Could you explain what it's actually trying to do? 

As for the Mosek solver, it would be quite easy for you to verify whether it does indeed require Mosek: download their script, replace "Mosek" with "SCS" or "OSQP", and see if it runs. 

Best,
Robert

**Comment by andrewcztrack** [comment]
Hi @robertmartin8 !! I hope your well :)!

I think the innovation comes from how they calculate the covariance matrix.

I tried to replace mosek with SCS but I am getting an error. I will keep working on it.

Would you be able to have a look at the error?

Kind regards and thanks,
Andrew

**Comment by robertmartin8** [comment]
Hi Andrew,

Could you explain the advantages and disadvantages of this method versus PyPortfolioOpt's existing methods for calculating the covariance matrix? 

Robert

**Comment by andrewcztrack** [comment]
Hi @robertmartin8 !! I looked at the multi period trading paper! It looks awesome!

Honestly I happy to close all these issues and just have the below paper as the focus. It seems like the most practical to add from an application perspective.

https://stanford.edu/~boyd/papers/pdf/cvx_portfolio.pdf

Kind regards and thanks,
Andrew

**Comment by andrewcztrack** [comment]
Hi @robertmartin8 from reading the paper, i think the authors try and construct a graph to try and improve the covariance matrix estimation.

This method ‘borrows strength’ from the neighboring covariances, to improve its estimate. With well chosen hyper-parameters, such models can perform very well, especially in the low data regime. We propose a distributed method that scales to large problems, and illustrate the efficacy of the method with examples in finance, radar signal processing, and weather forecasting.

paper reference -

https://web.stanford.edu/~boyd/papers/cov_strat_models.html

From a very high level thats how I understand it, but i could be wrong.

Kind regards and thanks,
Andrew

**Comment by andrewcztrack** [comment]
Hi @robertmartin8 !! I hope your well. did you have a rough eta on when you wanted to start adding the multiperiod portfolio optimisation section.

**Comment by robertmartin8** [comment]
@andrewcztrack There isn't currently a timeline for it – if I were to add new features, it would be in the following order (roughly):

1. CVaR optimisation
2. Optimising higher moments
3. Factor models
4. HRP with returns (e.g Raffinot's HERC or HCAA)
5. Multiperiod.

For people who need multiperiod optimisation, [cvxportfolio](https://github.com/cvxgrp/cvxportfolio) is a good starting point. 

I'm closing this issue for now, but really appreciate all your suggestions!

**Comment by sdafsdfw123wq** [comment]
Hello!

Any update on the multi period portfolio otpimization?
