### ISSUE TITLE
Import data from CSV

### ISSUE THREAD

**Issue by bvrilliance** [robertmartin8/PyPortfolioOpt#231]
Hi, how can I use PyPortOpt using data from csv files? 
My data goes like this until present, 27 Nov 2020. Here is an example from ABC.csv:

Date,Close
2018-01-01,10000.0
2018-01-02,10143.46
2018-01-03,10229.36
2018-01-04,10245.60
2018-01-05,10251.94
2018-01-06,10286.45
....

I tried merging the 2 csv files (ABC.csv and XYZ.csv) each corresponding to one asset:

ABC= pd.read_csv("ABC.csv")
XYZ= pd.read_csv("XYZ.csv")
df = pd.merge(ABC, XYZ, on="Date")
df.rename(columns={"Close_x": "ABC", "Close_y": "XYZ"}, inplace=True)
df

but when doing the calculations for mu and S,  I get an error, TypeError: unsupported operand type(s) for /: 'str' and 'str'

Can you please help me how to use local data from csv files rather than from web, like yahoo?

**Comment by robertmartin8** [comment]
Hi @bvrilliance,

Could you please send `df.head()` for your combined df and let me know the data types of the columns?

There is an example of csv reading [here](https://github.com/robertmartin8/PyPortfolioOpt/blob/master/examples.py). The date index should be a `DatetimeIndex`, not a string.

Hope this helps!
Robert

**Comment by bvrilliance** [comment]
Yeah, thanks it worked!

How can I assign prices to the assets when trying to do the allocation?

**Comment by robertmartin8** [comment]
Do you mean for the discrete allocation? There is an example in [this cookbook recipe](https://github.com/robertmartin8/PyPortfolioOpt/blob/master/cookbook/2-Mean-Variance-Optimisation.ipynb):

```python
from pypfopt import DiscreteAllocation

latest_prices = prices.iloc[-1]  # prices as of the day you are allocating
da = DiscreteAllocation(weights, latest_prices, total_portfolio_value=20000, short_ratio=0.3)
alloc, leftover = da.lp_portfolio()
print(f"Discrete allocation performed with ${leftover:.2f} leftover")
alloc
```
