### ISSUE TITLE
How to use custom optimization function?

### ISSUE THREAD

**Issue by billlyd123** [robertmartin8/PyPortfolioOpt#233]
Hello,

I am trying to use custom solver functions that I have implemented myself beyond what SciPy offers. Is this something that is possible?

**Comment by robertmartin8** [comment]
Hi @billlyd123,

PyPortfolioOpt offers two APIs for it, depending on whether your objective function is convex or nonconvex. These are described [here](https://pyportfolioopt.readthedocs.io/en/latest/EfficientFrontier.html#custom-optimisation-problems). Let me know if that helps!

Best,
Robert
