### ISSUE TITLE
How to use tracking error as constraint

### ISSUE THREAD

**Issue by TomLiu518** [robertmartin8/PyPortfolioOpt#237]
Hi All, is there a away to incorporate tracking error as a constraint in PyPortfolioOpt?  I mean it does not make much sense to minimize TE because TE can always be zero.

**Comment by robertmartin8** [comment]
Hi @TomLiu518,

Minimising TE is quite important if you are trying to replicate an index – you need to know which combination of assets gives the best approximation of some index. This is a key task for index fund providers like BlackRock and Vanguard. 

A full example of using the TE as a constraint is shown below. In this case, we try to minimise the volatility of a portfolio subject to a TE of less than 0.1 (note that this TE function actually gives the square of the TE). 

```python
from pypfopt import expected_returns, risk_models, EfficientFrontier
import yfinance as yf
import cvxpy as cp

# Asset data
tickers = ["MSFT", "AMZN", "KO", "MA", "COST", 
           "LUV", "XOM", "PFE", "JPM", "UNH", 
           "ACN", "DIS", "GILD", "F", "TSLA"] 
ohlc = yf.download(tickers, period="max")
prices = ohlc["Adj Close"].iloc[-500:]
spy_prices = yf.download("SPY", period="max")["Adj Close"].iloc[-500:]

# Get returns
rets = expected_returns.returns_from_prices(prices)
spy_rets = expected_returns.returns_from_prices(spy_prices)


# Define constraint
def TE(w, portfolio_returns, benchmark_returns):
    xi= (w @ portfolio_returns.T - benchmark_returns)
    mean = cp.sum(xi)/len(benchmark_returns)
    return cp.sum_squares(xi- mean)
    
# Construct efficient frontier
mu = expected_returns.mean_historical_return(prices)
S = risk_models.sample_cov(prices)
ef = EfficientFrontier(mu, S)
ef.add_constraint(lambda w: TE(w, rets, spy_rets) <= 0.1**2)
ef.min_volatility()

dict(ef.clean_weights())
```

Result:

```
{'ACN': 0.08108,
 'AMZN': 0.13866,
 'COST': 0.20818,
 'DIS': 0.03824,
 'F': 0.04868,
 'GILD': 0.06069,
 'JPM': 0.02214,
 'KO': 0.13445,
 'LUV': 0.02339,
 'MA': 0.0,
 'MSFT': 0.04025,
 'PFE': 0.0828,
 'TSLA': 0.00652,
 'UNH': 0.04376,
 'XOM': 0.07115}
 ```
 
 Hope that helps!
 Robert

**Comment by TomLiu518** [comment]
Hi Robert,
thanks for the example. I tried to run it but have the following errors. 

  File "<ipython-input-45-5ba5171e2b9d>", line 5, in <module>
    ef.min_volatility()

  File "C:\Users\kx04743\AppData\Local\Continuum\anaconda3\lib\site-packages\pypfopt\efficient_frontier.py", line 166, in min_volatility
    return self._solve_cvxpy_opt_problem()

  File "C:\Users\kx04743\AppData\Local\Continuum\anaconda3\lib\site-packages\pypfopt\base_optimizer.py", line 224, in _solve_cvxpy_opt_problem
    opt.solve(verbose=self._verbose)

  File "C:\Users\kx04743\AppData\Local\Continuum\anaconda3\lib\site-packages\cvxpy\problems\problem.py", line 396, in solve
    return solve_func(self, *args, **kwargs)

  File "C:\Users\kx04743\AppData\Local\Continuum\anaconda3\lib\site-packages\cvxpy\problems\problem.py", line 753, in _solve
    self, data, warm_start, verbose, kwargs)

  File "C:\Users\kx04743\AppData\Local\Continuum\anaconda3\lib\site-packages\cvxpy\reductions\solvers\solving_chain.py", line 326, in solve_via_data
    solver_opts, problem._solver_cache)

  File "C:\Users\kx04743\AppData\Local\Continuum\anaconda3\lib\site-packages\cvxpy\reductions\solvers\conic_solvers\mosek_conif.py", line 233, in solve_via_data
    task.optimize()

  File "C:\Users\kx04743\AppData\Roaming\Python\Python37\site-packages\mosek\__init__.py", line 7627, in optimize
    raise Error(rescode(res),msg)

Error: License cannot be located. The default search path is ';C:\Users\kx04743\mosek\mosek.lic;'.

**Comment by phschiele** [comment]
Hi @TomLiu518 
does not seem to be directly related to PyPortfolioOpt, but you can try to specify a different solver:
`ef = EfficientFrontier(mu, S, solver='ECOS')` is open source and comes with CVXPY.
Alternatively, you could try to locate the license file and manually add it to the search path.
Another option would be to try to isolate the error by trying to [test the mosek installation](https://docs.mosek.com/9.2/pythonapi/install-interface.html#testing-the-installation). The same page also describes different ways to install the solver which you can try out.
Hope this helps.

**Comment by TomLiu518** [comment]
Hi @phschiele 
Thanks for the tips. I tried ECOS but i got error "The solver ECOS is not installed."  I figure out that the solver list is ['CVXOPT', 'GLPK', 'GLPK_MI', 'MOSEK', 'OSQP'], so ECOS is not there? 
I tried 'CVXOPT' and it works.

**Comment by TomLiu518** [comment]
A related question,  I am trying a different way of calculating tracking error. The reason is that the TE function proposed by Robert is more based on historical return and therefore ex-post. Using the covariance matrix, one can calculate a more ex-ante tracking error: 
def TE_exante(w, bm_weights, cov_matrix):
        relative_weights = w - bm_weights
        #relative_weights = np.transpose(relative_weights)
        variance = cp.quad_form(relative_weights,cov_matrix)
        return variance
eq_w = np.ones(15)/15 # assume equal weight for the index
mu = expected_returns.mean_historical_return(prices)
S = risk_models.sample_cov(prices)
ef = EfficientFrontier(mu, S)
ef.add_constraint(lambda w: TE_exante(w, eq_w, S) <= 0.1 ** 2)
ef.min_volatility()
weights = ef.clean_weights()

However, I get a error "setting an array element with a sequence". any idea why?

**Comment by phschiele** [comment]
> A related question, I am trying a different way of calculating tracking error. The reason is that the TE function proposed by Robert is more based on historical return and therefore ex-post. Using the covariance matrix, one can calculate a more ex-ante tracking error:
> def TE_exante(w, bm_weights, cov_matrix):
> relative_weights = w - bm_weights
> variance = cp.quad_form(relative_weights,cov_matrix)
> return variance
> eq_w = np.ones(15)/15 # assume equal weight for the index
> mu = expected_returns.mean_historical_return(prices)
> S = risk_models.sample_cov(prices)
> ef = EfficientFrontier(mu, S)
> ef.add_constraint(lambda w: TE_exante(w, eq_w, S) <= 0.1 ** 2)
> ef.min_volatility()
> weights = ef.clean_weights()
> 
> However, I get a error "setting an array element with a sequence". any idea why?

Good point! Actually, I was already formulating a response to your initial question using ex-ante TE, but @robertmartin8 was slightly faster, so I didn't want to add confusion :) 

The code you provided works fine for me, would you mind adding the stacktrace?

A final note on the solvers: 
[Here](https://www.cvxpy.org/tutorial/advanced/index.html#choosing-a-solver) you can see an overview of solvers supported by CVXPY, and what types of problems they can solve. ECOS can easily be installed e.g. by executing `pip install ECOS`. However, CVXOPT also works nicely in this case.

(FYI: When posting code on GitHub, using the "insert code" feature makes it much easier for others to copy and paste the code, especially in Python, where indentation matters)

**Comment by TomLiu518** [comment]
@phschiele  I figured out the issue, but thanks so much all the same!

**Comment by robertmartin8** [comment]
As of v1.3.0, both ex-ante and ex-post have been built into the `objective_functions` module.
