### ISSUE TITLE
Bug: some test functions not being run due to names

### ISSUE THREAD

**Issue by SeaPea1** [robertmartin8/PyPortfolioOpt#242]
Functions custom_nonconvex_sharpe() and custom_nonconvex_kelly() are not run by pytest, despite being valid tests because of their names.

**Comment by robertmartin8** [comment]
@SeaPea1 Thanks for pointing this out, and for the fix. Looking to merge everything within the next fortnight!

Cheers,
Robert

**Comment by SeaPea1** [comment]
No problem.  I have some other stuff too, but these were related and could
go in the same pull request.  I need to get the others into a separate pull
request.
