### ISSUE TITLE
BaseConvexOptimizer default solver is not "ECOS" as stated in the inline comment/documentation.

### ISSUE THREAD

**Issue by SeaPea1** [robertmartin8/PyPortfolioOpt#244]
It isn't specified unless it is overridden using the solver param.  It therefore is defaulting to whatever is used in CVXPY.  That happens to currently be "OSQP" in my environment, though "ECOS" is available and works.  To fix it should either be explicitly specified (overriding CVXPY's defaults) or the misleading comment removed.

**Comment by robertmartin8** [comment]
I will probably remove the comment, because I'm guessing the folks at CVXPY have put plenty of thought into what the defaults should be in different cases.

**Comment by SeaPea1** [comment]
I agree, probably best to remove the comment, which is why I have done in the pull request.
I'm afraid I don't know why the CVXPY people have chosen different defaults for the tolerances for the different solvers, there may well be very valid reasons.  As it happens the "ECOS" seems to have some of the tightest tolerances, so it is a bit of a shame it isn't actually the default solver.
