### ISSUE TITLE
Feature request: BaseConvexOptimizer solver can be specified, but the solvers configuration params cannot.

### ISSUE THREAD

**Issue by SeaPea1** [robertmartin8/PyPortfolioOpt#245]
That can be an issue, as the defaults in CVXPY vary greatly from solver to solver.

**Comment by robertmartin8** [comment]
Good point. I can probably just include a `optimizer_kwargs` in the constructor. What do you think?

**Comment by SeaPea1** [comment]
I think that's a good idea, so did in the pull request.
