### ISSUE TITLE
Feature request: Question about DiscreteAllocation

### ISSUE THREAD

**Issue by kayuksel** [robertmartin8/PyPortfolioOpt#251]
Wouldn't it make more sense to use KL or JS divergence instead of RMSE to find the optimal discrete allocation?

https://en.wikipedia.org/wiki/Kullback%E2%80%93Leibler_divergence
https://en.wikipedia.org/wiki/Jensen%E2%80%93Shannon_divergence

**Comment by robertmartin8** [comment]
Hi @kayuksel,

Interesting thought. Can you explain the reasoning behind it a little more? 

I wouldn't have thought that they are appropriate: KL and JS divergence measure the similarity between two distributions, while the discrete allocation task is to find an integer vector of weights that is "closest" to the continuous weights.

So for me, RMSE (or something like the MAE) makes much more sense.

Best,
Robert

**Comment by kayuksel** [comment]
I can just say that nobody uses RMSE to measure the divergence of class probabilities, which is quite often used in Deep Learning for many applications e.g. for measuring how noises effects the output class probabilities. KL or JS divergence is the default method that people use for such use-cases. They are a measure of information loss e.g. as a result of the discrete allocation. Here, I found an answer that explains the reasoning why KL or JS divergence is better over L1 and L2:

https://ai.stackexchange.com/questions/15367/advantages-of-kullback-leibler-over-l1-l2

**Comment by robertmartin8** [comment]
@kayuksel Thanks for sharing the resources! I agree with you regarding the divergence of class probabilities (though I wonder whether Brier scores are a counterexample?), I just hadn't thought about the discrete allocation problem in terms of probabilities. 

I would definitely be open to other distance measures, provided they can be optimised with CVXPY. The computational problem here (which is not addressed in the thesis) is that we have integer constraints. 

The current solution minimises something like the L1 norm with a [clever linear program](https://github.com/robertmartin8/PyPortfolioOpt/blob/795bf9d2d4a636e662e829f7260f4640d31e4b53/pypfopt/discrete_allocation.py#L297) devised by [gumblex](https://github.com/robertmartin8/PyPortfolioOpt/pull/14/commits/967432d711b1289f009a1f0ed092bcc03cbf613b). 

Cheers,
Robert

**Comment by phschiele** [comment]
Interesting though, @kayuksel !
In my experience, MAE or tracking error are most common. 
You already mention that the probability analogy does not naturally extend for portfolios with short positions. 
Nevertheless, it would be interesting to see how different the resulting portfolios would be!

**Comment by kayuksel** [comment]
@robertmartin8 I don't know much about Linear programming so I wouldn't know how they would effect. But I believe that they can be a better distance metric for the greedy version of your algorithm. The reason why people are using it over L1 or RMSE is probably because they make better loss functions. In fact, CVXPY seems to have a relevant allocation example with KL-div:

https://www.cvxpy.org/examples/applications/optimal_power_gaussian_channel_BV4.62.html

@phschiele It extends when you assume that they're long-only with some inverse assets. However, preserving the long-short ratio as much as possible after the discrete allocation is also very meaningful and can be done by treating long and short positions separately as two long-only portfolios and then merging, as I believe already how it is done in the current implementation.

**Comment by robertmartin8** [comment]
@kayuksel I'm not sure whether the greedy algorithm is so amenable to modifying the distance function – it doesn't explicitly compute the distance between two portfolios (though implicitly it uses L1).

Let's say the `discrete_allocation` module didn't exist. What algorithm would you use to convert the continuous weights to an integer allocation? (or if you can point me in the direction of any other research). 

I'm not sure if I'm googling the wrong terms, but I really can't find anything on it (which is why I resorted to hacking together a greedy algo).

**Comment by kayuksel** [comment]
Hello @robertmartin8 , your algorithm that is implemented over this library is great and I also didn't encounter anything better. I was just curious if changing distance function would be of any help on improving it and wanted to confirm if divergence considered.

**Comment by robertmartin8** [comment]
@kayuksel no worries. Your inputs are very valuable, so please don't hesitate to comment / raise new issues if you come across anything :)
