### ISSUE TITLE
Short value not added to long value by default in DiscreteAllocation.greedy_portfolio

### ISSUE THREAD

**Issue by arcaputo3** [robertmartin8/PyPortfolioOpt#260]
As of now, the cash gained from shorting is not reinvested long, although this is the claimed functionality. Proposed fix:
`da1 = DiscreteAllocation(
                longs,
                self.latest_prices[longs.keys()],
                total_portfolio_value=self.total_portfolio_value + short_val,
            )`

**Comment by arcaputo3** [comment]
A quick and dirty fix is, for some short ratio `sr`,
`import pypfopt as po`
`do = po.discrete_allocation.DiscreteAllocation(weights, prices, capital * (1 + sr), sr / (1 + sr))`
`res = do.greedy_portfolio()`

**Comment by robertmartin8** [comment]
Fixed with v1.3.0
