### ISSUE TITLE
How to add tracking error as an objective function?

### ISSUE THREAD

**Issue by GreekQuant** [robertmartin8/PyPortfolioOpt#262]
**What are you trying to do?**
I am trying to replicate an index  by minimising the tracking error (TE). I am planning to migrate to PyPortfolioOpt, hence I will need some help for now. The code I am currently using is the below - cvxpy package.

```
import cvxpy as cp
w = cp.Variable(returns_avg.shape[0])
port_avg_ret = w.T@returns_avg
TE =  cp.quad_form((w-bench_weight), var_covar)

constraints = [cp.sum(w)==1, port_avg_ret >=target_ret]
constraints.extend([w[i]<=bounds[i][1] for i in range(len(bounds))])
constraints.extend([w[i]>=bounds[i][0] for i in range(len(bounds))])

problem = cp.Problem(cp.Minimize(TE), constraints )
problem.solve(warm_start=True, verbose=True)
```

**What data are you using?**
Main inputs are ex-ante covariance matrix, average return for each constituent in the index, the weight of each constituent in the index, and tuple of tuple I call bounds where the 1 position is the constituent specific upper bound and 0 the constituent specific lower bound. Initially I used:
`cp.abs(w-bench_weight)<=limit`

I dont know if it makes huge difference to use the loop version or the cp.abs() one.

Each target return is the result of a np.linspace() - namely scanning specific returns and building efficient frontier.
 
**Now the question:**
How can I translate this specific example into PyPrtfolioOpt? Since the underlying optimiser has been altered to cvxpy am I going to get the same errors I get  (see below)? Is there anything wrong with the constraints that PyPortfolioOpt defines in a more optimal way?

OSQP -> primal infeasible
ECOS -> primal infeasible
CVXOPT -> Certificate of primal infeasibility found
SCS -> Status: Infeasible

**** 125 constituents

p.s I do not know if it adds any value; when the above is implemented in scipy.minimize then no error is raised

**Comment by robertmartin8** [comment]
Hi @GreekQuant,

Have you looked at issue #237? It might be helpful. 

Best,
Robert

**Comment by GreekQuant** [comment]
Hi @robertmartin8 ,

Yes I have already  had a look at it. Is it just adding TE as a constraint and not objective function or am I missing something?

**Comment by robertmartin8** [comment]
Hi @GreekQuant,

Yes, that's just as a constraint, but you should be able to adapt the code in combination with `convex_objective()` (docs [here](https://pyportfolioopt.readthedocs.io/en/latest/EfficientFrontier.html#custom-optimisation-problems)). 

Let me know if that works for you!

Best,
Robert

**Comment by GreekQuant** [comment]
Awesome @robertmartin8 , thanks!
