### ISSUE TITLE
Analysis for a large file will result in an error.

### ISSUE THREAD

**Issue by Originn** [robertmartin8/PyPortfolioOpt#263]
Before explaining my issue I would like to thank the brilliant mind and kind person who made this tool, well done !

I am trying to run a large file with more then 1500 symbols and 9 years of data. When I  run 

```python
mu = expected_returns.mean_historical_return(df)
S = risk_models.sample_cov(df)
```

I get the following error

```
/usr/local/lib/python3.6/dist-packages/pypfopt/risk_models.py:69: UserWarning: The covariance matrix is non positive semidefinite. Amending eigenvalues.
  "The covariance matrix is non positive semidefinite. Amending eigenvalues."
/usr/local/lib/python3.6/dist-packages/pypfopt/risk_models.py:88: UserWarning: Could not fix matrix. Please try a different risk model.
  warnings.warn("Could not fix matrix. Please try a different risk model.")`
```

Adding methods spectral and diag won't change the issue.

After running 

```python
ef = EfficientFrontier(mu, S)
weights = ef.max_sharpe()

cleaned_weights = ef.clean_weights()
print(cleaned_weights)
ef.portfolio_performance(verbose=True)`
```

I get 

```
OptimizationError                         Traceback (most recent call last)
<ipython-input-36-32b004e14f58> in <module>()
      1 #Optimize for the miximal Sharpe ratio
      2 ef = EfficientFrontier(mu, S)
----> 3 weights = ef.max_sharpe()
      4 
      5 cleaned_weights = ef.clean_weights()

1 frames
/usr/local/lib/python3.6/dist-packages/pypfopt/base_optimizer.py in _solve_cvxpy_opt_problem(self)
    227 
    228         if opt.status != "optimal":
--> 229             raise exceptions.OptimizationError
    230         self.weights = self._w.value.round(16) + 0.0  # +0.0 removes signed zero
    231         return self._make_output_weights()

OptimizationError: Please check your objectives/constraints or use a different solver.`
```

If I would run a smaller size file with 300 stocks it will usually run (once it did run the second time it didn't and I got the error above) 

A file with 100 stocks will run all the time with no issues. I have checked that the data is ok, fixed voids etc.

My code is 

```python
#import the python libraries

import pandas as pd
import numpy as np
import requests 

#Load the data
df = pd.read_csv('stocks.csv')

#Set the date as the index
df = df.set_index(pd.DatetimeIndex(df['Date'].values))

#Remove the date column
df.drop(columns=['Date'], axis=1, inplace=True)

#Get the assets /tickers
assets = df.columns

#Optimize the Portfolio
from pypfopt.efficient_frontier import EfficientFrontier
from pypfopt import risk_models
from pypfopt import expected_returns

#Calculate the expected annualized returns and the annualize sample covariance matrix of the daily asset returns
mu = expected_returns.mean_historical_return(df)
S = risk_models.sample_cov(df)

#Optimize for the miximal Sharpe ratio
ef = EfficientFrontier(mu, S)
weights = ef.max_sharpe()

cleaned_weights = ef.clean_weights()
print(cleaned_weights)
ef.portfolio_performance(verbose=True)

#Get the discrete allocation of each share per stock
from pypfopt.discrete_allocation import DiscreteAllocation, get_latest_prices

portfolio_val = 5000 
latest_prices = get_latest_prices(df)
weights = cleaned_weights
da = DiscreteAllocation(weights, latest_prices, total_portfolio_value = portfolio_val)
allocation, leftover = da.lp_portfolio()
print('Discrete allocation:', allocation)
print('Funds Remaining: $', leftover)
```

If the data is needed please let me know, and thanks again!#

**Comment by robertmartin8** [comment]
Hi @Originn,

Thanks for providing detailed code and error messages, it really helps in debugging (FYI, I have reformatted your issue by using triple backticks to make code blocks).

The problem is that with 9 years of daily data, you have about 2250 datapoints (9x252). This is not much larger than the number of assets, leading to numerical issues when calculating the sample covariance matrix.

Could you try a different method for calculating the covariance matrix? For example

```python
S = risk_models.CovarianceShrinkage(df).ledoit_wolf()
```

These are sometimes able to estimate the covariance matrix even when the number of assets is large relative to the number of datapoints. 

If this doesn't work, unfortunately you will either have to get a lot more data, or reduce the size of the asset universe (e.g remove the stocks with the worst expected returns, as these are unlikely to get allocated much anyway). 

Let me know how you get on!

Best,
Robert

**Comment by Originn** [comment]
Thanks a lot Robert! 

I have tried to run the same number of stocks but only on 5 years worth of data. 

I tried on both
```S = risk_models.sample_cov(df)```

and

```S = risk_models.CovarianceShrinkage(df).ledoit_wolf()```

I get the following error

```
SolverError                               Traceback (most recent call last)
<ipython-input-9-32b004e14f58> in <module>()
      1 #Optimize for the miximal Sharpe ratio
      2 ef = EfficientFrontier(mu, S)
----> 3 weights = ef.max_sharpe()
      4 
      5 cleaned_weights = ef.clean_weights()

4 frames
/usr/local/lib/python3.6/dist-packages/pypfopt/efficient_frontier.py in max_sharpe(self, risk_free_rate)
    224         ] + new_constraints
    225 
--> 226         self._solve_cvxpy_opt_problem()
    227         # Inverse-transform
    228         self.weights = (self._w.value / k.value).round(16) + 0.0

/usr/local/lib/python3.6/dist-packages/pypfopt/base_optimizer.py in _solve_cvxpy_opt_problem(self)
    222                 opt.solve(solver=self._solver, verbose=self._verbose)
    223             else:
--> 224                 opt.solve(verbose=self._verbose)
    225         except (TypeError, cp.DCPError) as e:
    226             raise exceptions.OptimizationError from e

/usr/local/lib/python3.6/dist-packages/cvxpy/problems/problem.py in solve(self, *args, **kwargs)
    288         else:
    289             solve_func = Problem._solve
--> 290         return solve_func(self, *args, **kwargs)
    291 
    292     @classmethod

/usr/local/lib/python3.6/dist-packages/cvxpy/problems/problem.py in _solve(self, solver, warm_start, verbose, parallel, gp, qcp, **kwargs)
    573         full_chain = self._solving_chain.prepend(self._intermediate_chain)
    574         inverse_data = self._intermediate_inverse_data + solving_inverse_data
--> 575         self.unpack_results(solution, full_chain, inverse_data)
    576         return self.value
    577 

/usr/local/lib/python3.6/dist-packages/cvxpy/problems/problem.py in unpack_results(self, solution, chain, inverse_data)
    716             raise error.SolverError(
    717                     "Solver '%s' failed. " % chain.solver.name() +
--> 718                     "Try another solver, or solve with verbose=True for more "
    719                     "information.")
    720         self.unpack(solution)

SolverError: Solver 'OSQP' failed. Try another solver, or solve with verbose=True for more information.
```

I have tried to run it on couple of months and with the same number of stocks and it worked ,although understandably the results were pretty high

```
Expected annual return: 44442507.9%
Annual volatility: 392.8%
Sharpe Ratio: 113138.39
```

As you suggested, maybe I will need to run this on 200 stocks at a time (with 9 years of data), keep the best performing stocks until I'll be left with 200 best stocks and run it one last time.

I am quite a beginner in code writing, but I'll try to write a loop that will do it, and if I am successful I will post here. Do you think it is possible? Any help/guidance in writing it will be greatly appreciated! 

Thanks!

Ori

**Comment by robertmartin8** [comment]
Hi @Originn,

Sorry if I wasn't clear: you need to increase the amount of data relative to the number of stocks. So if you want to use 1500 stocks, you should get e.g 15-20 years of data (this is just an estimate – I don't know how much you actually need). 

However, I think it's a better idea to reduce the size of the stock universe first. 

One way to do this (as mentioned previously) is to remove the stocks with the lowest expected returns. The below script takes the top 500 stocks (ranked by `mu`) from your universe.

```python
mu = expected_returns.mean_historical_return(df)
top_stocks = mu.sort_values(ascending=False).index[:500]
df = df[top_stocks]

# Now proceed as you did before, and it _should_ be fine.
mu = expected_returns.mean_historical_return(df)
S = risk_models.sample_cov(df)
...
```

You can easily extend this to make it more complicated, for example, filtering by historical Sharpe ratio rather than return.

```python
S = risk_models.sample_cov(df)
std = np.diag(S)
mu = expected_returns.mean_historical_return(df)
sharpes = mu / std 
top_stocks = sharpes.sort_values(ascending=False).index[:500]
df = df[top_stocks]
```

The idea here, as I have mentioned in other threads (#128 , #243) is that _portfolio selection_ is conceptually quite different to _portfolio optimisation_.

Hope this helps!
Robert

**Comment by Originn** [comment]
Thank you very much Robert it's working well.

**Comment by robertmartin8** [comment]
I'm glad to hear! Please feel free to raise any other issues you encounter.

Best,
Robert
