### ISSUE TITLE
No module name Pypfort

### ISSUE THREAD

**Issue by phamanhtu17295** [robertmartin8/PyPortfolioOpt#269]
Operation system:
Ubuntu 18.04, Anaconda, Python 3.7

I try to install Pyport according to instruction but the system cannot find the module "pypfopt" 

Is there something wrong ?

![Screenshot from 2021-02-01 11-23-15](https://user-images.githubusercontent.com/74130487/106414734-f04af300-647f-11eb-9103-8d2272fcab47.png)
![Screenshot from 2021-02-01 11-23-31](https://user-images.githubusercontent.com/74130487/106414737-f17c2000-647f-11eb-8d1a-6e47b3773eab.png)

**Comment by robertmartin8** [comment]
@phamanhtu17295 

Does `import pandas, cvxpy` work?

**Comment by phamanhtu17295** [comment]
I have run your model smoothly on my computer. Thank you very much for your contribution.

**Comment by robertmartin8** [comment]
Great. Glad it's working!
