### ISSUE TITLE
Test solved weights for EfficientFrontier can be calculated in some cases.

### ISSUE THREAD

**Issue by SeaPea1** [robertmartin8/PyPortfolioOpt#271]
The tests often have hard-coded "magic" values for the expected weights, vol and Sharpe ratio results but at least in some cases the solver results could be validated against values that can be calculated.

I will provide a test utility that will calculate the values and use it in some tests to validate the values.

**Comment by robertmartin8** [comment]
Yes, that'd be great! Hard coding weights is far from ideal, so any improvements there are appreciated.

**Comment by robertmartin8** [comment]
Fixed in v1.4.0
