### ISSUE TITLE
max_return() optimisation

### ISSUE THREAD

**Issue by benlvovsky** [robertmartin8/PyPortfolioOpt#275]
**I need to get a portfolio with the maximum return out of the whole efficient frontier**

I show chart on a screen with dots for efficient frontier from min_volatility()/risk for it as a very left bottom point and I need something like max_return() (and then calculate risk for it) for the very top right point of the efficient frontier. 
Currently I calculate say 100 points for efficient frontier and use interpolation to show smooth chart.

**various stock data**
I need something like max_return()

**Comment by robertmartin8** [comment]
Hi @benlvovsky,

If your portfolio is long-only, the `max_return` is simply the highest expected return out of your assets, e.g `mu.max()`. This corresponds to a portfolio that is 100% weighted in this asset, so the corresponding portfolio volatility is the volatility of that asset.

Once you calculate the `max_return`, you can just use it as your upper bound in the `pypfopt.plotting` module, e.g

```python
return_range = np.linspace(min_return, max_return, 100)  # 100 points on the frontier
ax = plotting.plot_efficient_frontier(ef, ef_param="return", ef_param_range=return_range,
                           show_assets=True, showfig=True)
```

Hope this helps!
Robert

**Comment by benlvovsky** [comment]
Thanks a lot!
Just one thing which is probably normal: the max return from mu.max() which
I pass to efficient_return() produces a portfolio with slightly different
return. I guess it is a normal error:

end_return = mu.max()

ef.efficient_return(end_return)
(end_return1, end_risk1, _) = ef.portfolio_performance()


end_return  =1.0052181559682412
end_return1=1.0052168269502733

Just want to make sure I am doing it right.

**Comment by phschiele** [comment]
@benlvovsky Maybe one further point: if you have constraints on the weights, the `max_return` can also be found by solving a linear program:
```python
import numpy as np
import cvxpy as cp
np.random.seed(1)

n = 10
mu = np.abs(np.random.randn(n, 1))

w = cp.Variable(n)
ret = mu.T@w
first_five = np.array([1,1,1,1,1,0,0,0,0,0])  # some random constraints, could be regions, currencies, ...
odd = np.array([0,1]*5)
even = np.array([1,0]*5)
prob = cp.Problem(cp.Maximize(ret), 
               [cp.sum(w) == 1, 
                w >= 0,
                cp.sum(cp.multiply(first_five,w)) <= 0.3,
                cp.sum(cp.multiply(odd,w)) <= 0.4,
                cp.sum(cp.multiply(even,w)) >= 0.2])
prob.solve()
```

@robertmartin8 Perhaps it would make sense to include such a helper function, such that e.g. the constraint interfaces from PyPortfolioOpt can still be used. Could also improve the current plotting logic (i.e., add an "auto" case, which plots from GMVP to max return PF.

**Comment by robertmartin8** [comment]
@phschiele Good suggestions. I can add `max_return` to the `EfficientFrontier` class (or do you think it is logically better suited to `BaseConvexOptimizer`?)

There is certainly a lot of room for improvement in the plotting functionality

**Comment by phschiele** [comment]
It does need the `expected_returns` variable, which is only being added in `EfficientFrontier`. So I think putting it there would make sense for now.

**Comment by benlvovsky** [comment]
One thing I noticed that in the new version I have to reinitialise EfficientFrontier - get a new instance - to get the cacls right:
        `
        ef = EfficientFrontier(mu, S, weight_bounds=(options.lower_weight_bound, options.higher_weight_bound))
        ef.efficient_return(val)
`
In the previous version I just did `ef.efficient_return(val)` multiple time per new `val` and all worked. Now I have tocreate a new instance every time otherwise something goes wrong with calcs.

**Comment by robertmartin8** [comment]
@benlvovsky 

When you say "previous version", which do you mean?

Since PyPortfolioOpt moved the backend to CVXPY in `v1.0`, instantiating an `EfficientFrontier` object creates an immutable optimisation problem. Methods like `efficient_risk` add objectives/constraints to this problem, so if you call `efficient_risk` twice, you are adding two sets of constraints. 

Sometimes these play nice, if your subsequent additions are subsets of the previous constraints, but it should fail if the constraints are contradictory.

**Comment by benlvovsky** [comment]
That explains. Thank you very much
