### ISSUE TITLE
weights = ef.max_sharpe() is not working some times

### ISSUE THREAD

**Issue by kman624** [robertmartin8/PyPortfolioOpt#282]
```
/usr/local/lib/python3.6/dist-packages/pypfopt/efficient_frontier.py in max_sharpe(self, risk_free_rate)
    239         # max_sharpe requires us to make a variable transformation.
    240         # Here we treat w as the transformed variable.
--> 241         self._objective = cp.quad_form(self._w, self.cov_matrix)
    242         k = cp.Variable()
    243 

/usr/local/lib/python3.6/dist-packages/cvxpy/atoms/quad_form.py in quad_form(x, P)
    225         return x.H @ P @ x
    226     elif P.is_constant():
--> 227         return QuadForm(x, P)
    228     else:
    229         raise Exception(

/usr/local/lib/python3.6/dist-packages/cvxpy/atoms/quad_form.py in __init__(self, x, P)
     35 
     36     def __init__(self, x, P):
---> 37         super(QuadForm, self).__init__(x, P)
     38 
     39     def numeric(self, values):

/usr/local/lib/python3.6/dist-packages/cvxpy/atoms/atom.py in __init__(self, *args)
     43         # Convert raw values to Constants.
     44         self.args = [Atom.cast_to_const(arg) for arg in args]
---> 45         self.validate_arguments()
     46         self._shape = self.shape_from_args()
     47         if len(self._shape) > 2:

/usr/local/lib/python3.6/dist-packages/cvxpy/atoms/quad_form.py in validate_arguments(self)
     51             raise ValueError("Invalid dimensions for arguments.")
     52         if not self.args[1].is_hermitian():
---> 53             raise ValueError("P must be symmetric/Hermitian.")
     54 
     55     def sign_from_args(self):

ValueError: P must be symmetric/Hermitian.
```

**Comment by phschiele** [comment]
Hi @kman624,
from the trace, it looks like the covariance matrix is not symmetric. This can occur for a number of reasons, depending on how it was derived. You can try to fix it like this:
```python
cov_matrix = np.maximum( cov_matrix, cov_matrix.transpose() )
```
If that does not work, or I did not interpret the trace correctly, please post a reproducible example, if possible.

**Comment by kman624** [comment]
Thank you for that, unfortunately it did not help. I will link my dataset and I am using the Efficient Frontier Optimization. My code works for other datasets, for some reason this particular one is causing problems. I am also using Google Colab, if that makes a difference.

Also, side question. For my other datasets that work and I get the optimal portfolio out, why do only 5-10 stocks out of the 50-100 I input make it through? Especially some I know from fundamental analysis are quite good?

https://docs.google.com/spreadsheets/d/13Qvrjrq_X11tkPYsIOT7hywNZ7PaZd9UkH-3xJEDEu0/edit?usp=sharing

**Comment by phschiele** [comment]
Great if you are using Colab. That should not cause any issues by itself. Can you perhaps share the notebook or the code you use exactly? Otherwise, it is quite hard to reproduce the issue. One thing to mention is that `max_sharpe()` is generally a bit more complex compared to other optimizations, as the variables are transformed in the background. But that mostly only comes into effect when adding constraints (which you might or might not be doing).

Regarding your observation about concentration, indeed, this is a common behavior of classical mean-variance optimization.
There are different ways to deal with it, a common one is regularization, as described [in the Docs](https://pyportfolioopt.readthedocs.io/en/latest/EfficientFrontier.html#more-on-l2-regularisation).

**Comment by kman624** [comment]
I see, here is a link to the Colab. I changed the code to weights = np.array([ef.max_sharpe()]   and that sorta fixed things. I just have a new error now on the next line with one of my variables. You should be able to see it. Thank you so much for helping me with this

https://colab.research.google.com/drive/1yzEGEeJY7AJb2vU5xLJqbVxnmhZT5zCk?usp=sharing

**Comment by kman624** [comment]
Also, when I use the L2 Regularization, I get this error:

NameError                                 Traceback (most recent call last)
<ipython-input-70-1168f1b843a1> in <module>()
      1 ef = EfficientFrontier(mu, S)
----> 2 ef.add_objective(objective_functions.L2_reg, gamma=0.01)
      3 weights = ef.max_sharpe()
      4 
      5 #ef = EfficientFrontier(mu, S)

NameError: name 'objective_functions' is not defined

I do not know why, I thought it was in the package

**Comment by phschiele** [comment]
Re the first error:
Some assets in `df` only have `NaN` observations.
Try:
```python
df.dropna(how='any',inplace=True,axis=1)
```

Re your second error:
You need to import it first:
```python
from pypfopt import objective_functions
```

**Comment by kman624** [comment]
the df.drop line worked, thanks! I tried something like that earlier but I do not think I wrote it like you did

I am currently trying the objective functions solution

**Comment by kman624** [comment]
If you were wondering, out of the Nasdaq 100, the program says to spend all your money on Tesla. How funny. I suppose it makes sense based on it's price history
