### ISSUE TITLE
Using Variable Length Time Series

### ISSUE THREAD

**Issue by SoundsSerious** [robertmartin8/PyPortfolioOpt#297]
One of the features of PyPortfolioOpt is that is setup to use different length time series:
`Robust to missing data, and price-series of different lengths (e.g FB data only goes back to 2012 whereas AAPL data goes back to 1980).`

I am able to get the library to work fine when I pre-process the inputs to have all the same lengths, however when I have a pandas dataframe indexed / sorted by dates, I will get different errors based on how I'm setting up the pandas array.

What is the correct way to do this? I assume only a portion of the system may be used like this, for instance covariance must be implicit model to model. 

Method used
```
data = [pd.DataFrame({mod.name: mod.rawperf},index=mod.rawtime) for mod in p.models]
pdf = pd.concat(data,axis=1).sort_index()
```
Results in error:
```
ValueError: Workspace allocation error!
```

```
miniconda3/envs/smxenv/lib/python3.8/site-packages/pypfopt/base_optimizer.py in _solve_cvxpy_opt_problem(self)
    237                 )
    238             else:
--> 239                 self._opt.solve(verbose=self._verbose, **self._solver_options)
    240         except (TypeError, cp.DCPError) as e:
    241             raise exceptions.OptimizationError from e
    ```

**Comment by phschiele** [comment]
Hi @SoundsSerious!

Indeed, it is possible to work with different length time-series.

For example, the dataset from the screenshot below works just fine, even though there are missing values in the beginning. 
If your data frame looks similar, this should not be the cause of the issue. Please keep in mind that if the time-series are of different lengths, you implicitly assume that there was no change in the distribution of the assets for the different sub periods, which might be more or less realistic depending on your data set at hand. 

<img width="853" alt="image" src="https://user-images.githubusercontent.com/44360364/108401851-195bd980-721d-11eb-8956-4800c8172242.png">

The error `ValueError: Workspace allocation error!` looks more like you might be running out of memory. Can you run the optimisation again and monitor your memory usage?

**Comment by SoundsSerious** [comment]
@phschiele Ah thanks! Will try this when I get home.

I have 128GB of memory and my dataset size is only like ~2800, or 6 models-monthly for maybe a decade so I'm pretty doubtful I'm running out of memory. This issue describes something similar happening if there are NaN's or Zeros https://github.com/robertmartin8/PyPortfolioOpt/issues/160
