### ISSUE TITLE
i use risk model just get  5-9 stockes，i want filter 50 stockes， what can i do？

### ISSUE THREAD

**Issue by wac81** [robertmartin8/PyPortfolioOpt#301]
I use the risk model just get  5-9 stocks in 3000 stockes， I want to filter 50 -100 stockes， what can I do？

below it's my code
===========================================================
    past_rets = expected_returns.mean_historical_return(past_df)

    # past_rets = expected_returns.ema_historical_return(past_df)
    past_cov = risk_models.exp_cov(past_df)

    ef = EfficientFrontier(past_rets, past_cov)
    weights = ef.max_sharpe()

    cleaned_weights = ef.clean_weights(cutoff=1e-5, rounding=6)
    weights = cleaned_weights

    print(cleaned_weights)
    ef.portfolio_performance(verbose=True)

    latest_prices = get_latest_prices(past_df)
    print(latest_prices)

    da = DiscreteAllocation(weights, latest_prices, total_portfolio_value=portfolio_val)

    allocation, leftover = da.lp_portfolio()

**Comment by phschiele** [comment]
Hi @wac81 ,
is your question why you get only 5-9 nonzero weights from 3000 assets?
If so, please check the docs for L2 regularization as a simple way to include more assets.
If that does not suit your application, feel free to follow up.

Cheers

**Comment by wac81** [comment]
yes, as you said, i will try, thank you
