### ISSUE TITLE
Feature request: parameterized CVXPY problems

### ISSUE THREAD

**Issue by robertmartin8** [robertmartin8/PyPortfolioOpt#302]
**Is your feature request related to a problem?**

Currently, risk/return targets are included into CVXPY expressions as floats. This means that if you want to try several parameter values, you have to rebuild the entire `EfficientFrontier` object, which is quite unintuitive.

**Ideal solution**

As pointed out by @phschiele in #291, this can be avoided using `cp.Parameter()`. I'm not yet sure how best to design the API for this (or what kind of interactions it would support). In an ideal world, we would be able to do something like this:

```python
ef = EfficientFrontier(mu, S)
ef.add_constraint(...)

results = []

for target_risk in np.linspace(0.1, 0.25, 10):
    ef.efficient_risk(target_risk=0.15)
    results.append(ef.portfolio_performance())
```

**Problem**

The reason why this doesn't work outside of the box is that all of the optimisation functions (e.g `efficient_risk`, `min_volatility` also add weight constraints (checking if `market_neutral`). So if you made two calls to `efficient_risk`, even if you had logic for overwriting the current param value, there would also be an issue in which an extra set of weight constraints get added. 

In retrospect, this is probably a design flaw – perhaps it would be more logical if `market_neutral` were specified in the constructor (though this is debatable, and in any case, not backwards-compatible).

In principle, it'd be possible to check if previous weight constraints have been added, and overwrite if so, but this is hard because CVXPY constraints don't support metadata (last I checked). If we could associate a string ID with each constraint, it'd be quite easy:

```python
if not "weight_constraint" in [constr.name for constr in self._constraint]:
     # add new constraint
else:
     # don't add new constraint
```

**Proposed solution?**

We can turn all of the possible parameters into instance attributes (e.g `self.target_risk`). When you call `efficient_risk`, it will update the parameter value.

However, we are still stuck with the issue of duplicated weight bounds for each call to the method. 

At this point, I ran a quick test, and it seems that duplicate constraints don't matter?

<img width="1097" alt="Screenshot 2021-02-20 at 11 06 27" src="https://user-images.githubusercontent.com/11792905/108582050-c0e72200-736b-11eb-9418-04600eb1a2de.png">

<img width="1114" alt="Screenshot 2021-02-20 at 11 08 02" src="https://user-images.githubusercontent.com/11792905/108582080-ebd17600-736b-11eb-82a5-725eac1b54ef.png">

If this is true, then the Ideal Solution described earlier is easy to implement.

But if we insisted on not having duplicate constraints, we would have to do one of the following:

- Add some flag to not build weight constraint, e.g `efficient_risk(add_weights=False)`, but this would have to be added to every method. Lots of duplicated code.
- Build the weight constraint in the constructor – cool, but not backwards compatible.
- Add some logic that checks whether weight sum constraints have already been added. This would involve some detective work digging through the `cp.Constraint` class to see if there is some way of identifying the problems and keeping track. There are IDs in cvxpy, so it'll probably be possible, but not pleasant (e.g may involve maintaining a dict that maps semantic meaning to cvxpy ID). 

I don't like the idea of having a tonne of duplicated constraints, but if it doesn't affect the solution of the problem, then I guess it's ok?

**Comment by phschiele** [comment]
@robertmartin8 going one step back, what is the intended use case for the `EfficientFrontier` class?
What I mean is should calling multiple different optimizations on a single object should be supported?
Currently, the constraints are always appended to, which can lead to unintuitive behavior:
```python
# case A
ef.min_volatility()
ef.efficient_risk(0.17) <- works

# case B
ef.min_volatility()
ef.efficient_return(0.21)
ef.efficient_risk(0.17) <- fails
```

I think a more robust way to implement it would be:
- Whenever an optimization on the object is first called, this is stored within the project and the optimization problem is set up in a parametrized way (if necessary). 
- For subsequent calls, one first checks if the same function was called, if not, fail with an informative error message. If it is the same function again (perhaps with a different parameter value), skip the objective/constraint setup and solve the problem again.

I am not quite sure how one would incorporate such logic with additional / custom objectives. Would also be a quite invasive change. What are your thoughts on this in general? 

There are also other ways to enforce this (freezing constraints/objectives when the solve function is first called, ...).

**Comment by robertmartin8** [comment]
@phschiele It was initially intended to be something like a wrapper for a single `cp.Problem` (though in the early days it was a scipy backend). It was designed for the basic user, e.g someone who knows that they want to optimise a `max_sharpe` portfolio with a certain set of constraints.

Just like on cvxpy, if you were going to solve a different optimisation problem, you'd create a brand new `cp.Problem` (rather than rewriting its constraints etc). 

So for the most part, I'm against `case B`. But I recognise that the current design does not encourage users to build many objects, which could make both plotting and backtesting quite inefficient.

**Comment by phschiele** [comment]
@robertmartin8 from that description, it seems like it would make sense to promote (/enforce?) a form of immutability on the objects. 
I think not only can the current state lead to outright failures, but also to more subtle unexpected behavior, which is not ideal.
From my point of view, this can be tackled in a variety of ways. If you think it makes sense, I could try to include such a change. The requirements would be backward compatibility (except for the problematic use-cases, of course) and keeping the scope of the change somewhat manageable.

**Comment by robertmartin8** [comment]
> I could try to include such a change

Are you referring to the `cp.Parameter` aspect, or the architecture of `EfficientFrontier`? What solution do you have in mind?

**Comment by phschiele** [comment]
I was thinking perhaps one could add an attribute to the class which records the last optimization type (e.g.  `efficient_return`, ...).
If the next call is to the same function, skip the constraint building and just update the Parameter value.
If it is to a different function, either fail, or warn.
I guess this would be a minimal invasive change. One could of course also keep the `cvxpy.Problem` around and check for its existence on subsequent calls, therefore automatically having the immutability from the cvxpy side of things. 
Just spinning around some ideas, I am not yet sure what would be an ideal solution. Thus, I wanted to try it out by just updating one or two functions in a PR and check the pros and cons.

**Comment by robertmartin8** [comment]
>I wanted to try it out by just updating one or two functions in a PR and check the pros and cons.

Good idea. This seems like quite a tough problem, so I don't want to rush into anything.
