### ISSUE TITLE
Binder yfinance

### ISSUE THREAD

**Issue by robertmartin8** [robertmartin8/PyPortfolioOpt#303]
`yfinance` is not available in the binder notebooks. I added it to the `pyproject.toml` as a dev dependency, and also added `pip install` in the `Dockerfile`, but I keep getting `ModuleNotFoundError`.

It seems that binder is only looking at `requirements.txt` when it sets up the environment, so I may have to add `yfinance` to the requirements (either that or make all of the notebooks read from local data).

@phschiele any thoughts?

**Comment by phschiele** [comment]
First of all, it is correct that binder only looks at the `requirements.txt` file. Sadly, one cannot set different priorities such that it would read from a more robust format.

So I see three solutions:
- add it to requirements.txt
- rewrite all notebooks to use local data -> I think loading the prices directly from `yfinance` makes the notebook always feel "up to date", which I like
- some hack like `! pip install yfinance` in the notebooks

Personally, I would go for the first one. I guess for the time being, `requirements.txt` will always be a subset of main, dev, and optional dependencies, which is fine for this "fallback" file.
