### ISSUE TITLE
Is it possible to create value/growth equality constraint? 

### ISSUE THREAD

**Issue by x829901** [robertmartin8/PyPortfolioOpt#306]
**What are you trying to do?**
In the following portfolio optimization, I'd like to add a constraint so that there are equal amounts of value and growth. So, if there is 30% allocated to value, there should also be 30% allocated to growth, and vice-versa. How would I go about doing this? Thanks! 

```
style_mapper = {
    "SPY": "blend",
    "VUG": "growth",
    "VTV": "value"
}

style_lower = {
    "blend": 0.5,
    "growth": 0.5,
    "value": 0.5
}

style_upper = {
    "blend": 0.5,
    "growth": 0.5,
    "value": 0.5
}

mu = expected_returns.capm_return(prices)
S = risk_models.CovarianceShrinkage(prices).ledoit_wolf()

ef = EfficientFrontier(mu, S)  # weight_bounds automatically set to (0, 1)
ef.add_sector_constraints(style_mapper, style_lower, style_upper)

ef.efficient_risk(0.2)
weights = ef.clean_weights()
```

**Comment by robertmartin8** [comment]
Hi @x829901,

One way you could do this is to explicitly add the constraint

```python
value_indices = [1, 0, 0, 1 ..., 0, 0, 1]  # 1 if value, 0 if not
growth_indices = [0, 1, 1, 0 ..., 1, 1, 0]  # 1 if growth, 0 if not

ef.add_constraint(lambda w: cp.sum(w[value_indices]) 
ef.add_constraint(lambda w: w @ growth_indices == w @ value_indices)
```

Here's an example using the data from MVO cookbook

```python
growth_indices = [1 if i in {"AMZN", "TSLA", "MSFT"} else 0 for i in ef.tickers]
value_indices = [1 if i in {"GILD", "F", "XOM", "LUV"} else 0 for i in ef.tickers]

ef = EfficientFrontier(mu, S) 
ef.add_constraint(lambda w: w @ growth_indices == w @ value_indices)
w = ef.min_volatility()
print(w["AMZN"] + w["TSLA"] + w["MSFT"])  # = 0.1404
print(w["GILD"] + w["F"] + w["XOM"] + w["LUV"]) # = 0.1404
```

Hope this helps!

**Comment by x829901** [comment]
> Hi @x829901,
> 
> One way you could do this is to explicitly add the constraint
> 
> ```python
> value_indices = [1, 0, 0, 1 ..., 0, 0, 1]  # 1 if value, 0 if not
> growth_indices = [0, 1, 1, 0 ..., 1, 1, 0]  # 1 if growth, 0 if not
> 
> ef.add_constraint(lambda w: w @ growth_indices == w @ value_indices)
> ```
> 
> Here's an example using the data from MVO cookbook
> 
> ```python
> growth_indices = [1 if i in {"AMZN", "TSLA", "MSFT"} else 0 for i in ef.tickers]
> value_indices = [1 if i in {"GILD", "F", "XOM", "LUV"} else 0 for i in ef.tickers]
> 
> ef = EfficientFrontier(mu, S) 
> ef.add_constraint(lambda w: w @ growth_indices == w @ value_indices)
> w = ef.min_volatility()
> print(w["AMZN"] + w["TSLA"] + w["MSFT"])  # = 0.1404
> print(w["GILD"] + w["F"] + w["XOM"] + w["LUV"]) # = 0.1404
> ```
> 
> Hope this helps!

Thanks, this worked.
