### ISSUE TITLE
How to get the entire set of weights for the efficient frontier portfolio 

### ISSUE THREAD

**Issue by papisagre** [robertmartin8/PyPortfolioOpt#307]
Im trying to obtain the entire set of weights for the efficient frontier but im only obtaining the max sharpe weights ( ef.max_sharpe())

and need the whole set.

does someone have this same issue, or some one have already figured it out?

thanks, im looking forward to it!

**Comment by phschiele** [comment]
Hi @papisagre,

perhaps something like this:

```python
import copy
from pypfopt.plotting import _ef_default_returns_range

ef = EfficientFrontier(mu,Sigma)
return_range = _ef_default_returns_range(ef, 100)

def get_single_target_weights(target_return, ef):
    ef_i = copy.deepcopy(ef)
    ef_i.efficient_return(target_return)
    return ef_i.weights
frontier_weights = [get_single_target_weights(target_return, ef) for target_return in return_range]
```

I think `_ef_default_returns_range` could also be useful outside of the plotting module, e.g. for application like yours or some constrained optimization where `max_sharpe()` does not work directly.

**Comment by robertmartin8** [comment]
@papisagre if you don't have any special constraints, you can use [`CLA`](https://pyportfolioopt.readthedocs.io/en/latest/OtherOptimizers.html#the-critical-line-algorithm):

```python
from pypfopt import CLA

cla = CLA(mu, S)
mu_list, sigma_list, weight_list = cla.efficient_frontier(points=100)
```


However, @phschiele it'd be cool to eventually support this from `EfficientFrontier` (somewhat related to #302). For example, I want to be able to make transition maps, which are basically plots of how the weight varies with risk:

![](https://systematicinvestor.files.wordpress.com/2011/10/plot2-small4.png)

**Comment by papisagre** [comment]
> @papisagre if you don't have any special constraints, you can use [`CLA`](https://pyportfolioopt.readthedocs.io/en/latest/OtherOptimizers.html#the-critical-line-algorithm):
> 
> ```python
> from pypfopt import CLA
> 
> cla = CLA(mu, S)
> mu_list, sigma_list, weight_list = cla.efficient_frontier(points=100)
> ```
> 
> However, @phschiele it'd be cool to eventually support this from `EfficientFrontier` (somewhat related to #302). For example, I want to be able to make transition maps, which are basically plots of how the weight varies with risk:
> 
> ![](https://camo.githubusercontent.com/79c3d2e931f6980756f3339a2978c5146184ff6ad21c5e076b4df480104b7506/68747470733a2f2f73797374656d61746963696e766573746f722e66696c65732e776f726470726573732e636f6d2f323031312f31302f706c6f74322d736d616c6c342e706e67)

**Comment by papisagre** [comment]
> > @papisagre if you don't have any special constraints, you can use [`CLA`](https://pyportfolioopt.readthedocs.io/en/latest/OtherOptimizers.html#the-critical-line-algorithm):
> > ```python
> > from pypfopt import CLA
> > 
> > cla = CLA(mu, S)
> > mu_list, sigma_list, weight_list = cla.efficient_frontier(points=100)
> > ```
> > 
> > 
> > However, @phschiele it'd be cool to eventually support this from `EfficientFrontier` (somewhat related to #302). For example, I want to be able to make transition maps, which are basically plots of how the weight varies with risk:
> > ![](https://camo.githubusercontent.com/79c3d2e931f6980756f3339a2978c5146184ff6ad21c5e076b4df480104b7506/68747470733a2f2f73797374656d61746963696e766573746f722e66696c65732e776f726470726573732e636f6d2f323031312f31302f706c6f74322d736d616c6c342e706e67)

**Comment by papisagre** [comment]
> @papisagre if you don't have any special constraints, you can use [`CLA`](https://pyportfolioopt.readthedocs.io/en/latest/OtherOptimizers.html#the-critical-line-algorithm):
> 
> ```python
> from pypfopt import CLA
> 
> cla = CLA(mu, S)
> mu_list, sigma_list, weight_list = cla.efficient_frontier(points=100)
> ```
> 
> However, @phschiele it'd be cool to eventually support this from `EfficientFrontier` (somewhat related to #302). For example, I want to be able to make transition maps, which are basically plots of how the weight varies with risk:
> 
> ![](https://camo.githubusercontent.com/79c3d2e931f6980756f3339a2978c5146184ff6ad21c5e076b4df480104b7506/68747470733a2f2f73797374656d61746963696e766573746f722e66696c65732e776f726470726573732e636f6d2f323031312f31302f706c6f74322d736d616c6c342e706e67)

hi @robertmartin8, actually this transition maps are really useful, but i do have special constraints for my set of assets. is it possible to do map the transition weights with special constraints?

thanks for your help

**Comment by papisagre** [comment]
> Hi @papisagre,
> 
> perhaps something like this:
> 
> ```python
> import copy
> from pypfopt.plotting import _ef_default_returns_range
> 
> ef = EfficientFrontier(mu,Sigma)
> return_range = _ef_default_returns_range(ef, 100)
> 
> def get_single_target_weights(target_return, ef):
>     ef_i = copy.deepcopy(ef)
>     ef_i.efficient_return(target_return)
>     return ef_i.weights
> frontier_weights = [get_single_target_weights(target_return, ef) for target_return in return_range]
> ```
> 
> I think `_ef_default_returns_range` could also be useful outside of the plotting module, e.g. for application like yours or some constrained optimization where `max_sharpe()` does not work directly.

thanks @phschiele i was able to retrieve the set of weights for my efficient frontier. even though, i agree that it would be very useful to map the transition weights from `EfficientFrontier.`

**Comment by pebennett** [comment]
Hi there, thanks for this. So, how do I get the what robertmartin8 has defined above as Mu_list & sigma_list when I have constraints and have to use EfficientFrontier? Thanks

**Comment by robertmartin8** [comment]
@pebennett 

A simple modification of @phschiele's code should work:

```python
import copy
from pypfopt.plotting import _ef_default_returns_range

ef = EfficientFrontier(mu,Sigma)
return_range = _ef_default_returns_range(ef, 100)

def get_single_target_metrics(target_return, ef):
    ef_i = copy.deepcopy(ef)
    ef_i.efficient_return(target_return)
    return ef_i.portfolio_performance()
frontier_metrics = [get_single_target_metrics(target_return, ef) for target_return in return_range]
```

`frontier_metrics` will then be a list of (mu, sigma, sharpe) tuples, which you can unpack:

```python
mu_list = [i[0] for i in frontier_metrics]
```

**Comment by pebennett** [comment]
Thank you very much for this. I was able to get it to work and was able to get it to work with a constrained enabled…I think. The resulting lists were worrisome because the mu_list had 100 elements and was decreasing while the sigma_list had 52 elements and was increasing.  After cutting the 100 back to 52 and inverting one of the lists, the resulting efficient frontier was not very intuitive looking, as in the constrained efficient frontier below.  Any thoughts?  Thanks again.

***@***.***

Phil

**Comment by robertmartin8** [comment]
Without seeing your code it's a little difficult to understand what might be causing that.

**Comment by pebennett** [comment]
The code that’s producing that is as follows. The risk/return diagram is below that. The asset classes look ok.

Any help you could provide would be greatly appreciated as I’m pretty much at my wits end.

Thanks,
Phil

***@***.***




























***@***.***

**Comment by phschiele** [comment]
@pebennett The code is not visible in your comment. It appears to be an issue with replying via E-Mail, perhaps it's best to add the code directly on GitHub.

**Comment by pebennett** [comment]
The code that’s producing that is as follows. Had to paste the code in directly as I couldn't paste an image. The` risk/return diagram is below that. The asset classes look ok.

Any help you could provide would be greatly appreciated as I’m pretty much at my wits end.  Thanks phschiele for reaching out.

 ef_constr = EfficientFrontier(mu_hist, cov_hist, weight_bounds=(0,1))
    #ef_constr.add_sector_constraints(sector_mapper, sector_lower, sector_upper)
    ef_constr.add_sector_constraints(sector_mapper, current_lower, current_upper)
    target_return=0.2
    return_range = _ef_default_returns_range(ef_constr, 52)
def get_single_target_metrics(target_return, ef_constr):
        ef_i = copy.deepcopy(ef_constr)
        ef_i.efficient_return(target_return)
        return ef_i.portfolio_performance()
    frontier_metrics = [get_single_target_metrics(target_return, ef_constr) for target_return in return_range]

    mu_list = [i[0] for i in frontier_metrics]
    mu_sigma = [i[0] for i in frontier_metrics]

    df_mu_list =pd.DataFrame(mu_list)
    df_sigma_list =pd.DataFrame(sigma_list)
    print(),print('mu_list: '),print(df_mu_list),print(df_mu_list.shape),print()
    print(),print('sigma_list: '),print(df_sigma_list),print(df_sigma_list.shape),print()
    mu_list_path_file =  os.path.join(data_output_path,'Constrained_Mu_List.csv')
    print(mu_list_path_file)
    df_mu_list.to_csv(mu_list_path_file)
    sigma_list_path_file =  os.path.join(data_output_path,'Constrained_Sigma_List.csv')
    print(sigma_list_path_file)
    df_sigma_list.to_csv(sigma_list_path_file)

    print(),print()
    ef_constr.portfolio_performance(verbose=True)

Thanks,
Phil

**Comment by pebennett** [comment]
Thanks for this.

**Comment by robertmartin8** [comment]
You should change the lines to:

```python
mu_list = [i[0] for i in frontier_metrics]
sigma_list = [i[1] for i in frontier_metrics]
```

Currently both your lists are pointing to the same thing.

Probably best to reply on github directly – your mail client doesn't seem to get on well with gh!

**Comment by pebennett** [comment]
Robert, thanks very much for this. A small correction but very important.

I have more checking to do, but initial run-throughs are looking ok, but some are a little unintuitive. One thing that seems to still be happening with this routine that doesn't happen with the CLA-based, no constraints routine is that the mu_list is increasing while the sigma_list is decreasing. btw, it is very convenient that the volatilities from both routines are the same, which makes charting much easier.

For the sharpe_list, is the code 'sharpe_list = [i[2] for i in frontier_metrics]'?

Thanks again, VERY much.
Phil

**Comment by robertmartin8** [comment]
>it is very convenient that the volatilities from both routines are the same, which makes charting much easier. 

You should be able to modify the above code to use a particular range of volatilities as follows:

```python
risk_range = np.linspace(0.1, 0.4, 10)  # define your risk range
    
def get_single_target_metrics(target_risk, ef_constr):
        ef_i = copy.deepcopy(ef_constr)
        ef_i.efficient_risk(target_risk)
        return ef_i.portfolio_performance()

frontier_metrics = [get_single_target_metrics(target_risk, ef_constr) for target_risk in risk_range]
```

> For the sharpe_list, is the code 'sharpe_list = [i[2] for i in frontier_metrics]'?

Yup!

**Comment by pebennett** [comment]
Thanks Robert. An issue I'm having is with the length of the lists. I'm looking at five specific examples and in three of them the mu_list & sigma_list are the same list, however, in the other two the lists are of different lengths (e.g. one has 38  and the other 52), making them useless. Any way to fix this?

Thanks,
Phil

**Comment by robertmartin8** [comment]
The logic of how the above scripts work is pretty simple: for a range of parameters (be they volatilities or risks), optimise a portfolio using that parameter as a constraint. 

The only caveat is that due to how PyPortfolioOpt is designed, you need to re-instantiate the object at each point (though we're currently trying to figure out a better way of doing it).

So for example you could do:

```python
ef1 = EfficientFrontier(mu, S)
ef1.efficient_risk(0.2)
mu1, std1, _ = ef1.portfolio_performance()

ef2 = EfficientFrontier(mu, S)
ef2.efficient_risk(0.25)
mu2, std2, _ = ef2.portfolio_performance()

ef3 = ...
```

The script in the previous comment is simply a way of looping through this so you don't have to manually copy the above code 100 times (or however many risk increments you want to do).

In order to debug, I suggest you create a for loop iterating over your parameter range and in each loop print the parameter and mu, std. This will allow you to figure out which parameters are causing a "missing" entry, though I think it's more likely that there is a mistake with how the loop has been defined.

This thread is starting to diverge a bit from the original issue, so if there are still problems it's worth opening a new issue – but please provide a [minimum reproducible example](https://stackoverflow.com/help/minimal-reproducible-example), highlighting the exact portion of the code that is causing issues.

**Comment by pebennett** [comment]
Sorry, been tied up with a different deadline!!! ;-)

First of all, thanks for all your help with this. I have been laser-focused on getting the data to construct both unconstrained and constrained efficient frontiers. If you recall, I was getting different numbers of elements for the 'mu_list' than the 'sigma_list' for some cases when I was using 

mu_list = [i[0] for i in frontier_metrics]
sigma_list = [i[1] for i in frontier_metrics]

I've now resolved this issue by  putting the return, volatility and Sharpe into a dataframe, as below. Since doing that, I have had no mis-matched counts! ;-) 

Thanks again.

df_fm_unconstr = pd.DataFrame(frontier_metrics,columns = ['Return','Volatility','Sharpe'])

**Comment by robertmartin8** [comment]
Glad to hear it worked!

**Comment by pebennett** [comment]
Hi Robert,

PyPortfolioOpt has been working pretty well for me at home, with one question I will ask separately. However, I have been trying to get it working on my work computer and ran into a problem. In particular, I was able to install it ok with ‘pip install pyportfolioopt’ however, when I tried to import it as ‘import pypfopt’, ‘from pypfopt import risk_models’ or any similar import, I get the error ‘ImportError: cannot import name ‘IncompatibleFrequency’. I’ve gone through almost all the code on your github site and have not even been able to locate anything with that name.  Any thoughts or insights?

Thanks,
Phil

**Comment by robertmartin8** [comment]
Hi Phil, that’s a strange issue. It seems to be a pandas issue but I’m not sure why exactly it’s happening:

https://github.com/pandas-dev/pandas/issues/39113

**Comment by realmart** [comment]
> Hi @papisagre,
> 
> perhaps something like this:
> 
> ```python
> import copy
> from pypfopt.plotting import _ef_default_returns_range
> 
> ef = EfficientFrontier(mu,Sigma)
> return_range = _ef_default_returns_range(ef, 100)
> 
> def get_single_target_weights(target_return, ef):
>     ef_i = copy.deepcopy(ef)
>     ef_i.efficient_return(target_return)
>     return ef_i.weights
> frontier_weights = [get_single_target_weights(target_return, ef) for target_return in return_range]
> ```
> 
> I think `_ef_default_returns_range` could also be useful outside of the plotting module, e.g. for application like yours or some constrained optimization where `max_sharpe()` does not work directly.

This did not work for me. The error was"target_return should be a positive float". 
At the lower end of my efficient frontier, there were portfolios with a negative return expectation. I had to remove those portfolios to make it work. 

How would I have to adjust the code to get the weights of portfolios with negative return expectations?

**Comment by robertmartin8** [comment]
@realmart the library doesn't support having a negative return target using the built-in method. In principle you could implement this as follows:

- Add your negative return constraint using `ef.add_constraint()`
- Optimise for minimum risk using `ef.convex_objective()`

However, this seems like a weird edge case – why would one want to optimise for negative returns?
