### ISSUE TITLE
typo in Quick example section?

### ISSUE THREAD

**Issue by omendezmorales** [robertmartin8/PyPortfolioOpt#319]
**What are you trying to do?**
In the [quick example](https://github.com/robertmartin8/PyPortfolioOpt#a-quick-example) section, calling 
`da = DiscreteAllocation(cleaned_weights, latest_prices, total_portfolio_value=10000) `
 retrieves
"NameError: name 'weights' is not defined"
**What have you tried?**
I believe given the variable used previously, it should be `cleaned_weights`?

**What data are you using?**
I am using the following dataset ("tests/resources/stock_prices.csv") as provided in the repo, and executing the sample code in a _ipython_ environment

Thanks for your help.

**Comment by phschiele** [comment]
Good catch, indeed, using `cleaned_weights` works.
@robertmartin8, I have changed it here: #320

**Comment by robertmartin8** [comment]
Cheers, fixed!
