### ISSUE TITLE
5-Hierarchical-Risk-Parity.ipynb

### ISSUE THREAD

**Issue by waudinio27** [robertmartin8/PyPortfolioOpt#321]
Dear Robert Martin!

I want to use the HRP model from the cookbook to generate a Long - Short portfolio. It is intended to be used with Forex Data as an Asset class, and to rebalance it every week or two. I want to generate a portfolio where the HRP selects the Ratio of Long and Short positions and also the corresponding weights. The data is downloaded from yahoo with daily data in the same way as it is shown in the example. I use 15 pairs so far for my trials.

I think that - ef = EfficientFrontier(mu, S, weight_bounds=(-1,1)) has to be put somewhere - like it is stated in the User Guide. But as a beginner I struggle to find where this is needed exactly

Could you publish a cookbook with these requirements - I would appreciate it a lot

Thank you and best regards

**Comment by robertmartin8** [comment]
Hi @waudinio27,

Unfortunately HRP only supports long-only portfolios for the time being. 

Best,
Robert
