### ISSUE TITLE
Shrunk covariance matrix - altering the delta / calc the delta

### ISSUE THREAD

**Issue by Seanhenney** [robertmartin8/PyPortfolioOpt#323]
Hi Rob,

I'm just trying to figure out a way of altering the delta when using your risk_model functions. Is this functionality possible via your code? i.e.  pypfopt.risk_models.CovarianceShrinkage(prices, returns_data=False, frequency=252, **delta=0.5**) 

In your docs, you recommend using the Ledoit and Wolf approach to calculating the delta, grateful if you can point to the paper or code for estimating the optimal shrinkage delta?

Best,
SH

**Comment by robertmartin8** [comment]
Hi @Seanhenney,

Thanks for the question! If you want to manually alter delta, you can do the following:

```python
cs = CovarianceShrinkage(prices)
cov = cs.shrunk_covariance(delta=0.5)
```

The [docs](https://pyportfolioopt.readthedocs.io/en/latest/RiskModels.html#shrinkage-estimators) contain several references.

Let me know if that helps!
Robert
