### ISSUE TITLE
Feature request: [CLA consistency of inputs]

### ISSUE THREAD

**Issue by msh855** [robertmartin8/PyPortfolioOpt#326]
I think is good to keep some consistency with the inputs in optimizers. For example, the CLA optimizer needs np arrays as inputs while others can take pandas data frames. I think would help users to smooth their pipelines. For example, if one wants to estimate a covariance matrix from Risk models the output is a pandas dataframe. CLA would not accept this as input unless converted to an array.

**Comment by robertmartin8** [comment]
@msh855 

CLA works with dataframes – I've just tested the below

```python
import yfinance as yf
import matplotlib.pyplot as plt
import pandas as pd
from pypfopt import risk_models, expected_returns, CLA
import numpy as np

tickers = ["MSFT", "AMZN", "KO", "MA", "COST"]
prices = yf.download(tickers, period="max")["Adj Close"].dropna(how="all")

mu = expected_returns.mean_historical_return(prices)
S = risk_models.sample_cov(prices)

cla = CLA(mu, S)
cla.max_sharpe()


> OrderedDict([('AMZN', 0.11612112215328058),
             ('COST', 1.4675421303524718e-17),
             ('KO', 0.13420360217688765),
             ('MA', 0.5242791383646173),
             ('MSFT', 0.22539613730521454)])
```



Best,
Robert

**Comment by msh855** [comment]
Yes, my mistake sorry. The problem was that I passed a vector of returns, not the mean returns.
