### ISSUE TITLE
Help regarding the calculation of Sharpe ratio in portfolio optimization

### ISSUE THREAD

**Issue by Shauryasingh741** [robertmartin8/PyPortfolioOpt#329]
Hey, I was having trouble in calculating the Sharpe ratio in python and want to know that I have calculated it correct and also just need your assistance in creating risk model using my values.

https://colab.research.google.com/drive/1N8LKjyqpdgQ8ER8FXRlX1fykPavMl-LO#scrollTo=byAbaw9CFZDQ&line=1&uniqifier=1

**Comment by robertmartin8** [comment]
Hi @Shauryasingh741,

I can't access the notebook. Could you copy-paste the relevant parts into github, using triple backticks ``` to make a codeblock?

Also can you describe exactly what trouble you're having calculating the Sharpe ratio?

Best,
Robert

**Comment by Shauryasingh741** [comment]
Ok @Robert Andrew Martin ***@***.***>

**Comment by robertmartin8** [comment]
I'm closing this as there is no information about the issue – please reopen if needed!
