### ISSUE TITLE
CLA().max_sharpe() throws IndexError with specific constraints

### ISSUE THREAD

**Issue by kingwongf** [robertmartin8/PyPortfolioOpt#334]
**Describe the bug**

The code throws `IndexError: list index out of range` when passing a specific set of covariances and expected returns to `CLA().max_sharpe()`

**Expected behavior**
It should gives an orderDict of weights

**Code sample**

```
t_cov = np.array([[1.99767457e-07, 1.35042700e-07, 6.50018304e-07],
 [1.35042700e-07, 9.12887968e-08, 4.39412045e-07],
 [6.50018304e-07, 4.39412045e-07, 2.11507821e-06]])

t_ret = np.array([-5.77014524e-05, -3.90061527e-05, -1.87753305e-04])

CLA(t_ret, t_cov, weight_bounds=(-5, 5)).max_sharpe().values()

Traceback (most recent call last):
  File "../python3.7/site-packages/IPython/core/interactiveshell.py", line 3326, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-214-92402b54e72e>", line 6, in <module>
    CLA(t_ret, t_cov, weight_bounds=(-5, 5)).max_sharpe().values()
  File "../python3.7/site-packages/pypfopt/cla.py", line 381, in max_sharpe
    self._solve()
  File "../python3.7/site-packages/pypfopt/cla.py", line 371, in _solve
    self._purge_excess()
  File "../python3.7/site-packages/pypfopt/cla.py", line 244, in _purge_excess
    w = self.w[i]
IndexError: list index out of range

```

**Operating system, python version, PyPortfolioOpt version**
 MacOS 10.15.7, python 3.7, PyPortfolioOpt 1.2.7

**Additional context**
It works with a different set of constraints. (-1,1). But the bug doesn't reflect a different constraint that should be used nor why `i` is larger than the length of `self.w`

**Comment by phschiele** [comment]
Couldn't look into it in detail yet, but looks like the error is already way before `_purge_excess()`. Already in the second iteration, the weights do no longer add up to one:
![image](https://user-images.githubusercontent.com/44360364/118358475-3899a700-b57f-11eb-93b4-419137971efd.png)
The `lambdas` also should be decreasing, but as you can see, this is not the case.
`[None, 0.041162072376941666, 0.07237455320192332, 0.07237449427937284, 0.07237449427937284, 0.07237446321603254, 0.07237446321603254, 0]`.

**Comment by phschiele** [comment]
Looking at 
```python
np.linalg.det(t_cov)
>>> 2.702501290077487e-38
```
it becomes clear that the covariance matrix is almost singular, leading to numerical issues.
I do not have the context to what you are trying to achieve (the covariances are very small and all expected returns are negative), but perhaps adding something like `t_cov = t_cov + np.eye(t_cov.shape[0]) * 1e-9)` would help.
You can also use the `EfficientFrontier` class, but this too fails (with an "infeasible" error) if `all(expected_returns - risk_free < 0)`. I think this is actually known, so perhaps we could add a check with a more informative error message here.
cc: @robertmartin8

**Comment by kingwongf** [comment]
Thanks! Will adjust the cov accordingly.
