### ISSUE TITLE
Labelling Assets and Efficient Frontier

### ISSUE THREAD

**Issue by SantoshKBehera** [robertmartin8/PyPortfolioOpt#336]
**Is your feature request related to a problem?**
I am trying to plot efficient frontiers over several periods to study the contraction/ expansion of the frontier. While several frontier are plotted, identifying which EF with period is not possible. 

**Describe the feature you'd like**
EFs should be labelled based on series.
Assets should be labelled, may be limited to a certain size.
With multiple EFs, repetion of Assets , optimal seems redundant.

**Additional context**
![Efficient Frontier](https://user-images.githubusercontent.com/82929836/118408610-fcac3200-b6a3-11eb-9435-9c39af7c4a4f.JPG)

**Comment by robertmartin8** [comment]
@SantoshKBehera Thanks for the feature suggestion.

I wonder if there is a matplotlib fix which can allow you to customise the legend on an existing ax. Have you had a look through the legend docs [here](https://matplotlib.org/stable/api/_as_gen/matplotlib.axes.Axes.legend.html)?

**Comment by robertmartin8** [comment]
Closing for now – please reopen if needed.
