### ISSUE TITLE
could not install de pyportfolioopt  

### ISSUE THREAD

**Issue by maximus8dds** [robertmartin8/PyPortfolioOpt#339]
i already try to download the visual studio installer and activate the  C++ complement.  thats allows me to download de package however when I try to import it does not read it and this error appears  ------ModuleNotFoundError: No module named 'PyPortfolioOpt'----

**Comment by robertmartin8** [comment]
Hi @maximus8dds,

What OS are you on, python version etc.

Are you able to `pip install cvxpy`? (One of PyPortfolioOpt's dependencies).

**Comment by peter-stuart-turner** [comment]
I am also hitting a wall (cvxpy failing). I downloaded this package previously but for some reason it is not working now, perhaps it is that I am using python 3.8 this time..


Extract of the stack trace:

lnclude/python3.8/Python.h:25:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:64:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:71:
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_types.h:43:9: error: unknown type name '__uint32_t'; did you mean '__uint128_t'?
    typedef __uint32_t      __darwin_wctype_t;
            ^
    note: '__uint128_t' declared here
    In file included from scs/linsys/external/qdldl/qdldl.c:1:
    In file included from scs/linsys/external/qdldl/qdldl.h:5:
    In file included from scs/linsys/external/qdldl/qdldl_types.h:4:
    In file included from scs/include/glbopts.h:52:
    In file included from /Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/include/python3.8/Python.h:25:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/stdio.h:64:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/_stdio.h:75:
    In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/sys/_types/_va_list.h:31:
    /Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/usr/include/machine/types.h:37:2: error: architecture not supported
    #error architecture not supported

**Comment by peter-stuart-turner** [comment]
For me it was an issue with Catalina's system Python - I am using python 3.8 from pyenv python (version manager) now and it seems to work fine.

**Comment by robertmartin8** [comment]
@peter-stuart-turner I'm glad to hear that you've gotten it to work! Pyenv is a great tool.
