### ISSUE TITLE
Can't install on Windows Anaconda

### ISSUE THREAD

**Issue by Jeff-kelly-104** [robertmartin8/PyPortfolioOpt#340]
Hi,

I cannot use any of the functions from pypfopt. 

I installed C++ and was able to run the "pip install pyportfolioopt" (see below)

![image](https://user-images.githubusercontent.com/84777724/119486055-bc0d8200-bd4f-11eb-8da4-276ed649cb39.png)

However, I must be missing a step as I get the error below when I try to run pyfopt. 

![image](https://user-images.githubusercontent.com/84777724/119486478-2f16f880-bd50-11eb-80ad-3f7bb59031dc.png)

Any help would be amazing. Thanks!

**Comment by Jeff-kelly-104** [comment]
Solved, apologies!

**Comment by ANDREWNGT** [comment]
Hi, I'm facing the same issue. Could you please write up how you solved this?
