### ISSUE TITLE
Feature request: Portfolio optimisation with Smart Sharpe Ratio

### ISSUE THREAD

**Issue by galarosa** [robertmartin8/PyPortfolioOpt#344]
In the second part of a paper of KeyQuant folks, is described the "Smart" Sharpe Ratio as an alternative to the classical Sharpe ratio for the estimation of portfolio performance, and maximising "Serenity" ( same paper, described in Part 1 ).

![image](https://user-images.githubusercontent.com/1311712/121053334-863eb380-c7bb-11eb-8cc6-f85b94172765.png)

where &rho;<sub>i</sub> is the autocorrelation of the portfolio returns at lag i, further simplified at pag 48 of the paper, by applying an AR(1) filter, to &rho;<sup>i</sup> where &rho; is the autocorrelation at lag 1.

I was wondering if it is possible to implement Smart Sharpe optimisation in PyPortfolioOpt.

The link to the paper is here:
[Part 1](https://www.keyquant.com/Download/GetFile?Filename=%5CPublications%5CKeyQuant_WhitePaper_APT_Part1.pdf)
[Part 2](https://www.keyquant.com/Download/GetFile?Filename=%5CPublications%5CKeyQuant_WhitePaper_APT_Part2.pdf)

**Comment by robertmartin8** [comment]
Hi @galarosa,

I'm doubtful that the smart Sharpe ratio can be formulated as a convex problem – simply because even the standard max sharpe portfolio is quite tricky to make convex.

Your best bet here is to define a custom objective function and pass it to `ef.nonconvex_objective`

Cheers,
Robert
