### ISSUE TITLE
Negative weights from max_sharpe function

### ISSUE THREAD

**Issue by Younghoon-Lee** [robertmartin8/PyPortfolioOpt#347]
**What are you trying to do?**

Sorry for my poor English in advance.(Currently, I am university student from South Korea)
I am trying to get optimal portfolio with Korean assets.
Here is my example code for better explanation

```
mu = expected_returns.mean_historical_return(df)
S = risk_models.CovarianceShrinkage(df).ledoit_wolf()
ef = EfficientFrontier(mu, S, weight_bounds=(0,1))
weights = ef.max_sharpe()
print(weights)
```
df is stock price dataframe.
And for the output, which is weights, I am keep getting some negative weights.
I don't get it why I am getting negative weights despite setting boundaries(weight_bounds=(0,1))
Plus, it doesn't even raise error.

**What have you tried?**

I applied another efficientFrontier method, 'efficient_return' and it works fine.
`ef.efficient_return(0.2)`

.

**Comment by robertmartin8** [comment]
Very strange. Are they big negative weights? Or near zero (in which case it might just be a floating point thing)

**Comment by Younghoon-Lee** [comment]
thank you for rapid reply.

I will give you more detailed explanation about output of my expected return and risk model.

```
mu = expected_returns.mean_historical_return(df)
>>>
252670.KS   -0.559241
091220.KS    0.046982
114800.KS   -0.310602
251340.KS   -0.325860
233740.KS    0.502901
dtype: float64

S = risk_models.CovarianceShrinkage(df).ledoit_wolf()
>>>
           252670.KS  091220.KS  114800.KS  251340.KS  233740.KS
252670.KS   0.281960  -0.129378   0.139624   0.137063  -0.262158
091220.KS  -0.129378   0.125743  -0.065309  -0.055681   0.105773
114800.KS   0.139624  -0.065309   0.077408   0.069616  -0.133249
251340.KS   0.137063  -0.055681   0.069616   0.113887  -0.205718
233740.KS  -0.262158   0.105773  -0.133249  -0.205718   0.401651

ef = EfficientFrontier(mu, S, weight_bounds=(0,1))
weights = ef.max_sharpe()
>>>
OrderedDict([('252670.KS', -2.878111693e-07), ('091220.KS', 2.926511146e-07), ('114800.KS', -1.105321317e-07), ('251340.KS', 2.917380841e-07), ('233740.KS', 0.9999998137326296)])
```

**Comment by robertmartin8** [comment]
Hi @Younghoon-Lee,

Those are very small negative weights, so it's just a numerical thing. Use `ef.clean_weights()` if you would like a nicely-formatted output that has been rounded. 

One comment: the optimiser has essentially given 100% weight to the last asset – probably because its return is so much higher than the other assets. 

 Hope this helps!
 Robert
