### ISSUE TITLE
Feature request: Use Plotly instead of matplotlib

### ISSUE THREAD

**Issue by samatix** [robertmartin8/PyPortfolioOpt#352]
**Is your feature request related to a problem?**
Using matplotlib is very limited when it comes to graphical representation. 

**Describe the feature you'd like**
The idea is to replace matplotlib module with plotly

**Additional context**
With plotly:
![image](https://user-images.githubusercontent.com/3855711/123441520-3d1c9b00-d5d4-11eb-9cfe-4693d3171fa6.png)

With matplotlib:
![image](https://user-images.githubusercontent.com/3855711/123441613-5aea0000-d5d4-11eb-8597-4d350e473d3b.png)

I can take care of the migration to Plotly.

**Comment by robertmartin8** [comment]
Hi @samatix,

The plotly charts do indeed look awesome, but I don't think plotly should be part of core PyPortfolioOpt.

Ultimately I want PyPortfolioOpt to be focussed primarily on the portfolio optimisation itself – data ingestion, backtesting, plotting, portfolio analysis etc is not truly within the scope of the library. 

The existing plotting functionality is meant to be a "quick" solution for non-technical users to get off the ground, but my belief is that any more advanced plotting should be done by the user, using a library of their choice. Also, while I agree that plotly produces superior charts, matplotlib is the "industry standard" (at least in finance), so people will be able to interact with the plots. 

All this said, if you are willing to share code, I'd love to add this in one of the tutorial notebooks as an example of advanced plotting (will link/attribute in the docs).

Cheers,
Robert

**Comment by samatix** [comment]
Fully agreed @robertmartin8, I'll share the code in the cook book section.

**Comment by nicktids** [comment]
@samatix did you ever get the plotly in to a notbook for demo?
