### ISSUE TITLE
Maximize objective function in cvxpy

### ISSUE THREAD

**Issue by amos-peter** [robertmartin8/PyPortfolioOpt#354]
Hi could you please show me how to maximize a set score in pyportfolio "ef.add_objective(objective_functions.L2_reg, gamma=2)". I have done a manual cvxpy. However, i am not sure how to implement using add_objective funcitions.
```
import cvxpy as cp

mu = expected_returns.capm_return(df)
S = risk_models.CovarianceShrinkage(df).ledoit_wolf()

w = cp.Variable(ef.n_assets) # weights to optimize
problem = cp.Problem(objective=cp.Maximize(w @ comp_score),
                     constraints=[
                         w >= 0,
                         cp.sum(w) == 1,
                         cp.quad_form(w, S) <= 0.20 ** 2,
                     ],
                    )
problem.solve()
weights = w.value
weights
```

**Comment by amos-peter** [comment]
Hi, I think I manage to code to maximize a set of score objective. Could you please review if I code it in the right way?

`comp_scores = np.array(comp_score).reshape(-1,1)

def comp_score_obj(w, score):
    return w @ -score

ef = EfficientFrontier(mu, S, weight_bounds=(0, 1))
ef.convex_objective(market_score_objective, score=market_scores)
weights = ef.clean_weights()
weights`

**Comment by robertmartin8** [comment]
Looks good!
