### ISSUE TITLE
Feature request: Interest in other methods of calculating CVaR

### ISSUE THREAD

**Issue by ibaris** [robertmartin8/PyPortfolioOpt#355]
Is there interest on your side that other methods can be used to calculate CVaR? I could implement different methods such as the `Monte Carlo`, `Stressed Monte Carlo`, `Historical` and `GARCH` methods and also backtest these.

**Comment by robertmartin8** [comment]
Hi @ibaris,

Thanks for raising this! I don't think the package needs additional implementations of CVaR (or any other portfolio metrics for that matter) _unless_ these can be optimised. 

My view is that PyPortfolioOpt should focus on its core competency – portfolio optimisation. There exist packages dedicated to portfolio analysis, such as [pyfolio-reloaded](https://pypi.org/project/pyfolio-reloaded/)

Cheers,
Robert
