### ISSUE TITLE
Question on OptionImpliedPDF.ipynb

### ISSUE THREAD

**Issue by NCortax88** [robertmartin8/PyPortfolioOpt#356]
Hi Robert,

I am reaching out as I have a question related to the code in the OptionImpliedPDF Jupiter note:
I don t get why the cumsum of the created PDF functions sums to something closer to 10.

Could you elaborate on that please? Most probably I'm missing the point.

Many thanks

NC

**Comment by robertmartin8** [comment]
Closing as this is unrelated to PyPortfolioOpt. If you've got a question about my other writing, feel free to drop me an [email](https://reasonabledeviations.com/about/).
