### ISSUE TITLE
Multiple objective

### ISSUE THREAD

**Issue by amos-peter** [robertmartin8/PyPortfolioOpt#357]
Hi, is there a way for me to have multiple objectives. For example, maximize a set of scores and minimize volatility? Thank you!

**Comment by robertmartin8** [comment]
Hi @amos-peter,

You have two options here:

1) define a new objective function like "scores - c × volatility" then maximise this objective. The constant c will need to be chosen depending on how you want to tradeoff the scores and volatility
2) maximise scores subject to a vol constraint, or minimise vol subject to a scores constraint.

Best,
Robert

**Comment by amos-peter** [comment]
Hi Robert. Thank you for your suggestion. I agree that I might need to define a function to set the percentage trade-off for multiple objectives.

**Comment by robertmartin8** [comment]
Cool. Let me know if you get stuck!
