### ISSUE TITLE
sector constraints don't work properly for market-neutral efficient risk optimization

### ISSUE THREAD

**Issue by bass-dee** [robertmartin8/PyPortfolioOpt#362]
Hi there,

sector constraints don't work properly for market-neutral efficient risk optimization, despite setting negative lower boundaries!
Setting weight bounds globally (-1,1) also doesn't help.
I tried different solver, but same there.

I want stocks being able to go short/long and strategies & funds just long in the portfolio (because they might be long/short already).
If market_neutral=True everything is either long or short and sectors get overwritten, if False, everything just long.
Any ideas how to fix it?

```
mu = expected_returns.ema_historical_return(df)
S = risk_models.risk_matrix(df, method="ledoit_wolf")
ef = EfficientFrontier(mu, S, solver='CVXOPT', verbose=True)

      sector_mapper={'sp500_etf': 'fund',
       'AAPL': 'stocks',
       '1001413': 'strategy'
}

        sector_lower = {"strategy": 0.0,
                       "fund": 0.0,
                        "stocks": -1.0
                       }  
        sector_upper = {
                    "strategy": 1.0,
                       "fund": 1.0, 
                        "stocks": 1.0
        }
        ef.add_sector_constraints(sector_mapper, sector_lower,sector_upper)
        raw_weights=ef.efficient_risk(0.107, market_neutral=True)
```

Windows Version	10.0.19042 Build 19042,  Python 3.6.7, PyPortfolioOpt 1.2.6

**Comment by phschiele** [comment]
I think using sector constraints together with market-neutral portfolios is not supported at the moment:
https://github.com/robertmartin8/PyPortfolioOpt/blob/6158b1e22819d174bae8885fc74eed772890bb55/pypfopt/base_optimizer.py#L313-L316

**Comment by robertmartin8** [comment]
Will leave in the warning for the time being
