### ISSUE TITLE
Port portfolio optimisation 

### ISSUE THREAD

**Issue by qowiews** [robertmartin8/PyPortfolioOpt#378]
Hi,

I am trying to implement a portfolio optimisation that minimises the TE of port vs BM. In that sense I want a cut of so I want the te to be less than or equal to 0.1^2. 

code so far:

```python
mu = expected_returns.mean_historical_return(prices)
S = risk_models.sample_cov(prices)
ef = EfficientFrontier(mu, S)
ef.add_objective((objective_functions.ex_post_tracking_error, historic_returns=rets, benchmark_returns=spy_rets)<=0.1**2)
ef.min_volatility()
```

**Comment by phschiele** [comment]
Hi @qowiews, 
since you only want to ensure that TE is <= 0.01, but not minimise it beyond that, you should look into `.add_constraint()` rather than `.add_objective()`.

**Comment by qowiews** [comment]
Hi @phschiele,

So is impossible to use objective_functions.ex_post_tracking_error, historic_returns() In an .add_constraint()? or am I forced to make an def and a lambda function In the add_constraint() 

another question is it possible to minimise the TE  and at at the same time maximise the sharp.ratio ?
