### ISSUE TITLE
Issue with small numbers/Scientific Notations from yfinance.

### ISSUE THREAD

**Issue by Originn** [robertmartin8/PyPortfolioOpt#387]
Among my symbols in the yf.download there is a symbol (SHIB-USD) which is worth 0.00005 usd. 

Yf will download its info as a df with Scientific Notations, so converting it with
`pd.set_option('display.float_format', lambda x: '%.7f' % x)`

Although the step above, I get the following output:
`/home/ubuntu/.local/lib/python3.9/site-packages/sklearn/covariance/_shrunk_covariance.py:243: RuntimeWarning: overflow encountered in square
X2 = X ** 2
/home/ubuntu/.local/lib/python3.9/site-packages/sklearn/covariance/_shrunk_covariance.py:263: RuntimeWarning: overflow encountered in square
np.dot(X.T[block_size * n_splits :], X[:, block_size * n_splits :]) ** 2
/home/ubuntu/.local/lib/python3.9/site-packages/sklearn/covariance/_shrunk_covariance.py:270: RuntimeWarning: invalid value encountered in double_scalars
beta = 1.0 / (n_features * n_samples) * (beta_ / n_samples - delta_)
/home/ubuntu/.local/lib/python3.9/site-packages/sklearn/covariance/_shrunk_covariance.py:272: RuntimeWarning: invalid value encountered in double_scalars
delta = delta_ - 2.0 * mu * emp_cov_trace.sum() + n_features * mu ** 2
DEBUG: locator: <matplotlib.colorbar._ColorbarAutoLocator object at 0x7f4c1ae1ebb0>
DEBUG: Using auto colorbar locator <matplotlib.colorbar._ColorbarAutoLocator object at 0x7f4c1ae1ebb0> on colorbar
DEBUG: Setting pcolormesh
/home/ubuntu/.local/lib/python3.9/site-packages/sklearn/covariance/_shrunk_covariance.py:243: RuntimeWarning: overflow encountered in square
X2 = X ** 2
/home/ubuntu/.local/lib/python3.9/site-packages/sklearn/covariance/_shrunk_covariance.py:263: RuntimeWarning: overflow encountered in square
np.dot(X.T[block_size * n_splits :], X[:, block_size * n_splits :]) ** 2
/home/ubuntu/.local/lib/python3.9/site-packages/sklearn/covariance/_shrunk_covariance.py:270: RuntimeWarning: invalid value encountered in double_scalars
beta = 1.0 / (n_features * n_samples) * (beta_ / n_samples - delta_)
/home/ubuntu/.local/lib/python3.9/site-packages/sklearn/covariance/_shrunk_covariance.py:272: RuntimeWarning: invalid value encountered in double_scalars
delta = delta_ - 2.0 * mu * emp_cov_trace.sum() + n_features * mu ** 2`

And get ValueError: P must be symmetric/Hermitian.

I expirence this issue only with this specific symbol, I guess because it is a small number. Is there a way to include this symbol in the df without issues or I'll have to remove it?

Will appriciate your help!

**Comment by BrandonKMLee** [comment]
A bit of side question for here and https://github.com/robertmartin8/PyPortfolioOpt/issues/445 are there any way of making a tutorial of using `yfinance` with PyPortfolioOpt?
