### ISSUE TITLE
Should risk_free_rate be a yearly rate?

### ISSUE THREAD

**Issue by gawry** [robertmartin8/PyPortfolioOpt#39]
Should risk_free_rate be a yearly rate? Or should I use the same frequency as my returns?

**Comment by robertmartin8** [comment]
Hi, thanks for reaching out.

The risk-free rate is needed to calculate the Sharpe ratio as an [objective function](https://github.com/robertmartin8/PyPortfolioOpt/blob/master/pypfopt/objective_functions.py).

In particular: 

```python
return -(mu - risk_free_rate) / sigma + L2_reg
```

Hence `risk_free_rate` must correspond to the frequency of your `expected_returns`. e.g if you provide monthly expected returns, use a monthly risk-free rate. I will add this to the docs, thanks for bringing it to my attention!

**Comment by schneiderfelipe** [comment]
@robertmartin8 

In the code you mentioned, isn't `mu` automatically annualised? Portfolio performance, at least, returns annualised values, doesn't it? Same goes for `sigma`.

**Comment by robertmartin8** [comment]
@schneiderfelipe good point! 

@gawry my mistake. Actually the methods automatically annualise mu and sigma so risk_free_rate should stay annual.
