### ISSUE TITLE
Black Litterman not working

### ISSUE THREAD

**Issue by Ann-eat-apple** [robertmartin8/PyPortfolioOpt#392]
**What are you trying to do?**
Clear description of the problem you are trying to solve with PyPortfolioOpt

   from pypfopt import black_litterman
    from pypfopt.black_litterman import BlackLittermanModel
    from pypfopt.efficient_frontier import EfficientFrontier

    # viewdict = {"AAPL": 0.20, "BBY": -0.30, "BAC": 0, "SBUX": -0.2, "T": 0.15}
    S =  risk_models.risk_matrix(market_prices)
    bl = BlackLittermanModel(S). #### HERE IS THE ERROR 

    # rets = bl.bl_returns()
    # ef = EfficientFrontier(rets, cov_matrix)

    # OR use return-implied weights
    delta = black_litterman.market_implied_risk_aversion(market_prices)
    bl.bl_weights(delta)
    weights = bl.clean_weights()

It gave me this error:
`*** TypeError: Q must be an array or dataframe` on line 3 

**What have you tried?**

**What data are you using?**
What asset class, how many assets, how many data points. Preferably provide a sample of the dataset as a csv attachment.

**Comment by Ann-eat-apple** [comment]
can you please give us an example usage of BlackLittermanModel?

**Comment by robertmartin8** [comment]
Hi @Ann-eat-apple,

There is a walkthrough in the [docs](https://pyportfolioopt.readthedocs.io/en/latest/BlackLitterman.html). Could you let me know if that doesn't work for you?

Cheers,
Robert

**Comment by Ann-eat-apple** [comment]
```
# viewdict = {"AAPL": 0.20, "BBY": -0.30, "BAC": 0, "SBUX": -0.2, "T": 0.15}
S =  risk_models.risk_matrix(market_prices)
bl = BlackLittermanModel(S). #### HERE IS THE ERROR 
```

**Comment by Ann-eat-apple** [comment]
@robertmartin8

**Comment by robertmartin8** [comment]
Have you had a chance to look at the docs? You aren’t passing any views to BlackLittermanModel.  Please check this section: https://pyportfolioopt.readthedocs.io/en/latest/BlackLitterman.html#views

**Comment by robertmartin8** [comment]
Closing for now as I believe this is addressed in the docs and example notebooks Feel free to reopen if not
