### ISSUE TITLE
Optimization based on other parameters than risk and return

### ISSUE THREAD

**Issue by emillaursen95** [robertmartin8/PyPortfolioOpt#400]
Would I be able to include other parameters in the portfolio optimization process than risk and return characteristics? I have a case when I want to construct a portfolio of 50 stocks from an index based on parameters such as ESG scores and valuation metrics. I am using a z-score to account for all of the parameters that I want to base the decision on. The objective is to maximize the Sharpe ratio while being constrained by a maximum tracking error relative to the index. My primary issue is how I can use the z-score as the main decision variable while not exceeding a fixed tracking error and keeping the number of assets at around 50 assets. 

I hope that my question is understood - thanks!

**Comment by robertmartin8** [comment]
Hi Emil,

That's definitely possible – let me know if the [FAQs](https://pyportfolioopt.readthedocs.io/en/latest/FAQ.html#constraining-a-score) clarify it for you. You should be able to combine the "constraining a score" and "tracking error" to solve your problem.

Cheers,
Robert

**Comment by emillaursen95** [comment]
Great, thank you, Robert! Your package is extremely useful.

**Comment by robertmartin8** [comment]
Cheers! 

Feel free to reopen if you've got any follow-up Qs.
