### ISSUE TITLE
Feature request: [Multi-Period Portfolio Optimization]

### ISSUE THREAD

**Issue by sdafsdfw123wq** [robertmartin8/PyPortfolioOpt#403]
**Is your feature request related to a problem?**
Hello!

I am wondering if there is a feature for multi-period portfolio optimization?

**Comment by robertmartin8** [comment]
Hi, unfortunately not. Multi-period optimisation is quite a tricky area, and realistically I don't think I'm ever going to get round to implementing it.

Happy to accept well thought-out PRs in this area though
