### ISSUE TITLE
Undocumented shrinkage estimators

### ISSUE THREAD

**Issue by schneiderfelipe** [robertmartin8/PyPortfolioOpt#41]
Hi, #20 has offered two variants on the Ledoit-Wolf shrinkage estimator that are undocumented. I did some backtests and I believe that the single factor target may be better than the default constant variance target.

I have two questions regarding this:

1. Is there a reason why the single factor target isn't documented?
2. Is there a theoretical reason why the single factor might be better?

**Comment by robertmartin8** [comment]
Hi Felipe,

I've got a very very basic overview present in the [docs](https://pyportfolioopt.readthedocs.io/en/latest/RiskModels.html#shrinkage-estimators), with a link to the original journal article for people to read more.

For your second question, I'm afraid I don't have an answer – and it's not something that Ledoit and Wolf's papers discuss either. It is still very much an empirical topic, so I don't think one can do better than what you've done by backtesting it. 

Best,
Robert

**Comment by schneiderfelipe** [comment]
@robertmartin8 

Thanks for the answer! I didn't see *that* part of the docs, sorry!
