### ISSUE TITLE
Consider transaction cost during discrete_allocation

### ISSUE THREAD

**Issue by mgrytsai** [robertmartin8/PyPortfolioOpt#413]
**What are you trying to do?**
I'm using `discrete_allocation` to convert my percentage allocation into number of shares I need to buy to get as close as possible to target allocation. However, in real world there is a transaction fee associated.

**The question**
I'm wondering what will be the best option to incorporate transaction fee when doing [greedy search](https://github.com/robertmartin8/PyPortfolioOpt/blob/master/pypfopt/discrete_allocation.py#L129).

**Comment by phschiele** [comment]
@mgrytsai I don't think there is a straightforward way to include it into the existing implementation. Do you absolutely need the greedy approach? For small portfolios, it should be easy to write it as a mixed-integer linear program.
