### ISSUE TITLE
Different transaction costs to different assets problem

### ISSUE THREAD

**Issue by doudou2001** [robertmartin8/PyPortfolioOpt#418]
In a portfolio optimization problem, there are 3 assets in total, and I'd like to assign different transaction cost rates (e.g., 0.01, 0.02, 0.03) to the 3 assets. What should I do?

I've tried `ec.add_objective(objective_functions.transaction_cost, w_prev=initial_weights, k=0.1)`, but I can only pass one transaction cost rate.

**Comment by robertmartin8** [comment]
You could create a custom transaction cost objective that supports vector input. This is a quick modification I made by looking at the source code for `transaction_cost`.

```python
def transaction_cost(w, w_prev, k=0.001):
    return w, k @ (w - w_prev)
```

Not sure if that'll work, but a simple modification of it probably should!
