### ISSUE TITLE
5 Assets out of all Assets

### ISSUE THREAD

**Issue by AdamTheDestroyer** [robertmartin8/PyPortfolioOpt#424]
How can i get the best 5 Stocks with their weights out of all Stocks i have?

There is a new Bank Product, which i want to use for my retirement preperation. 

-Once every month i can invest in 5 ETFs without buying costs. 
-Once every month i can reorganize all the money i have invested before and invest it to other ETFs (also without costs).

Therefore i trying to optimize a Portfolio with all available ETF Stocks and take just 5 of it for my reorganization.

Is there a way i can do this?

Greetings
Adam

**Comment by robertmartin8** [comment]
Does this mean that every month you want to optimise a portfolio s.t. the constraint that num assets = 5?

**Comment by robertmartin8** [comment]
That seems like a reasonable heuristic. Alternatively, you could try a constraint on the number of assets (discussed in the [FAQs](https://pyportfolioopt.readthedocs.io/en/latest/FAQ.html#constraining-the-number-of-assets)) and in several of the issues. 

Best of luck!

**Comment by AdamTheDestroyer** [comment]
Thank you!
