### ISSUE TITLE
Rolling window 

### ISSUE THREAD

**Issue by smahjub** [robertmartin8/PyPortfolioOpt#44]
How would I implement a rolling window on the risk models and efficientfrontier?

**Comment by robertmartin8** [comment]
Could you clarify what you mean? All of the risk models produce covariance matrices

**Comment by smahjub** [comment]
Hi! I apologize for the question not being clear enough. I’m trying to incorporate your package into a backtest. So I’d like to pass a rolling window of prices (1000 hours) to calculate the CovarianceShrinkage and then ef.min_volatility().

**Comment by smahjub** [comment]
Essentially, I want to avoid using a for loop through the time series.

**Comment by cal97g** [comment]
@smahjub implement a method like this: https://github.com/octible/algobox/blob/master/core/backtest/data_handler.py#L39

Pass your list of datapoints to ListHandler, then call next each time you want a new slice. It will iterate through the window.

**Comment by robertmartin8** [comment]
To clarify, do you mean that every day (for example) you want to re-train a portfolio on the past 100 days of data?

**Comment by smahjub** [comment]
Yes, exactly!

**Comment by robertmartin8** [comment]
Why not just loop through the dataset? The rate-determining step will be the optimisation, not the looping. So I'm not convinced that there are major gains to be made with a clever rolling window optimisation. In particular, the built-ins expect the rolling function to produce a scalar, whereas this function produces a covariance matrix. I'd just loop through the dataset, particularly because you should be storing the weights etc from each optimisation period.

**Comment by smahjub** [comment]
Thank you for taking the time on this, I appreciate it. I have the entire model in Pandas so was trying to think how to keep it all the same. I’ll trust your advice that a for-loop is probably the best way to go in this case.

**Comment by a-erik** [comment]
May I ask if you got this to work witg a -for loop @smahjub

**Comment by smahjub** [comment]
I didn’t move forward with it because a for loop was going to be too slow
for my purposes.

**Comment by a-erik** [comment]
Ok. Couldn't one just make it a series or dict and run it trough a loop?
How did you go about?

**Comment by smahjub** [comment]
Yes. You can create a dataframe (depending how many symbols/contracts) of the weights with a for loop. You have to be careful to not look forward, only use historical to get the weight for next time sample. I was using hourly time series on many contracts so it wasn’t feasible in production. I wasn’t clear on how to make vectorize it to get rid of the for loop.

**Comment by a-erik** [comment]
Thanks for your response, man. Do you mind helping on below? I can't seem to get it to loop:

```
for t in range(60, len(tickers.iloc[0:3896])):
        k = t - 60
    mu = expected_returns.mean_historical_return(tickers.iloc[t - 60:t])
    S = CovarianceShrinkage(tickers.iloc[t - 60:t]).ledoit_wolf()
    ef = EfficientFrontier(mu, S,solver='SCS',weight_bounds=(0.02,1),solver_options={'warm_start':False})
    ef.max_sharpe()
    weights = pd.DataFrame(ef.clean_weights(), columns=ef.clean_weights().keys(), index=[0]).T
    weights = np.asarray(weights[0].to_list())
```
