### ISSUE TITLE
poetry update can't resolve dependencies

### ISSUE THREAD

**Issue by atrawog** [robertmartin8/PyPortfolioOpt#441]
**Describe the bug**
Running ```poetry update``` to update the poetry.lock file results in an endless loop and the only way I found to make the dependencies resolvable again was to set the Python version to ```python = "^3.8"```.

**Expected behavior**
A ```poetry update``` should result in an updated poetry.lock file.

**Operating system, python version, PyPortfolioOpt version**
Linux,Python 3.9.11, PyPortfolioOpt Master

**Comment by robertmartin8** [comment]
@atrawog good spot... I guess I will bump the python version in the `pyproject.toml`.
