### ISSUE TITLE
Change the utility for optimisation

### ISSUE THREAD

**Issue by qowiews** [robertmartin8/PyPortfolioOpt#448]
Hi

I am trying to  change the utility function in PyPortfolioOpt. 

Package is currently using a utility function that looks like:

<img width="146" alt="Skærmbillede 2022-04-24 kl  11 47 21" src="https://user-images.githubusercontent.com/92123407/164970529-80741645-c4f6-451f-aa6a-68cebe7d2f5d.png">

would it be possible to implement something like:

<img width="205" alt="Skærmbillede 2022-04-24 kl  11 49 21" src="https://user-images.githubusercontent.com/92123407/164970638-4329dbdb-1ab0-4fa8-b6aa-6c8cd6068a9e.png">

With γ being the investors aversion against ESG risk and ESG_all being the ESG risk measured as the standard deviation between the ESG score from the four different providers we have access to. So, the ESG_all variable is a vector with the standard deviation between the different providers ESG score for each company.

i have changed the code so the EfficientFrontiere class and the objective function also contains the vector of ESG_all.

Hope one of you guys can help change the code in the objective function for quadratic_utility
<img width="493" alt="Skærmbillede 2022-04-24 kl  11 54 34" src="https://user-images.githubusercontent.com/92123407/164970882-ea8d73a4-4d06-4198-86ea-fa71f030590f.png">

<img width="649" alt="Skærmbillede 2022-04-24 kl  11 55 20" src="https://user-images.githubusercontent.com/92123407/164970924-2b0a86eb-7ebb-47ef-bb01-cdae34cae5a8.png">

<img width="759" alt="Skærmbillede 2022-04-24 kl  11 55 51" src="https://user-images.githubusercontent.com/92123407/164970951-04555cb6-ad72-4393-a08c-00abd6e4e1cb.png">

**Comment by qowiews** [comment]
Basically the idea is to maximise the SR and at the same time the ESG risk aversion

**Comment by qowiews** [comment]
Hi again,

i will elaborate a bit:

Hi,

I have come up with the following utility function for the portfolio optimisation:

U=(E[r]-r_f)/E[σ^2] -γ·ESG_all

With γ being the investors aversion against ESG risk defined by ESG_all which is the ESG risk measured as the standard deviation between the ESG score from four different providers. So, the ESG_all variable is a vector with the standard deviation between the different providers ESG score for each company.

The point of departure is that for an investor which is not concerned about ESG risk the gamma value would be zero and he would simply seek to invest in the tangency portfolio, under the constraint of being ESG compliant. For the investor who are concerned about the ESG risk the gamma value would increase and we define an investor to be a ESG Risk-concerned investor with a gamma value of XX.

The level of ESG is not a part of the utility but will be a constraint to the portfolio so the investor does not care about the level of ESG if the portfolio is compliant which is defined by the constraint added to the portfolio optimization problem. So, the investor only cares about maximising his utility which is a tradeoff between the return per unit of risk and the ESG Risk.

So fare have I looked at the package PyPortfolioOpt which is great. But I simply can't implement a convex problem that the package can use in the optimisation. Can any one help with formalising a convex objective function the package can use ?

**Comment by dcelisgarza** [comment]
You have a non-linear objective, it's not a conxex problem. You may be able to try the non-convex optimiser that is part of the base optimiser class. However, I don't know if scipy is capable of using non-linear objectives. You'd have to create a function that uses a solver and constraint structure capable of dealing with non-linear objectives.

You could also try a transformation similar to the one done for the sharpe ratio, if you go to the docs for the max sharpe ratio optimisation there's a link to the paper describing it, where they transform the numerator into a constraint, transform all the constraints, and change the objective function to minimise only the denominator instead of the division.

**Comment by robertmartin8** [comment]
Yeah in general it's not easy to modify the Sharpe objective because of the transformation required to make it a convex problem. But this is also addressed in #444, so maybe the solution therein will help!

**Comment by qowiews** [comment]
Thank you guys!
