### ISSUE TITLE
Is there any stock limit for Efficient frontier 

### ISSUE THREAD

**Issue by gautam1858** [robertmartin8/PyPortfolioOpt#45]
Can I use 500 stocks for Portfolio optimization to calculate weights (like recommend gamma value, in the docs it says for 20 stocks gamma value is 1, what if we use 500 stocks ) ?

We tried with gamma value as 100 for 500 stocks but 80% of the tickers were assigned zero. 

Can you please help us with this ?

**Comment by robertmartin8** [comment]
Hi,

There are a number of choices to increase the number of nonzero weights: 

- set a minimum weight in the EfficientFrontier constructor, e.g `weight_bounds = (1e-3, 1)`.
- try with larger and larger gammas. Gamma essentially pulls the weights towards the equal-weight portfolio. 
- average the efficient frontier weights with the equal-weight portfolio.

Ultimately, this concentration of weights is an inherent issue with efficient frontier optimisation. 

Best,
Robert
