### ISSUE TITLE
Issue adding sector constraints

### ISSUE THREAD

**Issue by rnmease** [robertmartin8/PyPortfolioOpt#450]
**Describe the bug**
I get an error when sector constraints are added.  It works fine with the ef.add_sector_constraint line commented out but with it in, even when I set sector_lower to 0 and sector_upper to 1 (i.e. effectively no constraint), the error comes up.

**Expected behavior**
with lower limit set to 0 and upper set to 1, I expect to get the same answer as when the ef.add_sector_constraint line is commented out.

**Code sample**
returns:
Asset Class
Large Cap           0.121
Small Cap           0.063
International       0.065
Emerging Markets    0.073
Fixed Income        0.020
Cash                0.011
Name: Returns, dtype: float64

Covariance Matrix:
	Large Cap	Small Cap	International	Emerging Markets	Fixed Income	Cash
Asset Class						
Large Cap	0.038547	0.050913	0.030644	0.042136	0.001687	-0.000100
Small Cap	0.050913	0.097438	0.039222	0.063588	0.001448	-0.000348
International	0.030644	0.039222	0.045245	0.048235	-0.000129	-0.000106
Emerging Markets	0.042136	0.063588	0.048235	0.104146	-0.000859	0.000208
Fixed Income	0.001687	0.001448	-0.000129	-0.000859	0.004519	0.000155
Cash	-0.000100	-0.000348	-0.000106	0.000208	0.000155	0.000953

minwts:
array([0., 0., 0., 0., 0., 0.])
maxwts:
array([1., 1., 1., 1., 1., 1.])
sector_mapper:
{'International': 'X', 'Emerging Markets': 'X'}
sector_lower:
{'X': 0}
sector_upper:
{'X': 1}

actual code:
from pypfopt import EfficientFrontier
ef = EfficientFrontier(ret, df_cov)
ef.add_sector_constraints(sector_mapper, sector_lower, sector_upper)

ef.add_constraint(lambda x: x <= maxwts)
ef.add_constraint(lambda x: x >= minwts)

ef.max_sharpe()
weights = ef.clean_weights()
df_p0w = pd.DataFrame([weights])
df_p0w = df_p0w.T
df_p0w

**Operating system, python version, PyPortfolioOpt version**
e.g MacOS 10.146, python 3.7.3, PyPortfolioOpt 1.2.6

**Additional context**
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
Input In [63], in <cell line: 3>()
      1 from pypfopt import EfficientFrontier
      2 ef = EfficientFrontier(ret, df_cov)
----> 3 ef.add_sector_constraints(sector_mapper, sector_lower, sector_upper)
      5 ef.add_constraint(lambda x: x <= maxwts)
      6 ef.add_constraint(lambda x: x >= minwts)

File ~\Miniconda3\lib\site-packages\pypfopt\base_optimizer.py:386, in BaseConvexOptimizer.add_sector_constraints(self, sector_mapper, sector_lower, sector_upper)
    382     warnings.warn(
    383         "Sector constraints may not produce reasonable results if shorts are allowed."
    384     )
    385 for sector in sector_upper:
--> 386     is_sector = [sector_mapper[t] == sector for t in self.tickers]
    387     self.add_constraint(lambda w: cp.sum(w[is_sector]) <= sector_upper[sector])
    388 for sector in sector_lower:

File ~\Miniconda3\lib\site-packages\pypfopt\base_optimizer.py:386, in <listcomp>(.0)
    382     warnings.warn(
    383         "Sector constraints may not produce reasonable results if shorts are allowed."
    384     )
    385 for sector in sector_upper:
--> 386     is_sector = [sector_mapper[t] == sector for t in self.tickers]
    387     self.add_constraint(lambda w: cp.sum(w[is_sector]) <= sector_upper[sector])
    388 for sector in sector_lower:

KeyError: 'Large Cap'

**Comment by robertmartin8** [comment]
As per the error traceback, there is a KeyError – you haven't specified which sector Large Cap belongs to in `sector_mapper`. It _should_ work once you've done so!
