### ISSUE TITLE
Constraint on position change

### ISSUE THREAD

**Issue by bruppfab** [robertmartin8/PyPortfolioOpt#452]
**What are you trying to do?**
I am trying to limit the transaction costs by limiting how frequent switches in and out from positions. 

Consider the portfolio on t-1 is invested 50% in stock A and 50% in stock B.  On T-0 the optimizer would rebalance to 40% in stock A and 60% in stock B. However, I would like to add a constraint, that the positions on T-0 can only be T-1 positions +/-7% on total assets, i.e. both stocks can only be between 43% and 57% on T-0.

Any ideas how to solve this?

**Comment by robertmartin8** [comment]
Yup, that's doable. This [issue](https://github.com/robertmartin8/PyPortfolioOpt/issues/350) might help!
