### ISSUE TITLE
Expected Returns in Mean Variance Optimisation

### ISSUE THREAD

**Issue by karlemilzt** [robertmartin8/PyPortfolioOpt#455]
When using Mean Variance Optimisation, you always get the same output regardless of the expected returns input. This should not be the case. I have checked both for mean historical returns and CAPM-returns. I have doubled checked that the code is not wrong, and I can't find anything in the source code about it. I am pretty sure it is a bug.

Could someone please confirm which expected returns it uses?

**Comment by agj60** [comment]
This is certainly the case for minimum variance portfolios, that don't depend on expected returns. Otherwise, yes, optimal portfolios for different sets of returns should be different.

**Comment by karlemilzt** [comment]
Oh wow, I what a blunder from my side. Thank you!
