### ISSUE TITLE
Another optimizer on CVAR function

### ISSUE THREAD

**Issue by andrewczgithub** [robertmartin8/PyPortfolioOpt#46]
Hi @robertmartin8 

I was thinking of trying the below optimiser package with the cvar problem.

https://github.com/uqfoundation/mystic/blob/master/examples/example08.py

Would I just need to create another function in this class -
https://github.com/robertmartin8/PyPortfolioOpt/blob/master/pypfopt/value_at_risk.py

**and replace the line -**

        result = noisyopt.minimizeSPSA(
            objective_functions.negative_cvar,
            args=args,
            bounds=self.bounds,
            x0=self.initial_guess,
            niter=1000,
            paired=False,
        )

**with -**

    # use DE to solve 8th-order Chebyshev coefficients
    npop = 10*ndim
    solver = DifferentialEvolutionSolver2(ndim,npop)
    solver.SetRandomInitialPoints(min=[-100]*ndim, max=[100]*ndim)
    solver.SetGenerationMonitor(stepmon)
    solver.enable_signal_handler()
    solver.Solve(chebyshev8cost, termination=VTR(0.01), strategy=Best1Exp, \
                 CrossProbability=1.0, ScalingFactor=0.9, \
                 sigint_callback=plot_solution)
    solution = solver.Solution()

I know its not exact, but am I on the write track?
Best,
Andrew

**Comment by andrewczgithub** [comment]
I could then create a pull request with the update.

**Comment by robertmartin8** [comment]
Hi Andrew, 

Have you gotten reasonable results when trying it? How does it compare with the current implementation? 

My issue is that there *is* a proper way to implement CVaR optimisation using linear programming (+ monte carlo), so I'm not really keen to try other optimisers unless it's a big improvement.

Best,
Robert

**Comment by robertmartin8** [comment]
I'm closing this for now. Feel free to re-open if you believe that `mystic` offers a significantly better interim solution to `noisyopt`.
