### ISSUE TITLE
Constraints on absolute sum of weights

### ISSUE THREAD

**Issue by lcykrbn** [robertmartin8/PyPortfolioOpt#461]
Hello, thank you very much for this great tool! 

I have a question. I allowed short selling for individual asset weights in my code and I am trying to put a constraint on the "sum of absolute values" of assets. for example, if the optimizer assigned -20% to an asset, the sum of other assets should be 80%, not 120%. How can I add such a constraint?

Thanks a lot!
Olcay.

**Comment by lcykrbn** [comment]
Hello again, I also have another related question. I want the sum of all assets that have positive weight to sum up to 1, and assets with negative weights should be kept apart from this summation. This is becaues I consider all short positions as leverage.

**Comment by robertmartin8** [comment]
This is a difficult problem: see #133 for ideas
