### ISSUE TITLE
Feature request: Add constrains on weights in blacklitterman model

### ISSUE THREAD

**Issue by heartwxmddd** [robertmartin8/PyPortfolioOpt#464]
**Is your feature request related to a problem?**

We **cannot take short position**  in some assest on real markets, but **blacklitterman could give negative weights**.

so i think it would be better if we could **add constrains, like 0 to 1, on weights** in blacklitterman model.

many thanks!

**Comment by robertmartin8** [comment]
If you would like to use Black Litterman with constraints, you should feed the output from `BlackLitterman` into an `EfficientFrontier` object, then you may add whatever constraints you like.

By definition, the `bl_weights` are the _unconstrained_ returns (a special case of mean-variance optimisation)
