### ISSUE TITLE
Minimum optimal weight

### ISSUE THREAD

**Issue by amos-peter** [robertmartin8/PyPortfolioOpt#466]
Hi, could you please check how to set the minimum optimal weight of an asset? For example, if the optimized assets are 90 out of 100. the minimum weight of the 90 assets should be 0.0025.

**Comment by robertmartin8** [comment]
Hi, could you clarify what you mean? You can set a minimum weight threshold in the `EfficientFrontier` constructor, or you can add weight constraints by asset using `ef.add_constraint(w[7] >0.00025`.

**Comment by amos-peter** [comment]
Hi Robert. Could you please suggest any way to prevent the optimizer to produce very small weight like 0.001?

**Comment by robertmartin8** [comment]
Adding constraints is generally the best way of doing this
