### ISSUE TITLE
Updated function - Portfolio opt

### ISSUE THREAD

**Issue by andrewczgithub** [robertmartin8/PyPortfolioOpt#47]
Hi @robertmartin8 

I am getting an error with the below code, and i am not sure what is the updated function?

 imports a tool to convert capital into shares

```
from pypfopt import discrete_allocation

# returns the number of shares to buy given the asset weights, prices, and capital to invest
alloc = discrete_allocation.portfolio(
    weights, 
    df_buy_in['Buy In: 2014-12-31'], 
    total_portfolio_value=capital
)

# returns same as above but for the MIS
mis_alloc = discrete_allocation.portfolio(
    mis_weights, 
    df_mis_buy_in['Buy In: 2014-12-31'],
    total_portfolio_value=capital
)
# imports a tool to convert capital into shares
from pypfopt import discrete_allocation
​
# returns the number of shares to buy given the asset weights, prices, and capital to invest
alloc = discrete_allocation.portfolio(
    weights, 
    df_buy_in['Buy In: 2014-12-31'], 
    total_portfolio_value=capital
)
​
# returns same as above but for the MIS
mis_alloc = discrete_allocation.portfolio(
    mis_weights, 
    df_mis_buy_in['Buy In: 2014-12-31'],
    total_portfolio_value=capital
)
```

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-63-7ff1e26da9af> in <module>
      3 
      4 # returns the number of shares to buy given the asset weights, prices, and capital to invest
----> 5 alloc = discrete_allocation.portfolio(
      6     weights,
      7     df_buy_in['Buy In: 2014-12-31'],

AttributeError: module 'pypfopt.discrete_allocation' has no attribute 
```

**Comment by robertmartin8** [comment]
Hi Andrew,

The API was changed in v0.4.0. Below is an example of how allocation methods should be called:

```python
from pypfopt.discrete_allocation import DiscreteAllocation, get_latest_prices

latest_prices = get_latest_prices(df)
da = DiscreteAllocation(weights, latest_prices, total_portfolio_value=10000)
allocation, leftover = da.lp_portfolio()
print("Discrete allocation:", allocation)
```

You may find [this page](https://pyportfolioopt.readthedocs.io/en/latest/Postprocessing.html) in the documentation to be helpful.

Best,
Robert

**Comment by Lorenzo025** [comment]
Hello, 

Im trying to run this code but i keep getting the error

The solver GLPK_MI is not installed.

#get discrete allocation per stock
from pypfopt.discrete_allocation import DiscreteAllocation, get_latest_prices
#Amount you want to invest in this portfolio
portfolio_value = 10000

latest_prices = get_latest_prices(df)

weights = cleaned_weights
# da = discrete allocation
da = DiscreteAllocation(weights, latest_prices, total_portfolio_value = portfolio_value)

allocation, leftover = da.lp_portfolio()
print('Discrete Allocation', allocation)
print('Funds Remaining $', leftover)

**Comment by robertmartin8** [comment]
@Lorenzo025 have you installed CVXOPT? this comes packaged with `GLPK_MI`
