### ISSUE TITLE
Weird behaviour with a monthly frequency

### ISSUE THREAD

**Issue by nicolasplanchon** [robertmartin8/PyPortfolioOpt#471]
**What are you trying to do?**
Basic function tests with a monthly frequency of ETF prices. However, it looks like the expected_returns and risk_models classes don't handle the frequency=12 parameters given the results I get. 

Here is the portfolio : https://colab.research.google.com/drive/14UtRt26GpgWogz8hmJn6p9nAk0KM_BeR?usp=sharing

**What have you tried?**
Many things..

**What data are you using?**
Yfinance with a monthly frequency over the last 3 years on 35 tickers.

**Comment by robertmartin8** [comment]
Hey – I skimmed through the notebook and it all looks fine?
