### ISSUE TITLE
Portfolio optimisation with fama french factor exposure and tracking error constraint

### ISSUE THREAD

**Issue by Lucifer1887** [robertmartin8/PyPortfolioOpt#473]
<img width="414" alt="image" src="https://user-images.githubusercontent.com/89203064/183544566-aee83627-bd2b-4384-9b90-94895c3f062b.png">

**Comment by Lucifer1887** [comment]
How do I implement this using Pyportfolioopt

**Comment by robertmartin8** [comment]
It's possible to do this by defining custom objective functions etc, but you may be better off just coding it up directly in `cvxpy`.
