### ISSUE TITLE
Example Data Files

### ISSUE THREAD

**Issue by seahawk920** [robertmartin8/PyPortfolioOpt#478]
**What are you trying to do?**
I am testing the package to try to replicate the results from the user guide. 

**What have you tried?**
I tried following the link to get the data but it's not successful. 

**What data are you using?**
Can you provide the data (Goog, Facebook, etc) shown in the userguide so that I can make sure the package is running properly?

**Comment by robertmartin8** [comment]
I believe they are all here: https://github.com/robertmartin8/PyPortfolioOpt/tree/master/tests/resources

**Comment by seahawk920** [comment]
Thanks I tried out your below example and get slightly different results: 

Expected annual return: 30.5%
Annual volatility: 22.2%
Sharpe Ratio: 1.28

(That's what's shown in your website) 
Expected annual return: 33.0%
Annual volatility: 21.7%
Sharpe Ratio: 1.43

import pandas as pd
from pypfopt.efficient_frontier import EfficientFrontier
from pypfopt import risk_models
from pypfopt import expected_returns

# Read in price data
df = pd.read_csv("tests/resources/stock_prices.csv", parse_dates=True, index_col="date")

# Calculate expected returns and sample covariance
mu = expected_returns.mean_historical_return(df)
S = risk_models.sample_cov(df)

# Optimize for maximal Sharpe ratio
ef = EfficientFrontier(mu, S)
weights = ef.max_sharpe()
ef.portfolio_performance(verbose=True)

**Comment by robertmartin8** [comment]
Ah in that case I must have been using a slightly different time period, hence the different results. Don't have that file to hand anymore – my apologies!

**Comment by seahawk920** [comment]
No worry. Do you plan to update your documentation? I think it’s quite
useful for the new users.
