### ISSUE TITLE
Webapp for PyPortfolioOpt

### ISSUE THREAD

**Issue by Originn** [robertmartin8/PyPortfolioOpt#484]
I have created a webapp with a demo account and several features from PyPortfolioOpt. The repo is https://github.com/Originn/AdvancedPortOpt

Feel free to test it:)

Thanks again to Robert for allowing to share it.

**Comment by 88d52bdba0366127fffca9dfa93895** [comment]
It's great, but it should has no password for testing purposes.

**Comment by Originn** [comment]
@88d52bdba0366127fffca9dfa93895 
You need to register to use it, its just a simple username and password, no email needed.

**Comment by Originn** [comment]
@BrandonKMLee I'll need to migrate the website from Heroku due to discontinuation of the free service, might as well streamlit it as well. I am not familiar with it, reading the docs currently. The issue currently that I'll need to find a free postgres hosting service and free redis service, or something similar to those. I'll have a look.

**Comment by robertmartin8** [comment]
@Originn thanks for sharing! Small tip: you should include some screenshots in your Readme :)
