### ISSUE TITLE
Support for sklearn 1.0

### ISSUE THREAD

**Issue by yuezhihan** [robertmartin8/PyPortfolioOpt#485]
**Operating system, environment, python version**
Linux, mamba, python 3.9

**What you tried**
mamba install pyportfolioopt

**Error message**

```
$ mamba install PyPortfolioOpt

Looking for: ['pyportfolioopt']

conda-forge/linux-64                                          No change
conda-forge/noarch                                  68.0MB @   2.5MB/s 27.5s

Pinned packages:
  - python 3.9.*


Encountered problems while solving:
  - package celer-0.7.2-py39hac2352c_0 requires scikit-learn >=1.0, but none of the providers can be installed
```

Another package I installed requires sklearn >= 1.0, while pyportfolioopt requires sklearn < 1. Therefore, I cannot install pyportfolioopt in the same environment. Can pyportfolioopt support sklearn 1.0?

**Comment by robertmartin8** [comment]
I don't really see why PyPortfolioOpt requires `sklearn < 1`. In both the `requirements.txt` and the `pyproject.toml` it would appear to be ok?

**Comment by yuezhihan** [comment]
> I don't really see why PyPortfolioOpt requires `sklearn < 1`. In both the `requirements.txt` and the `pyproject.toml` it would appear to be ok?

Actually, the v1.5.3 version solved this issue. Maybe it's because pyportfolioopt was updated too late in conda-forge. I see it was updated 1 month and 15 days ago (https://anaconda.org/conda-forge/pyportfolioopt/files). Now it works fine. Thank you.
