### ISSUE TITLE
Is there a way to specify a minimum weight only for actually used stocks

### ISSUE THREAD

**Issue by rjungbeck** [robertmartin8/PyPortfolioOpt#487]
I want to create a portfolio with a limited number of different stocks  (eg 20) (that is smaller than the number of stocks to select from (eg 100)).  I also want to each stock in the portfolio to have a minimum weight (eg 2%) and maximum weight (eg 20%).

Your understanding of minimum weight seems to be that a value >0 requires each stock to be in the final portfolio. That is not what I want.  I want the weights to  either be 0%, or between minWeight and maxWeight.

**Comment by phschiele** [comment]
@rjungbeck great question! This can be done, see my previous comment here:
https://github.com/robertmartin8/PyPortfolioOpt/issues/411#issuecomment-1022603981

**Comment by rjungbeck** [comment]
@phschiele OK this seems to work (with ecos_bb solver).
Question: As it now  no longer a convex problem, wouldn't it be possible to also include discretization  (so that only a integer number of shares for each stock is bought) in the optimization problem? (And no longer as a separate DiscreteAllocation step).

**Comment by phschiele** [comment]
@rjungbeck You might consider using a different solver, ecos_bb can have some correctness issues (e.g., you could use the community version of CPLEX if you have less than 1000 variables/constraints).

Yes you can also handle integer orders. Just create an integer variable and multiply by share price ./. portfolio value. 
I.e., something like this should work (untested):
```py
n = cp.Variable(ef.n_assets - 1, integer=True)

asset_prices = np.array([...])  # length:  n_assets - 1
portfolio_value = 10_000
weight_fractions = asset_prices/portfolio_value

lb = 0.1
ub = 1.0
ef.add_constraint(lambda w: w[1:] == cp.multiply(n, weight_fractions)
```

Note that here I assume a cash asset at location 0, such that the budget constraint is always feasible.

**Comment by rjungbeck** [comment]
@phshiele: Your solution in #411 does not work with max_sharpe  (I can set the constraint, but the solver (ECOS_BB) later complains with DCPError) or HRPOt (I cannot set the solver or add the constraint)

The integer handling was similar to something I already tried and has the same result: ECOS_BB simply hangs on optimize.

The CPLEX license does not allow redistribution as part of an  paid for application. There pricing would make using it prohibitive expensive.

**Comment by phschiele** [comment]
You could try SCIP through pysciopt. Alternatively, I'm sure you could do an iterative heuristic using convex programs that would work well in most cases.
