### ISSUE TITLE
is constraint on target_return really needed?

### ISSUE THREAD

**Issue by giordanocolombi** [robertmartin8/PyPortfolioOpt#488]
this post is releted to this open issue: https://github.com/robertmartin8/PyPortfolioOpt/issues/477

I stumbled across the error described in #477 by appling the efficient frontier code on a portfolio where the security returns are:
```
mu.values
array([ 0.04598439,  0.052016  ,  0.03663621,  0.02208842,  0.06023858,
        0.03231331,  0.09586187,  0.08313241,  0.04043133, -0.10731498,
        0.02416566,  0.02330225, -0.01686913,  0.06442683,  0.06367358,
        0.16949511,  0.05215236,  0.07096311,  0.04112797,  0.00618275,
        0.02787441, -0.12790353,  0.13597   ,  0.08452797,  0.03030415,
       -0.14468394,  0.0537372 ,  0.04336144,  0.04963428, -0.02248067,
        0.01793846,  0.11759868,  0.04622102,  0.01007199,  0.10688818,
        0.07502199]) 
```
as you can see some of them are negative. Thus, I decided to debug the `plot_efficient_frontier` to understand what was going on under the hood. 

I found out that what triggers the error is:

https://github.com/robertmartin8/PyPortfolioOpt/blob/6644741ff27fca5f2aaeefd63e31d157cfd718ae/pypfopt/efficient_frontier/efficient_frontier.py#L392

Indeed, having a security with negative returns lead to a target result that sometimes is negative. Is this constraint really needed?

Moreover, when this happens the code doens't raise the right Exception making the error more difficult to spot. 
Indeed instead of:
https://github.com/robertmartin8/PyPortfolioOpt/blob/6644741ff27fca5f2aaeefd63e31d157cfd718ae/pypfopt/efficient_frontier/efficient_frontier.py#L393
the exception that is raised is:
https://github.com/robertmartin8/PyPortfolioOpt/blob/6644741ff27fca5f2aaeefd63e31d157cfd718ae/pypfopt/base_optimizer.py#L539
because of:
https://github.com/robertmartin8/PyPortfolioOpt/blob/6644741ff27fca5f2aaeefd63e31d157cfd718ae/pypfopt/plotting.py#L189-L194 

I would be happy to create a small PR to solve these small issues :)

**Comment by robertmartin8** [comment]
yeah perhaps the check isn’t needed

**Comment by giordanocolombi** [comment]
Hi Robert,

I open a very tiny PR to fix it :)

**Comment by robertmartin8** [comment]
merged, thanks!
