### ISSUE TITLE
Generalize bounds to be specific for each stock

### ISSUE THREAD

**Issue by ahmmsn** [robertmartin8/PyPortfolioOpt#49]
Hi, 

I have a portfolio for which I want to keep certain stocks at a given level and optimize the rest, but that's not possible with the current implementation.

Can we have the bounds input be either a tuple or an array of tuples? The change is simple enough and I have something working already. I'd be happy to push it up

**Comment by robertmartin8** [comment]
Hi,

That's a very fair point. The reason I have designed it this way is that the most common input is constant weight bounds. However, once you instantiate the `EfficientFrontier` object you can actually go ahead and modify it's bounds field directly:

```python
ef = EfficientFrontier(mu, cov_matrix)
ef.bounds = [(0, 0.3), (0,0.1), (0, 0.3) ... (0,0.2)]   # len of this list must = num assets
ef.max_sharpe()
```

What do you think of this workaround? 

That being said, I'd love to see your proposal – as long as users who want constant bounds only have to input one pair, I'm happy. 

Best,
Robert

**Comment by ahmmsn** [comment]
Oh! That's a good workaround, I'll do that on my code for the time-being.

I do think users will like the ability to specify bounds without having to access the class variables themselves. What I was thinking is changing `BaseOptimizer._make_valid_bounds()` to take in a single pair, or an array of pairs. 

The function already returns an array of pairs, so if we add some validation, then it should be able to take in two types of inputs. Thoughts?

**Comment by robertmartin8** [comment]
That sounds very reasonable. Do you want to have a go at implementing it
with some tests?

**Comment by ahmmsn** [comment]
I'll take a stab at it :) 
I'll create a new branch and push it shortly

**Comment by robertmartin8** [comment]
@ahmmsn 

You should make the changes in a branch then submit a pull request so I can have a look :)
