### ISSUE TITLE
Constraints that include an "or" condition

### ISSUE THREAD

**Issue by OriKatz1** [robertmartin8/PyPortfolioOpt#502]
**What are you trying to do?**
I want for the assets to be either 0% of the optimal portfolio or, say, above 10%. 
I mean, something like that:
opt = EfficientCVaR(expected_returns, scenarios)
opt.add_constraint(lambda x : x >= 0.1 if x != 0 )
How can I do that? 

**What data are you using?**
My "assets" are real estate markets, no point on investing in a market if the share is very small

**Comment by robertmartin8** [comment]
Try #411
