### ISSUE TITLE
Installed on Anaconda in virtual env, but Jupyter Notebook says ModuleNotFoundError: No module named 'PyPortfolioOpt'

### ISSUE THREAD

**Issue by briancbeasley** [robertmartin8/PyPortfolioOpt#504]
**What are you trying to do?**
I attempted the first sample test of the program, entering the following:
import pandas as pd
from pyofopt import Efficient Frontier
from pyofopt import risk_models
from pyofopt import expected_returns

#When I run, I receive: ModuleNotFoundError: No module named 'pyofopt' 
I have confirmed install in the correct virtual environment, and ran Jupyter Notebook from that environment as well. 

Am I missing something?

**Comment by robertmartin8** [comment]
Might have misspelt pypfopt?

**Comment by briancbeasley** [comment]
yep. fat fingers. Sorry to bother.
