### ISSUE TITLE
Could not install pyportfolioopt 1.5.4 (MacOS 13.1 venv)

### ISSUE THREAD

**Issue by yannisant** [robertmartin8/PyPortfolioOpt#506]
**Operating system, environment, python version**
venv on MacOS 13.1 (22C65), Python 3.10.7, pyportfolioopt 1.5.4

**What you tried**
pip install pyportfolioopt

**Error message**

```
error: [Errno 2] No such file or directory: 'README.md'
```

**Comment by yosukesan** [comment]
Is your problem identical to this run ? Please collapse 'Install dependencies' and chech where it was terminated on your env.
https://github.com/yosukesan/PyPortfolioOpt/actions/runs/3775485419/jobs/6418196292

I found CI is not running on win32 and macos correctly. see
 issue https://github.com/robertmartin8/PyPortfolioOpt/issues/509

**Comment by 88d52bdba0366127fffca9dfa93895** [comment]
I fixed the CI on the latest `master` branch and am closing this issue. Please feel free to reopen it if necessary.

If you still see the above error, please provide more information about your specific case as it may be different from others.
