### ISSUE TITLE
Docker build failed due to obsolete pip and poetry versions were hard coded on docker/Dockerfile

### ISSUE THREAD

**Issue by yosukesan** [robertmartin8/PyPortfolioOpt#507]
**Describe the bug**
Follow up for issue https://github.com/robertmartin8/PyPortfolioOpt/issues/476  and RP https://github.com/robertmartin8/PyPortfolioOpt/pull/498.
Issue https://github.com/robertmartin8/PyPortfolioOpt/issues/476 was fixed by RP https://github.com/robertmartin8/PyPortfolioOpt/pull/498, but we found pip and poetry versions were hard coded on the test.
They were too obsolete to make dependency and set up (download) failed. Then docker build terminated with ERROR. See the error detail for the pull request comment.

**Expected behavior**
After removing the hard coded versions, all unit test terminated successfully. see https://github.com/robertmartin8/PyPortfolioOpt/pull/498.

**Fix paln**
1. Remove the hard coded versions.
pyproject.toml and poetry.lock are used by docker on its build. pip version was specified (>=18.1) by pyproject.toml, but poerty's was unspecified. 

2. Update debian's container image
Buster is going to be unsupported in 2023. Updated to 'latest' which is currently the latest stable is Bullseye.

**Comment by yosukesan** [comment]
> 2. Update debian's container image
>    Buster is going to be unsupported in 2023. Updated to 'latest' which is currently the latest stable is Bullseye.

Noticed following on test. Switch to 3.9-slim from latest.
python:latest uses 3.11.1. 

```
The currently activated Python version 3.11.1 is not supported by the project (>=3.8,<3.11).
Trying to find and use a compatible version. 
```

specified here
```
$ grep -C 1 tool.poetry.dependencies pyproject.toml

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
```

**Comment by yosukesan** [comment]
PR https://github.com/robertmartin8/PyPortfolioOpt/pull/508

**Comment by 88d52bdba0366127fffca9dfa93895** [comment]
merged and fixed it, close the issue.
