### ISSUE TITLE
Github CI does not run on MacOS and Windows

### ISSUE THREAD

**Issue by yosukesan** [robertmartin8/PyPortfolioOpt#509]
**Describe the bug**
This is not code issue, but CI issue.
Inserted the line below and got 'linux' from pytest (macos-latest) and pytest (windows-latest) run. This meant all CI tests run on Ubuntu.
```
python -c "import sys; print(sys.platform)" 
```

Collaps 'Get full python version' tab and check line 8
https://github.com/yosukesan/PyPortfolioOpt/actions/runs/3775428942/jobs/6418111547
https://github.com/yosukesan/PyPortfolioOpt/actions/runs/3775428942/jobs/6418111498

**Expected behavior**
Windows-latest and macos-latest tests shall run on the specified OS respectively

**Code sample**
I think the change blow fix this problem.
```
- runs-on : ubuntu-latest
+ runs-on : ${{ matrix.os }}
```

**Comment by yosukesan** [comment]
After changing the code (Code sample) CI run on correct OS, but we've got installation problem now.

windows:
https://github.com/yosukesan/PyPortfolioOpt/actions/runs/3775485419/jobs/6418196256

maxos:
https://github.com/yosukesan/PyPortfolioOpt/actions/runs/3775485419/jobs/6418196292

Changes:
https://github.com/robertmartin8/PyPortfolioOpt/compare/master...yosukesan:PyPortfolioOpt:CI_does_not_work_on_maxos_and_win32%23509

**Comment by yosukesan** [comment]
Just sent RP https://github.com/robertmartin8/PyPortfolioOpt/pull/510 for fix CI issue. Can I add two installation issues for win and mac ?

**Comment by 88d52bdba0366127fffca9dfa93895** [comment]
fixed the CI on latest `master`, close this issue. Please feel free to reopen it if necessary.

**Comment by yosukesan** [comment]
From https://github.com/robertmartin8/PyPortfolioOpt/actions/runs/4836018171 Install dependencies logs, I think test is running on correct OS now. I haven't got win and mac env locally, so haven't checked.
Thanks for your work.
