### ISSUE TITLE
Inconsistent dependencies in requiremets.txt and pyproject.toml

### ISSUE THREAD

**Issue by kaykurokawa** [robertmartin8/PyPortfolioOpt#524]
In requirements.txt, it requires numpy >= 1.12.0 and yfinance >= 0.1.55 , but pyproject.toml requires numpy >= 1.22.4  and yfinance >= 0.1.70

Also, this project seems to work fine also with numpy version less than 1.22.4 (I've been using 1.18 and 1.20) , so I'm not sure what the actual required numpy version should be.

**Comment by 88d52bdba0366127fffca9dfa93895** [comment]
Hi @kaykurokawa, I downgraded the numpy requirement to v1.0.0 and remove the conflict of those versions, it's better if you have numpy >= 1.15.0. Could you try to install latest code in the branch `master`?
