### ISSUE TITLE
Cannot install v1.5.4 with python v3.11+

### ISSUE THREAD

**Issue by jlchereau** [robertmartin8/PyPortfolioOpt#527]
**Describe the bug**

I run Python 3.11.2 on windows 11:
- `pip install pyportfolioopt` installs v1.5.2
- `pip install pyportfolioopt==1.5.4` displays the following error:

```
ERROR: Ignored the following versions that require a different python version: 1.5.3 Requires-Python >=3.8,<3.11; 1.5.4 Requires-Python >=3.8,<3.11
ERROR: Could not find a version that satisfies the requirement pyportfolioopt==1.5.4 (from versions: 0.1.0rc1, 0.1.0, 0.1.1, 0.2.0, 0.3.0, 0.3.1, 0.3.2, 0.3.3, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4, 0.5.5, 1.0.0, 1.0.1, 1.0.2, 1.1.0, 1.2.0, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.7, 1.3.0, 1.3.1, 1.4.0, 1.4.1, 1.4.2, 1.5.0, 1.5.1, 1.5.2)
ERROR: No matching distribution found for pyportfolioopt==1.5.4
```

**Expected behavior**
Should install latest version

**Code sample**
N/A

**Operating system, python version, PyPortfolioOpt version**
Python 3.11.2 on windows 11

**Additional context**
Workaround: use pip option `--ignore-requires-python`

**Comment by 88d52bdba0366127fffca9dfa93895** [comment]
Hi @jlchereau, could you please try to install latest code on the branch `master` and confirm that you can install with python v3.11+ on you environment?
