### ISSUE TITLE
Typo on Repo Description

### ISSUE THREAD

**Issue by gonzalesMK** [robertmartin8/PyPortfolioOpt#538]
**Describe the bug**

The repo states:
`Financial portfolio optimisation in python, including classical efficient frontier, Black-Litterman, Hierarchical Risk Parity `

There is a small typo on optimisation:
`Financial portfolio optimization in python, including classical efficient frontier, Black-Litterman, Hierarchical Risk Parity `

**Comment by 88d52bdba0366127fffca9dfa93895** [comment]
Hi @gonzalesMK, thanks for your report but the `optimisation` is British English

Ref: https://www.oxfordlearnersdictionaries.com/definition/english/optimize?q=optimise

**Comment by gonzalesMK** [comment]
Hey, I just learned something new today!  :smile: 

Sorry for misreporting.

**Comment by 88d52bdba0366127fffca9dfa93895** [comment]
np you're welcome
