### ISSUE TITLE
 cannot import name 'EfficientCVaR' from 'pypfopt' 

### ISSUE THREAD

**Issue by frr717** [robertmartin8/PyPortfolioOpt#546]
**Describe the bug**
running cookbook/2-Mean-Variance-Optimisation.ipynb, when encountering "from pypfopt import EfficientCVaR", it will throw
ImportError                               Traceback (most recent call last)
Cell In[67], line 1
----> 1 from pypfopt import EfficientCVaR
      3 ec = EfficientCVaR(mu, returns)
      4 ec.min_cvar()

ImportError: cannot import name 'EfficientCVaR' from 'pypfopt' (c:\Users\reborn\AppData\Local\Programs\Python\Python310\lib\site-packages\pypfopt\__init__.py)
**Expected behavior**
no exception

**Code sample**
from pypfopt import EfficientCVaR

**Operating system, python version, PyPortfolioOpt version**
win10, 64bit, python 3.10.8, PyPortfolioOpt 1.3.0

**Additional context**

**Comment by 88d52bdba0366127fffca9dfa93895** [comment]
hi @frr717, I checked the notebook but didnt see the above error, please try again on Colab or make sure you have the library on your local. Also, if you see error on `Plotting - Constrained` section, please change the range of `ef_param_range`, my valid range for today's data is `ef_param_range=np.linspace(0.13, 0.346558, 50)`
