### ISSUE TITLE
Unable to import the plotting module 'seeborn-deep' not an available style

### ISSUE THREAD

**Issue by RicardoBlank** [robertmartin8/PyPortfolioOpt#562]
**Describe the bug**
Cannot import the **plotting** module

**Thrown errors**
FileNotFoundError: [Errno 2] No such file or directory: 'seaborn-deep'

OSError: 'seaborn-deep' is not a valid package style, path of style file, URL of style file, or library style name (library styles are listed in `style.available`)

**Operating system, python version, PyPortfolioOpt version**
Linux, python 3.10.12, PyPortfolioOpt 1.5.4, matplotlib 3.8.0

**Comment by LuisGCanales** [comment]
Changing `plt.style.use("seaborn-deep")` to `plt.style.use("seaborn-v0_8-deep")` at line 21 of plotting.py does the work.

**Comment by 88d52bdba0366127fffca9dfa93895** [comment]
Please use latest version (1.5.5) here: https://pypi.org/project/pyportfolioopt/#history

**Comment by jiangzhonglian** [comment]
The same error is still there，PyPortfolioOpt version 1.5.5

```
seaborn                    0.13.0
matplotlib                 3.8.2
pyportfolioopt             1.5.5
```

<img width="678" alt="image" src="https://github.com/robertmartin8/PyPortfolioOpt/assets/9199175/4827db78-6dff-401b-af29-9a2943d80a74">

**Comment by jiangzhonglian** [comment]
I fix this error, you can try: 

```
pandas==1.3.3
seaborn==0.11.1
matplotlib==3.2.0
```

> I am using the latest version 1.5.5 and still encounter this error. Any suggestions? Thanks
> 
> > Changing plt.style.use("seaborn-deep") to plt.style.use("seaborn-v0_8-deep") at line 21 of plotting.py does the work.
> 
> After doing this, my python crashes every time I run the code that import `plotting` module.
