### ISSUE TITLE
pypfopt\plotting.py specifies an invalid style plt.style.use("seaborn-deep")

### ISSUE THREAD

**Issue by JonPoynter** [robertmartin8/PyPortfolioOpt#581]
**Describe the bug**
I am getting an error with the plotting package:

OSError: 'seaborn-deep' is not a valid package style, path of style file, URL of style file, 
or library style name (library styles are listed in `style.available`)

error caused by site-packages\pypfopt\plotting.py", line 21, in <module>    

plt.style.use("seaborn-deep")

I am using the latest version of seaborn  0.13.2

**Expected behavior**

Not to get an error

**Code sample**

error occurs when loading the package

from pypfopt import plotting

**Operating system, python version, PyPortfolioOpt version**
Windows OS Version: 10.0.22621, python 3.9.7, PyPortfolioOpt 1.5.5

**Additional context**

**Comment by mikylucky** [comment]
Same error here, I just installed the library and imported it

macOS, python 3.11.7, PyPortfolioOpt 1.5.5
