### ISSUE TITLE
Results not same as portfoliovisualizer.com

### ISSUE THREAD

**Issue by hcleungca** [robertmartin8/PyPortfolioOpt#596]
**What are you trying to do?**
I'm trying to reproduce the results of optimizing two ETFs (VOO, VGLT) from portfoliovisualizer.com 
https://www.portfoliovisualizer.com/optimize-portfolio?s=y&sl=3bujgs9JzveGOAw5M75x7g

**What have you tried?**
I tried to do it using PyPortfolioOpt, the colab notebook can be found here
https://colab.research.google.com/drive/1MgPrnar7MxrHZR2IqWA7ovKiepDN5DHH?usp=sharing

**What data are you using?**
I'm using data download from yahoo

** Problem **
maximizing sharpe ratio of two ETFs (VOO, VGLT) from portfoliovisualizer.com gave VOO 80.42%, VGLT 19.58%
but using PyPortfolioOpt gave VOO 70.8%, VGLT 29.2% 

Did I do something wrong? thanks a lot

**Comment by jokercraft** [comment]
The difference could be due to the calculation technique for expected returns, covariance, and some other risk/return-related metrics used in the final optimization calculation. Your volatilities are different too. It is not a surprise that the final weights are different.

**Comment by ManyeeK** [comment]
Is portfoliovisualizer.com using yahoo data? I assume not as they have premium plans, would be joke if they are not using good ones.....

**Comment by robertmartin8** [comment]
Hi, thanks for looking into this. The most likely cause is different windows/methodologies for calculating the expected returns and covariance matrix, which are required as inputs.

Beyond that, there are second order factors like different risk_free_rate assumptions, numerical differences, etc.
