### ISSUE TITLE
Time Varying Constraints Based on Benchmark Weights

### ISSUE THREAD

**Issue by richfremgen** [robertmartin8/PyPortfolioOpt#598]
**What are you trying to do?**
Are we able to add in time-varying sector constraints? For example if the sector weights in a benchmark change over time, I want the constraints on my portfolio's sector weights to dynamically adjust based on these changes. The constraints would be set as a certain percentage range (e.g., ±10%) around the sector weights in the benchmark index at each time step.

**Comment by robertmartin8** [comment]
Hi, I don't think there's a better way to do this than looping through, and at each time step re-optimising the portfolio using your new constraints. 

You can include a turnover penalty to stop the optimiser from massively changing the weights.
