### ISSUE TITLE
Plotting efficient frontier

### ISSUE THREAD

**Issue by elGringo11** [robertmartin8/PyPortfolioOpt#601]
Hello, how can I plot the efficient frontier diagram, showing the assets by return and volatility, the optimal portfolio, and the frontier? Thanks a lot!

**Comment by robertmartin8** [comment]
Hi, there are several examples in the [cookbooks](https://github.com/robertmartin8/PyPortfolioOpt/blob/master/cookbook/2-Mean-Variance-Optimisation.ipynb)
