### ISSUE TITLE
cannot import name 'hrp_portfolio' from 'pypfopt.hierarchical_risk_parity'

### ISSUE THREAD

**Issue by akitxu** [robertmartin8/PyPortfolioOpt#61]
Dear All

Within the directory where I have the jupyter notebook script I want to work with, which uses this library, clone "PyPortfolioOpt and run the setup for installation. When executing the script I get the error" ImportError: cannot import name 'hrp_portfolio 'from' pypfopt.hierarchical_risk_parity '(C: \ Anaconda3 \ lib \ site-packages \ pyportfolioopt-0.5.1-py3.7.egg \ pypfopt \ hierarchical_risk_parity.py) ".
I will appreciate help to overcome this problem.

Best regards

**Comment by robertmartin8** [comment]
Hi, 

This is my fault – I changed the API a while ago and don't have a good example of usage in the docs. However, there is an example of new usage in `examples.py`: [here](https://github.com/robertmartin8/PyPortfolioOpt/blob/master/examples.py).

Hope this helps!
Robert

**Comment by akitxu** [comment]
Thanks.  The problem was solved by changing  "from pypfopt.hierarchical_risk_parity import hrp_portfolio" to "from pypfopt.hierarchical_risk_parity import HRPOpt"
