### ISSUE TITLE
Sigue el error:  No module named 'pulp'

### ISSUE THREAD

**Issue by akitxu** [robertmartin8/PyPortfolioOpt#63]
I have re-created the environment and installed pulp with:
`pip install pulp==1.6.10`
Al ejecutar
`from pypfopt import discrete_allocation` 
It keep returning me the error.
`ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-18-c2f7d90634ef> in <module>
----> 1 from pypfopt import discrete_allocation

C:\Anaconda3\lib\site-packages\pyportfolioopt-0.5.1-py3.7.egg\pypfopt\discrete_allocation.py in <module>
      6 import numpy as np
      7 import pandas as pd
----> 8 import pulp
      9 
     10 

ModuleNotFoundError: No module named 'pulp'
`

**Comment by schneiderfelipe** [comment]
Is this the same error as #62 @akitxu?

**Comment by akitxu** [comment]
Yes, every time is the same error

**Comment by akitxu** [comment]
Certainly, I think I did not do well when I opened error 362 on Github PyPortfolioOpt instead of on Github Geston_Recursos, which is where the error occurs

**Comment by robertmartin8** [comment]
Closing as duplicate of #62
