### ISSUE TITLE
ImportError: No module named setuptools

### ISSUE THREAD

**Issue by akitxu** [robertmartin8/PyPortfolioOpt#65]
I am trying, after cloning it, to install this module on a Linuxmint computer. When executing the command` python setup.py` install, inside the cloning directory, I get the error:
```
enri@enri-Presario-CQ57-Notebook-PC:/media/enri/TRABAJO/PyPortfolioOpt-master$ python setup.py install
Traceback (most recent call last):
  File "setup.py", line 1, in <module>
    from setuptools import setup
ImportError: No module named setuptools

What can be the cause?
```
e

**Comment by robertmartin8** [comment]
Try pip install setuptools.

What version of python are you using?

**Comment by akitxu** [comment]
Efectivamente, por iba el problema. Linux Mint 19 instala por defecto python 2.7.17. Anaconda 3 crea por defecto un entorno virtual denominado base. Cierro este problema y abro un nuevo.

**Comment by akitxu** [comment]
Linux Mint operating system 19.2. I start from scratch and follow the following process.
a) .- I create an env called "Gestion_Recursos".
b) .- Active env.
c) .- I install "Jupyter notebook" in this env.
d) .- With pip I install "pulp" in this env. (version 2.0)
e) .- I open "jupyter",
f) .- Clone "Gestion_Resources".
g) .- I go to "Gestion_Recursos" with "Jupyter".
h) .- I open with Jupyter "PyPortfolioOpt 0.2.0.ipynb".
i) .- I install scikit-learn in this env.
j) .- I execute the import sentences of modules of "PyPortfolioOpt 0.2.0.ipynb".
It returns me  the error:
`` ImportError Traceback (most recent call last)
<ipython-input-1-1256bf6b0805> in <module>
      4 from pypfopt import risk_models
      5 from pypfopt import expected_returns
----> 6 from pypfopt.hierarchical_risk_parity import hrp_portfolio
      7 from pypfopt.value_at_risk import CVAROpt
      8 from pypfopt import discrete_allocation

ImportError: cannot import name 'hrp_portfolio' from 'pypfopt.hierarchical_risk_parity' (/home/enri/anaconda3/envs/Gestion_Recursos/lib/python3.8/site-packages/pypfopt/hierarchical_risk_parity.py)
`
