### ISSUE TITLE
EfficientFrontier - erorr

### ISSUE THREAD

**Issue by biocoreexpert** [robertmartin8/PyPortfolioOpt#69]
Is this some python-version issue?
It worked fine until this point. 

>>> ef = EfficientFrontier(mu, S)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "pypfopt/efficient_frontier.py", line 84, in __init__
    super().__init__(len(tickers), tickers, weight_bounds)
TypeError: super() takes at least 1 argument (0 given)
>>>

**Comment by robertmartin8** [comment]
Hi,

I do believe it's a python version error. Could you let me know what version of python and this package you're using? 

Best,
Robert
