### ISSUE TITLE
(Question)Plotting the Eff frontier

### ISSUE THREAD

**Issue by joan-arau** [robertmartin8/PyPortfolioOpt#7]
Could you share the function to plot the Eff frontier as shown in the user guide ?

**Comment by robertmartin8** [comment]
Hi there,

Right now that's not really a part of this package; the code I used to generate it was from a different project of mine. If you're still interested in it, I've uploaded it as a text file (change it to .py), but you'd have to supply your own stock prices as input.

[efficient_frontier.txt](https://github.com/robertmartin8/PyPortfolioOpt/files/2412875/efficient_frontier.txt)

Hope that helps!
