### ISSUE TITLE
pipenv support

### ISSUE THREAD

**Issue by zhenyulin** [robertmartin8/PyPortfolioOpt#71]
current using `pipenv install PyPortfolioOpt` would result in 'Not Found' error

**Comment by robertmartin8** [comment]
Hi,

Thanks for the suggestion. I'm currently not familiar with `pipenv`. From a quick read on the internet, it seems that all I need to do is provide a `pipfile` in the repo? If that's the only thing, I'm happy to support `pipenv`.

Best,
Robert

**Comment by zhenyulin** [comment]
possibly, I haven't published a package of Python myself, but from the reading `pipenv` would download packages from PyPI, so it probably just needs some extra setup

https://github.com/pypa/pipenv/issues/1288
