### ISSUE TITLE
Can't find CVAR optimization in the module

### ISSUE THREAD

**Issue by blonpina** [robertmartin8/PyPortfolioOpt#72]
Hello! I can't find value at risk function described here: https://pyportfolioopt.readthedocs.io/en/latest/OtherOptimisers.html#pypfopt.value_at_risk.CVAROpt

It says "AttributeError: module 'pypfopt' has no attribute 'value_at_risk'"

How can I use CVAR optimization within this pypfopt module?

Thanks!

**Comment by robertmartin8** [comment]
Hi, thanks for raising the issue. The CVaR optimisation is currently broken, I will be removing it from PyPortfolioOpt soon until I can figure out how to properly fix it (see #5)
