### ISSUE TITLE
Efficient Frontier Min Volatility - Not necessarily the minimum volatility

### ISSUE THREAD

**Issue by edgetrader** [robertmartin8/PyPortfolioOpt#75]
See attached python notebook and data file.  

Notice ef.max_sharpe(risk_free_rate=0.00) produces lower volatility than ef.min_volatility().

[min_vol_issue.zip](https://github.com/robertmartin8/PyPortfolioOpt/files/4282050/min_vol_issue.zip)

Can you check and let me know whether this is a bug?

**Comment by robertmartin8** [comment]
Hi, 

Thank you so much for raising this issue and providing code/data to accompany it. I was able to replicate your results.

This is indeed an important bug, though it is a very strange. PyPortfolioOpt is really quite a simple package, and I can't see any errors in the code. I fear that the actual problem is in the scipy optimiser – the only fix for this is for me to migrate PyPortfolioOpt to a different backend. This has always been part of the plan I suppose, but it is not looking achievable in the near future given my current commitments.

I will aim to revisit this in a couple of weeks with fresh eyes. 

Apologies,
Robert

**Comment by schneiderfelipe** [comment]
> Hi,
> 
> Thank you so much for raising this issue and providing code/data to accompany it. I was able to replicate your results.
> 
> This is indeed an important bug, though it is a very strange. PyPortfolioOpt is really quite a simple package, and I can't see any errors in the code. I fear that the actual problem is in the scipy optimiser – the only fix for this is for me to migrate PyPortfolioOpt to a different backend. This has always been part of the plan I suppose, but it is not looking achievable in the near future given my current commitments.
> 
> I will aim to revisit this in a couple of weeks with fresh eyes.
> 
> Apologies,
> Robert

@robertmartin8 can't we give the user some way to access the results of the SciPy optimisation to check whether the optimisation was successful? We could, e.g., store the [scipy.optimize.OptimizeResult](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.optimize.OptimizeResult.html) object within the instances of BaseScipyOptimizer subclasses:

```python3
class EfficientFrontier(base_optimizer.BaseScipyOptimizer):
    ....
    def max_sharpe(self, risk_free_rate=0.02):
        """
        ...
        """
        if not isinstance(risk_free_rate, (int, float)):
            raise ValueError("risk_free_rate should be numeric")

        args = (self.expected_returns, self.cov_matrix, self.gamma, risk_free_rate)

        # storing the result in the instance
        self.result = sco.minimize(
            objective_functions.negative_sharpe,
            x0=self.initial_guess,
            args=args,
            method=self.opt_method,
            bounds=self.bounds,
            constraints=self.constraints,
        )
        self.weights = result["x"]
        return dict(zip(self.tickers, self.weights))
```

So, (in case `self.result` was set to `None` in `__init__`) we could

```python3
...
_ = ef.max_sharpe(risk_free_rate=0.00)
if ef.result is None or not ef.result.success:
    print("Error: unsuccessful optimisation!")
...
```

Additionally (or even instead), an error could be raised in `max_sharpe`:

```python3
....
self.result = sco.minimize(
    objective_functions.negative_sharpe,
    x0=self.initial_guess,
    args=args,
    method=self.opt_method,
    bounds=self.bounds,
    constraints=self.constraints,
)

if not self.result.success:
    # or some other error?
    raise ValueError(f"Unsucessful optimization: "
                     f"{self.result.message} (status={self.result.status})")
...
```

The user could then use a `try...catch` block to ensure everything is safe.

**Comment by robertmartin8** [comment]
@schneiderfelipe 

Those are all good ideas, and I will aim to include them in the next release. 

However, the more unsettling thing is that a failure exists in the first place for such a simple dataset!

Robert

**Comment by gatorliu** [comment]
I think this problem is because scipy optimiser's just solved the local minimize, not global minimize,
when the parameter `x_0` is given by `self.initial_guess` in some case

on @edgetrader 's example
```
import pandas as pd
from pypfopt.efficient_frontier import EfficientFrontier

expected_returns_daily = pd.Series([0.043622, 0.120588,  0.072331, 0.056586], index=['AGG', 'SPY', 'GLD', 'HYG'])
covariance_matrix = pd.DataFrame([
     [ 0.000859, -0.000941,  0.001494, -0.000062]
    ,[-0.000941,  0.022400, -0.002184,  0.005747]
    ,[ 0.001494, -0.002184,  0.011518, -0.000129]
    ,[-0.000062,  0.005747, -0.000129,  0.002287]
    ],
    index = ['AGG', 'SPY', 'GLD', 'HYG'],
    columns= ['AGG', 'SPY', 'GLD', 'HYG']
    )
ef = EfficientFrontier(expected_returns_daily, covariance_matrix)
```

Solve minimize volatility (using default `initial_guess`)
```
ef.min_volatility()
volatility_minv  = ef.portfolio_performance(risk_free_rate = 0.00)[1]
# volatility_minv  = 0.025727685319005385
```
Solve max sharpe  (using default `initial_guess`)
```
ef.max_sharpe(risk_free_rate=0.00)
volatility_maxs  = ef.portfolio_performance(risk_free_rate = 0.00)[1]
# volatility_maxs  = 0.025330974771971895
```
volatility_minv(0.257...)  > volatility_max (0.253..)

If we solve minimize volatility by using weights from max_sharpe() as `initial_guess` 
```
ef.initial_guess = ef.weights  # replaced initial_guess by weights
ef.min_volatility()
volatility  = ef.portfolio_performance(risk_free_rate = 0.00)[1]
# volatility  = 0.024508632182529723
```
We got  the much lower volatility.
Hope it helps you!

**Comment by robertmartin8** [comment]
Happy to announce that in the dev branch (migrating backend from `scipy` to `cvxpy`), I have verified this is no longer an issue and added a test.

@gatorliu Thanks for your detailed write-up, I was able to directly copy-paste your code as a test 💯 

@edgetrader Sorry for the issue and stay tuned for the new release! Progress is being tracked in #77.
