### ISSUE TITLE
Pulp error when calculating discrete allocation

### ISSUE THREAD

**Issue by MarcelKresse** [robertmartin8/PyPortfolioOpt#76]
Hi Robert, 

first of all, thank you for sharing this great library. 

Unfortunately I have to report a bug. Since today the following error occurs when calculating the discrete allocation:
Pulp: Error while trying to execute /usr/local/lib/python3.6/dist-packages/pulp/solverdir/cbc/linux/64/cbc  
Yesterday the package still worked flawlessly. However, since today the error occurs. All other things have been equal and no updates have been made in my environment. 

Have you encountered this problem already and can you think of a solution ? 

Kind regards 

Marcel 

Error: 

Pulp: Error while trying to execute /usr/local/lib/python3.6/dist-packages/pulp/solverdir/cbc/linux/64/cbc  
-----------------------------------------------------------------------------
File "algorithm_management.py", line 868, in retrieve_portfolio_info
    **allocation, leftover = discrete_allocation.lp_portfolio()**
  File "/usr/local/lib/python3.6/dist-packages/pypfopt/discrete_allocation.py", line 322, in lp_portfolio
    opt.solve()
  File "/usr/local/lib/python3.6/dist-packages/pulp/pulp.py", line 1713, in solve
    status = solver.actualSolve(self, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pulp/solvers.py", line 1408, in actualSolve
    return self.solve_CBC(lp, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/pulp/solvers.py", line 1476, in solve_CBC
    if cbc.wait() != 0:
  File "/usr/lib/python3.6/subprocess.py", line 1477, in wait
    (pid, sts) = self._try_wait(0)
  File "/usr/lib/python3.6/subprocess.py", line 1424, in _try_wait
    (pid, sts) = os.waitpid(self.pid, wait_flags)

**Comment by MarcelKresse** [comment]
Updating pulp fixes the issue. 

Thank you for the awesome package and keep up the good work!

Cheers

Marcel

**Comment by robertmartin8** [comment]
@MarcelKresse 

Just so I know for future users, what was the error?

**Comment by MarcelKresse** [comment]
Here is a description of what happened. 

I am running ppopt as the default portfolio optimisation algorithm of my algo-trading strategy. 

I am rebalancing my portfolio daily. Yesterday and the months before everything was working flawlessly. Today exception handling mailed me the following exception. 

Pulp: Error while trying to execute /usr/local/lib/python3.6/dist-packages/pulp/solverdir/cbc/linux/64/cbc

When running the script to locate the issue I noticed that the algorithm timed out when it calculated the discrete allocation.

When I keyboard interrupted the algorithm I saw the following error message: 

allocation, leftover = discrete_allocation.lp_portfolio()
File "/usr/local/lib/python3.6/dist-packages/pypfopt/discrete_allocation.py", line 322, in lp_portfolio
opt.solve()
File "/usr/local/lib/python3.6/dist-packages/pulp/pulp.py", line 1713, in solve
status = solver.actualSolve(self, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/pulp/solvers.py", line 1408, in actualSolve
return self.solve_CBC(lp, **kwargs)
File "/usr/local/lib/python3.6/dist-packages/pulp/solvers.py", line 1476, in solve_CBC
if cbc.wait() != 0:
File "/usr/lib/python3.6/subprocess.py", line 1477, in wait
(pid, sts) = self._try_wait(0)
File "/usr/lib/python3.6/subprocess.py", line 1424, in _try_wait
(pid, sts) = os.waitpid(self.pid, wait_flags)

I saw in the error message that the bug was related to the python package pulp. Updating pulp eventually fixed the issue. 

I cannot exactly say what caused the issue as i have not made any changes to the algorithm or the environment. 

The issue occurred on my local machine and on the cloud server I am using. 

Updating pulp fixed the issue on both machines.

**Comment by robertmartin8** [comment]
I see – really sorry about that and hope it wasn't a major outage. 

I'm a little confused about why that happened – was it an issue with PyPortfolioOpt's packaging? I pushed an update yesterday so maybe that changed something?

**Comment by MarcelKresse** [comment]
No, it fortunately wasn’t. PyPortfolioOpt just timed out and did not return the discrete weights. Thanks to exception handling I noticed and fixed the bug quickly. 

I cannot exactly say and I was also a little confused this morning when I saw, that an error was raised in a process which was working stable for months. 

What I found out is, that It seems to be an issue with the dependency package pulp, which is apparently used to calculate the discrete weights. I never used that package and did not install or update any packages during the last days.

But this raises another interesting question. If you push an update, are the changes reflected immediately in the package I am using in production? I thought that updates will only go into effect after I update the package. 

This would be interesting to know in general and may help to locate the issue.

**Comment by robertmartin8** [comment]
No it shouldn't affect your package, but sometimes people have an automated script that pulls the latest version. 

If you've been working with explicit pip installs it shouldn't affect. 

But yeah that's just a weird coincidence then.
