### ISSUE TITLE
CLA class efficient frontier issues

### ISSUE THREAD

**Issue by edgetrader** [robertmartin8/PyPortfolioOpt#81]
Hi,

Attached is the jupyter notebook highlighting 2 issues:

1. Plotting of efficient frontier will need weights to be computed via max_sharpe or min_volatility? Setting weights will not work?
2. CLA class does not work for a portfolio with only 2 assets?

[cla_ef_issue.zip](https://github.com/robertmartin8/PyPortfolioOpt/files/4367897/cla_ef_issue.zip)

**Comment by robertmartin8** [comment]
Hi @edgetrader, really appreciate the testing as always!

As for point 1, what exactly are you trying to achieve? Is it that you want to plot the red cross at a different location? The efficient frontier itself does not depend on a particular set of weights.

As for number 2, it is indeed a silly bug. Basically, I used some lazy logic to determine whether the user was passing a list of bounds e.g `[(0,1), (0, 0.8), (0.3, 0.6), ...]` or passing a single `(lower, upper)` pair. I will fix this now.

Best,
Robert

**Comment by edgetrader** [comment]
Hi,

For point 1, I had just wanted to plot the efficient frontier.  However, the function is complaining that the weights are not yet computed.  

Hence, for now, to plot the efficient frontier, I will need to run min_volatility or max_sharpe first.  Setting weights will not work too.

**Comment by robertmartin8** [comment]
Regarding the weights not being computed, you are right – that's a bug. I've fixed that now.

Setting weights is not meant to change anything – the efficient frontier is not a function of a given set of weights, it is meant to be generated from a large number of weight combinations.
