### ISSUE TITLE
Cannot install it using pip install PyPortfolioOpt

### ISSUE THREAD

**Issue by xchxing** [robertmartin8/PyPortfolioOpt#84]
Requirement already satisfied: PyPortfolioOpt in ./anaconda3/lib/python3.7/site-packages/PyPortfolioOpt-1.0.2-py3.7.egg (1.0.2)
Requirement already satisfied: numpy in ./anaconda3/lib/python3.7/site-packages (from PyPortfolioOpt) (1.18.1)
Requirement already satisfied: pandas in ./anaconda3/lib/python3.7/site-packages (from PyPortfolioOpt) (0.25.3)
Requirement already satisfied: scipy in ./anaconda3/lib/python3.7/site-packages (from PyPortfolioOpt) (1.4.1)
Requirement already satisfied: cvxpy in ./anaconda3/lib/python3.7/site-packages/cvxpy-1.1.0a3-py3.7-macosx-10.7-x86_64.egg (from PyPortfolioOpt) (1.1.0a3)
Requirement already satisfied: python-dateutil>=2.6.1 in ./anaconda3/lib/python3.7/site-packages (from pandas->PyPortfolioOpt) (2.8.1)
Requirement already satisfied: pytz>=2017.2 in ./anaconda3/lib/python3.7/site-packages (from pandas->PyPortfolioOpt) (2019.3)
Collecting ecos>=2
  Using cached ecos-2.0.7.post1.tar.gz (126 kB)
Requirement already satisfied: osqp>=0.4.1 in ./anaconda3/lib/python3.7/site-packages (from cvxpy->PyPortfolioOpt) (0.6.1)
Collecting scs>=1.1.3
  Using cached scs-2.1.2.tar.gz (3.5 MB)
Requirement already satisfied: six>=1.5 in ./anaconda3/lib/python3.7/site-packages (from python-dateutil>=2.6.1->pandas->PyPortfolioOpt) (1.14.0)
Requirement already satisfied: future in ./anaconda3/lib/python3.7/site-packages (from osqp>=0.4.1->cvxpy->PyPortfolioOpt) (0.18.2)
Building wheels for collected packages: ecos, scs
  Building wheel for ecos (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/xing/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/w9/by1fnry12_95625xcgn7nv6m0000gn/T/pip-install-ww2hg676/ecos/setup.py'"'"'; __file__='"'"'/private/var/folders/w9/by1fnry12_95625xcgn7nv6m0000gn/T/pip-install-ww2hg676/ecos/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/w9/by1fnry12_95625xcgn7nv6m0000gn/T/pip-wheel-yqyyln92
       cwd: /private/var/folders/w9/by1fnry12_95625xcgn7nv6m0000gn/T/pip-install-ww2hg676/ecos/
  Complete output (24 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.7-x86_64-3.7
  creating build/lib.macosx-10.7-x86_64-3.7/ecos
  copying src/ecos/version.py -> build/lib.macosx-10.7-x86_64-3.7/ecos
  copying src/ecos/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/ecos
  copying src/ecos/ecos.py -> build/lib.macosx-10.7-x86_64-3.7/ecos
  running build_ext
  building '_ecos' extension
  creating build/temp.macosx-10.7-x86_64-3.7
  creating build/temp.macosx-10.7-x86_64-3.7/src
  creating build/temp.macosx-10.7-x86_64-3.7/ecos
  creating build/temp.macosx-10.7-x86_64-3.7/ecos/external
  creating build/temp.macosx-10.7-x86_64-3.7/ecos/external/ldl
  creating build/temp.macosx-10.7-x86_64-3.7/ecos/external/ldl/src
  creating build/temp.macosx-10.7-x86_64-3.7/ecos/src
  creating build/temp.macosx-10.7-x86_64-3.7/ecos/external/amd
  creating build/temp.macosx-10.7-x86_64-3.7/ecos/external/amd/src
  creating build/temp.macosx-10.7-x86_64-3.7/ecos/ecos_bb
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/xing/anaconda3/include -arch x86_64 -I/Users/xing/anaconda3/include -arch x86_64 -DPYTHON -DDLONG -DLDL_LONG -DCTRLC=1 -Iecos/include -Iecos/external/amd/include -Iecos/external/ldl/include -Iecos/external/SuiteSparse_config -I/Users/xing/anaconda3/include/python3.7m -I/Users/xing/anaconda3/lib/python3.7/site-packages/numpy/core/include -c src/ecosmodule.c -o build/temp.macosx-10.7-x86_64-3.7/src/ecosmodule.o
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for ecos
  Running setup.py clean for ecos
  Building wheel for scs (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /Users/xing/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/w9/by1fnry12_95625xcgn7nv6m0000gn/T/pip-install-ww2hg676/scs/setup.py'"'"'; __file__='"'"'/private/var/folders/w9/by1fnry12_95625xcgn7nv6m0000gn/T/pip-install-ww2hg676/scs/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /private/var/folders/w9/by1fnry12_95625xcgn7nv6m0000gn/T/pip-wheel-k5j9zyt7
       cwd: /private/var/folders/w9/by1fnry12_95625xcgn7nv6m0000gn/T/pip-install-ww2hg676/scs/
  Complete output (59 lines):
  Namespace(blas64=False, extraverbose=False, float32=False, gpu=False, int32=False, scs=False)
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.macosx-10.7-x86_64-3.7
  creating build/lib.macosx-10.7-x86_64-3.7/scs
  copying src/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/scs
  running build_ext
  blas_mkl_info:
      libraries = ['mkl_rt', 'pthread']
      library_dirs = ['/Users/xing/anaconda3/lib']
      define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
      include_dirs = ['/Users/xing/anaconda3/include']
  blas_opt_info:
      libraries = ['mkl_rt', 'pthread']
      library_dirs = ['/Users/xing/anaconda3/lib']
      define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
      include_dirs = ['/Users/xing/anaconda3/include']
  lapack_mkl_info:
      libraries = ['mkl_rt', 'pthread']
      library_dirs = ['/Users/xing/anaconda3/lib']
      define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
      include_dirs = ['/Users/xing/anaconda3/include']
  lapack_opt_info:
      libraries = ['mkl_rt', 'pthread']
      library_dirs = ['/Users/xing/anaconda3/lib']
      define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
      include_dirs = ['/Users/xing/anaconda3/include']
  {'libraries': ['mkl_rt', 'pthread'], 'library_dirs': ['/Users/xing/anaconda3/lib'], 'define_macros': [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)], 'include_dirs': ['/Users/xing/anaconda3/include']}
  {'libraries': ['mkl_rt', 'pthread'], 'library_dirs': ['/Users/xing/anaconda3/lib'], 'define_macros': [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)], 'include_dirs': ['/Users/xing/anaconda3/include']}
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
  error: Command "gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/xing/anaconda3/include -arch x86_64 -I/Users/xing/anaconda3/include -arch x86_64 -DPYTHON -DCTRLC=1 -DDLONG=1 -DCOPYAMATRIX -DUSE_LAPACK -DSCIPY_MKL_H -DHAVE_CBLAS -DSCIPY_MKL_H -DHAVE_CBLAS -Iscs/include -Iscs/linsys -Iscs/linsys/cpu/direct/ -Iscs/linsys/external/amd -Iscs/linsys/external/dqlql -I/Users/xing/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/Users/xing/anaconda3/include -I/Users/xing/anaconda3/include -I/Users/xing/anaconda3/include/python3.7m -c scs/src/util.c -o build/temp.macosx-10.7-x86_64-3.7/scs/src/util.o -O3" failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for scs
  Running setup.py clean for scs
Failed to build ecos scs
Installing collected packages: ecos, scs
    Running setup.py install for ecos ... error
    ERROR: Command errored out with exit status 1:
     command: /Users/xing/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/w9/by1fnry12_95625xcgn7nv6m0000gn/T/pip-install-ww2hg676/ecos/setup.py'"'"'; __file__='"'"'/private/var/folders/w9/by1fnry12_95625xcgn7nv6m0000gn/T/pip-install-ww2hg676/ecos/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/w9/by1fnry12_95625xcgn7nv6m0000gn/T/pip-record-c18ys53k/install-record.txt --single-version-externally-managed --compile --install-headers /Users/xing/anaconda3/include/python3.7m/ecos
         cwd: /private/var/folders/w9/by1fnry12_95625xcgn7nv6m0000gn/T/pip-install-ww2hg676/ecos/
    Complete output (24 lines):
    running install
    running build
    running build_py
    creating build
    creating build/lib.macosx-10.7-x86_64-3.7
    creating build/lib.macosx-10.7-x86_64-3.7/ecos
    copying src/ecos/version.py -> build/lib.macosx-10.7-x86_64-3.7/ecos
    copying src/ecos/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/ecos
    copying src/ecos/ecos.py -> build/lib.macosx-10.7-x86_64-3.7/ecos
    running build_ext
    building '_ecos' extension
    creating build/temp.macosx-10.7-x86_64-3.7
    creating build/temp.macosx-10.7-x86_64-3.7/src
    creating build/temp.macosx-10.7-x86_64-3.7/ecos
    creating build/temp.macosx-10.7-x86_64-3.7/ecos/external
    creating build/temp.macosx-10.7-x86_64-3.7/ecos/external/ldl
    creating build/temp.macosx-10.7-x86_64-3.7/ecos/external/ldl/src
    creating build/temp.macosx-10.7-x86_64-3.7/ecos/src
    creating build/temp.macosx-10.7-x86_64-3.7/ecos/external/amd
    creating build/temp.macosx-10.7-x86_64-3.7/ecos/external/amd/src
    creating build/temp.macosx-10.7-x86_64-3.7/ecos/ecos_bb
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/xing/anaconda3/include -arch x86_64 -I/Users/xing/anaconda3/include -arch x86_64 -DPYTHON -DDLONG -DLDL_LONG -DCTRLC=1 -Iecos/include -Iecos/external/amd/include -Iecos/external/ldl/include -Iecos/external/SuiteSparse_config -I/Users/xing/anaconda3/include/python3.7m -I/Users/xing/anaconda3/lib/python3.7/site-packages/numpy/core/include -c src/ecosmodule.c -o build/temp.macosx-10.7-x86_64-3.7/src/ecosmodule.o
    xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
ERROR: Command errored out with exit status 1: /Users/xing/anaconda3/bin/python -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/w9/by1fnry12_95625xcgn7nv6m0000gn/T/pip-install-ww2hg676/ecos/setup.py'"'"'; __file__='"'"'/private/var/folders/w9/by1fnry12_95625xcgn7nv6m0000gn/T/pip-install-ww2hg676/ecos/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /private/var/folders/w9/by1fnry12_95625xcgn7nv6m0000gn/T/pip-record-c18ys53k/install-record.txt --single-version-externally-managed --compile --install-headers /Users/xing/anaconda3/include/python3.7m/ecos Check the logs for full command output.

**Comment by robertmartin8** [comment]
Hi,

So it looks like it's not able to install `ecos`, which is a solver that `cvxpy` requires. I'm not great at debugging these install issues, so you'll have to be patient with me :) Here are some things that might be worth trying.

Have you installed the latest developer tools? I notice this line in the above:

```
xcrun: error: invalid active developer path (/Library/Developer/CommandLineTools), missing xcrun at: /Library/Developer/CommandLineTools/usr/bin/xcrun
```

Sometimes this can be fixed by running `xcode-select --install`. After doing this, try `pip install PyPortfolioOpt` again.

If that doesn't work, try `pip install cvxpy` to verify that you get the same error. Then, run `conda install ecos` and try to `pip install cvxpy` again. 

Let me know if this doesn't work and we'll try to figure out some other solution.

Best,
Robert

**Comment by xchxing** [comment]
Hi Robert,

Your suggestion works!

Thanks a lot,
Xing
