### ISSUE TITLE
backtest integration

### ISSUE THREAD

**Issue by trbck** [robertmartin8/PyPortfolioOpt#9]
You put it on your roadmap already but I would like to integrate this into a backtrader backtest. Where you think I should start?

**Comment by robertmartin8** [comment]
Luckily, backtrader has [fantastic docs](https://www.backtrader.com/docu/index.html) which should give you a decent overview of the overall API. Though I haven't done an implementation myself, basically you will need to connect a data feed, e.g of stock daily data, then every 252 days (or whatever period you'd like to use), train a PyPortfolioOpt model on previous data and treat the resulting portfolio as a set of 'buy' signals. The quantity to buy can be calculated with `pypfopt.discrete_allocation`. Hope this helps!

Robert

**Comment by trbck** [comment]
Thanks! I was also (rather) trying to understand how you would integrate PyPortfolioOpt into a daily frequency backtest where I would re-evaluate per day the current portfolio items and derive signals as you mentioned. Even better, a combination with new buy signals (e.g. crossing set of moving averages) triggered per day and as a result would iniate multiple portfolio setups to find the best solution. The training would take too long for that..

**Comment by robertmartin8** [comment]
In my experience, portfolio optimisation over short time horizons isn't as effective as one would hope, because you will get eaten alive by transaction cost and slippage. 

However, depending on which algorithm you use (and the size of your training window), I don't think the training time would be excessively onerous (though definitely much slower than you other signals).

**Comment by schneiderfelipe** [comment]
Just a thought: is the price data format accepted by e.g. `expected_returns.mean_historical_return` the same as what backtrader expects?

**Comment by robertmartin8** [comment]
@schneiderfelipe I really doubt it – to be honest I've never quite figured out how to get data for multiple stocks into backtrader. From what I understand (based on their [docs](https://www.backtrader.com/docu/datafeed/)), it's more suited to a single feed of OHLC data.
