### ISSUE TITLE
Changing weights in portfolio_performance

### ISSUE THREAD

**Issue by nojaba** [robertmartin8/PyPortfolioOpt#93]
Hi,
I have a question about the possibility of passing the weights variable to ef.portfolio_performance.
In the base_optimizer.portfolio_performance the parameter weights exists but in ef it could not be passed. When we use weights = ef.max_sharpe() we could get the weights but changing the values is not possible in the ef.portfolio_performance(True, risk_free_rate).
I want to use it not for optimization but for validating some portfolios and get its performance and sharpe ratio on a specific percents of each. Is it a way to change the weights or pass it from the ef.portfolio_performance(self, verbose=False, risk_free_rate=0.02):
Thanks for your respond
Barmak

**Comment by robertmartin8** [comment]
Hi @nojaba,

Thanks for reaching out! If you want to use just the `portfolio_performance` function independent of any optimizer:

```python
from pypfopt.base_optimizer import portfolio_performance

portfolio_performance(weights, expected_returns_ cov_matrix, verbose=True, risk_free_rate=0.02)
```

I should probably add this to the docs somewhere

Best,
Robert
