### ISSUE TITLE
Examples.py,ln 84: parameter has changed in method efficient_risk

### ISSUE THREAD

**Issue by bvonboyen** [robertmartin8/PyPortfolioOpt#96]
In file examples.py: method is called with parameter "target_risk", should be (in module) "target_volatility".

I am completely new to Github; would be a good case to learn. What can I contribute?

**Comment by robertmartin8** [comment]
Hi @bvonboyen,

Good catch! You can submit that as a pull request if you'd like :) 

If you navigate to the `examples.py` file in GitHub, you can click the edit button in the top right and submit the fix (alternatively if you want to do it the long way, you can follow the instructions [here](https://www.freecodecamp.org/news/how-to-make-your-first-pull-request-on-github-3/)).

Thanks!

Robert

**Comment by bvonboyen** [comment]
Hi @robertmartin8 , thank you. As I came to stay, I will do this right away. ;-)
