### ISSUE TITLE
Poetry incompatibility

### ISSUE THREAD

**Issue by kivo360** [robertmartin8/PyPortfolioOpt#98]
When trying to install `pyportfolioopt` using poetry  I get the following installation error:

```bash
The current project's Python requirement (>=3.6.0) is not compatible with some of the required packages Python requirement:
  - pyportfolioopt requires Python >=3.6.0,<4.0.0

Because pyportfolioopt (1.1.0) requires Python >=3.6.0,<4.0.0
 and no versions of pyportfolioopt match >1.1.0,<2.0.0, pyportfolioopt is forbidden.
So, because darwin-handlers depends on pyportfolioopt (^1.1.0), version solving failed.
```

The problem. I have a installation clause for allowing any python version above 3.6. `python = ">=3.6.0"`. Essentially everything over 3.6.0, exactly as pyportfolioopt prefers. I've seen this kind of error in pipenv. I think it has much to do with the less than sign. The parser can't understand complex version queries. I don't know how to fix this. I at most know the nature of the problem.

**Comment by kivo360** [comment]
Hold on. Let me try the recommended changes. I ended up using raw pip, but I like poetry for package management reasons too.

**Comment by warraquiy** [comment]
I had an installation problem.
I tried to use google colab instead of installing on my machine and it works. 

If you want to install it on your machine you may use virtualenv it may help. I haven't try it yet. But I am planning to do it.

**Comment by robertmartin8** [comment]
I'm closing for now, but don't hesitate to reopen the issue if your problem persists!
